### ISSUE TITLE
plexdrive not updating directory structure

### ISSUE THREAD

**Issue by shindycham01** [dweidenfeld/plexdrive#100]
Hi, when I mount my googledrive with plexdrive the mount is stable and fast. But I experienced that even though uploading files and folders to my drive, the new files don't appear on the mount. 
I have already tried to remount the drive.

**Comment by mitchelp** [comment]
What is the version of plexdrive you using?
I can't reproduce this. Try the [Slack](https://plexdrive.slack.com/shared_invite/MTg1NTg5NzY2Njc4LTE0OTUwNDU3NzAtMjJjNWRiMTAxMg) channel

**Comment by animosity22** [comment]
You should see something like this in your logs as it updates files every 5 minutes:

```
[2017-05-18 23:10] INFO   : Processed 200 items / deleted 200 items / updated 0 items

```

Did you let the cache process finish up as well? You should see a 'start' and a 'complete' in the logs as well.

**Comment by mitchelp** [comment]
Before accessing the mount point.

I think this is kinda solved now. If @shindycham01 still has questions he can ask around on the slack channel.

**Comment by s0mm3rb** [comment]
@mitchelp wrote: 
> I think this is kinda solved now.

could you please post the solution?
I have the same issue

**Comment by zmike808** [comment]
> @mitchelp wrote:
> 
> > I think this is kinda solved now.
> 
> could you please post the solution?
> I have the same issue
> 
> thanks

Post your current plexdrive mount settings. along with any mergerfs (or if you use anything else shame on you and your family :P) settings as well. as well as themethod you use to upload the files to drive.
