### ISSUE TITLE
Crash when using clear-chunk-age + clear-chunk-max-size

### ISSUE THREAD

**Issue by f-santos** [dweidenfeld/plexdrive#104]
Using latest version 3.0.0, Debian stretch x86_64.

Mounted with options:
`--chunk-size=8M --clear-chunk-max-size=1G --fuse-options=allow_other,read_only --clear-chunk-age=30m --refresh-interval=5m --temp=/dev/shm`

Possible race condition between options, tried local folder also, same outcome. Haven't really looked in the code yet, but my guess is that the chunk file is removed by clear-chunk-max-size before it crashes when removing the file by time.
In my case its reproducible when reading thousands of files for +15m

```
#033[0mpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7c0b08]
goroutine 1172315 [running]:
main.deleteOldestFile.func1(0xc4226ccbd0, 0x2c, 0x0, 0x0, 0xd646e0, 0xc4226ccc30, 0x0, 0x0)
#011/go/src/github.com/dweidenfeld/plexdrive/buffer.go:271 +0x38
path/filepath.walk(0xc4201a3870, 0xf, 0xd6b2a0, 0xc4226d8f70, 0xc420693e00, 0x0, 0x20)
#011/usr/local/go/src/path/filepath/path.go:372 +0x2fe
path/filepath.Walk(0xc4201a3870, 0xf, 0xc420693e00, 0x8ed800, 0x0)
#011/usr/local/go/src/path/filepath/path.go:398 +0x14c
main.deleteOldestFile(0xc4201a3870, 0xf, 0x4583c9ba, 0x0)
#011/go/src/github.com/dweidenfeld/plexdrive/buffer.go:279 +0x119
main.cleanChunkDir(0xc4201a3870, 0xf, 0xc4200de180, 0xd68a20)
#011/go/src/github.com/dweidenfeld/plexdrive/buffer.go:257 +0x98
main.(*Buffer).ReadBytes.func2()
#011/go/src/github.com/dweidenfeld/plexdrive/buffer.go:170 +0x3d
created by main.(*Buffer).ReadBytes
#011/go/src/github.com/dweidenfeld/plexdrive/buffer.go:174 +0x1393
```

**Comment by sbcrumb** [comment]
Also getting the same thing as well. Latest version 3.0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7c0b08]

goroutine 4491932 [running]:
main.deleteOldestFile.func1(0xc430fbccc0, 0x3c, 0x0, 0x0, 0xd646e0, 0xc4311daed0, 0x0, 0x0)
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:271 +0x38
path/filepath.walk(0xc430fbcb80, 0x32, 0xd6b2a0, 0xc4219e6340, 0xc431057760, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:372 +0x2fe
path/filepath.walk(0xc4201d4100, 0x15, 0xd6b2a0, 0xc4227fc270, 0xc431057760, 0x0, 0x20)
        /usr/local/go/src/path/filepath/path.go:376 +0x414
path/filepath.Walk(0xc4201d4100, 0x15, 0xc431057760, 0x8ed800, 0x0)
        /usr/local/go/src/path/filepath/path.go:398 +0x14c
main.deleteOldestFile(0xc4201d4100, 0x15, 0xdabaf8903, 0x0)
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:279 +0x119
main.cleanChunkDir(0xc4201d4100, 0x15, 0xc420186300, 0xd68a20)
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:257 +0x98
main.(*Buffer).ReadBytes.func2()
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:170 +0x3d
created by main.(*Buffer).ReadBytes
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:174 +0x1393

**Comment by kageurufu** [comment]
Reproduced here with just ``-v 2 -o allow_other``

**Comment by mattlemay28** [comment]
Same here
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7c0b08]

goroutine 4995638 [running]:
main.deleteOldestFile.func1(0xc424a24fc0, 0x68, 0x0, 0x0, 0xd646e0, 0xc42163e720, 0x0, 0x0)
	/go/src/github.com/dweidenfeld/plexdrive/buffer.go:271 +0x38
path/filepath.walk(0xc424c08420, 0x5d, 0xd6b2a0, 0xc42154c4e0, 0xc4205b8140, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:372 +0x2fe
path/filepath.walk(0xc4201a1ec0, 0x40, 0xd6b2a0, 0xc42154c410, 0xc4205b8140, 0x0, 0x20)
	/usr/local/go/src/path/filepath/path.go:376 +0x414
path/filepath.Walk(0xc4201a1ec0, 0x40, 0xc4205b8140, 0x8ed800, 0x0)
	/usr/local/go/src/path/filepath/path.go:398 +0x14c
main.deleteOldestFile(0xc4201a1ec0, 0x40, 0x13fab03fe, 0x0)
	/go/src/github.com/dweidenfeld/plexdrive/buffer.go:279 +0x119
main.cleanChunkDir(0xc4201a1ec0, 0x40, 0xc4200da180, 0x438c48)
	/go/src/github.com/dweidenfeld/plexdrive/buffer.go:257 +0x98
main.(*Buffer).ReadBytes.func2()
	/go/src/github.com/dweidenfeld/plexdrive/buffer.go:170 +0x3d
created by main.(*Buffer).ReadBytes
	/go/src/github.com/dweidenfeld/plexdrive/buffer.go:174 +0x1393
```
The command I'm using to start is
`plexdrive -v 2 -c ~/.plexdrive_GDrive1.conf -t /tmp/gde1 --clear-chunk-age=1440m0s --clear-chunk-max-size=5G /mnt/raw/GDrive1/`

Further, it doesn't happen automatically, but rather after several hours to even a day

Running on Linux Mint 18.1 x64, version 3.0.0 downloaded from the releases section

**Comment by animosity22** [comment]
How many concurrent streams are going on when you are playing things and why have the max size so small?

I'm streaming 2 Movies atm and if you give it a little more size, I'd surmise the problem would go away. 1G is definitely way too tiny to stream. My one movie has 2.4G in chunks and the second has 1.5G in a single folder.

```
felix@plex:/tmp/chunks$ du -sh *
11M	0By9RTGwjTUgObmUxQXpZTms1QW8
2.4G	0By9RTGwjTUgOc2xuMHVSakFhbEE
11M	0By9RTGwjTUgOcU04QzhsUkh1Mmc
11M	0By9RTGwjTUgOMHktOVVNSXpoSHM
11M	0By9RTGwjTUgOTEtRUGpnLXlTM28
11M	0By9RTGwjTUgOUlVoSDBkcF9LYkE
11M	0By9RTGwjTUgOUVRTQkN1TXBrOFE
11M	0By9RTGwjTUgOVkdXdGlZa2pzeTQ
11M	0By9RTGwjTUgOVlY2Z0RGVWlJLUE
1.5G	0By9RTGwjTUgOX0FDdDlJSlRmOUU
felix@plex:/tmp/chunks$
```

I think you are stomping on the files you need.

**Comment by lloydie2009** [comment]
I'm seeing this also, nothing else accessing the files, just a Plex library scan. I'm running on Ubuntu 14.04.

**Comment by stardustrider** [comment]
I'm having this issue too. Here is my launch config, possibly something in it is causing the crash/panic?: 

/usr/bin/plexdrive -c /home/<user>/.plexdrive -o allow_other -v 2 --chunk-size=10M --clear-chunk-max-size=100G --temp=/home/<user>/_files/chunk_temp --refresh-interval=5m --uid=1000 --gid=1000 /home/<user>/drive-encrypted

**Comment by dweidenfeld** [comment]
The options are exclusive, so they will not work together.

**Comment by onedr0p** [comment]
@dweidenfeld can you mention that in the readme to avoid further confusion? Thanks.

**Comment by dweidenfeld** [comment]
Done

**Comment by stardustrider** [comment]
Removal of --chunk-size=10M and --clear-chunk-max-size=100G from my launch args has fixed the crashing for me! Stable as a rock since.
