### ISSUE TITLE
WARNING: Could not get object root from API

### ISSUE THREAD

**Issue by TimoPtr** [dweidenfeld/plexdrive#105]
First set up with your tool I get :
[PLEXDRIVE-LINUX-AMD64-2] [2017-05-18 21:28] INFO   : Mounting path /mnt/Gdrive
[PLEXDRIVE-LINUX-AMD64-2] [2017-05-18 21:28] INFO   : Using clear-by-interval method for chunk cleaning
[PLEXDRIVE-LINUX-AMD64-2] [2017-05-18 21:28] INFO   : First cache build process started...
[PLEXDRIVE-LINUX-AMD64-2] [2017-05-18 21:28] WARNING: Could not get object root from API

and when I ls the directory I get : 
ls: cannot access /mnt/Gdrive: Transport endpoint is not connected

With v2 and v3 

It's work with rclone mount

**Comment by Em31Et** [comment]
First cache build process have not finished.
The cache is still building in background, you may **-v 3** to view the operation.

`INFO : First cache build process finished`
You will see this message when finished.

**Comment by animosity22** [comment]
For me 30TB took about 18 minutes to cache. It went pretty fast, but you do have to wait it out.

**Comment by mitchelp** [comment]
@TimoPtr as @Em31Et already said, you should wait till the initial cache build has finished before accessing the mount point.
