### ISSUE TITLE
Bad performance after cache built completed

### ISSUE THREAD

**Issue by Keeperjoey** [dweidenfeld/plexdrive#107]
The cache was completed but my performance is really slow. 

My mount command is: 

`./plexdrives -o allow_other --chunk-size=20M  -v 3 --refresh-interval=30m /home/plex/amazonencrypt `

and my log during playback:

```
[PLEXDRIVES] [2017-05-19 02:57] DEBUG  : Requesting object 0BykRFuXuzv1wZEpKQzVMcnJxOVE bytes 146800640 - 167772160 from API
[PLEXDRIVES] [2017-05-19 02:57] DEBUG  : Requesting object 0BykRFuXuzv1wZEpKQzVMcnJxOVE bytes 167772160 - 188743680 from API
[PLEXDRIVES] [2017-05-19 02:57] DEBUG  : Requesting object 0BykRFuXuzv1wZEpKQzVMcnJxOVE bytes 188743680 - 209715200 from API
[PLEXDRIVES] [2017-05-19 02:57] DEBUG  : Requesting object 0BykRFuXuzv1wZEpKQzVMcnJxOVE bytes 209715200 - 230686720 from API
[PLEXDRIVES] [2017-05-19 02:57] DEBUG  : Cleaning chunk directory /tmp/chunks
[PLEXDRIVES] [2017-05-19 02:57] DEBUG  : Requesting object 0BykRFuXuzv1wZEpKQzVMcnJxOVE bytes 230686720 - 251658240 from API
[PLEXDRIVES] [2017-05-19 02:57] DEBUG  : Requesting object 0BykRFuXuzv1wZEpKQzVMcnJxOVE bytes 251658240 - 272629760 from API
[PLEXDRIVES] [2017-05-19 02:58] DEBUG  : Requesting object 0BykRFuXuzv1wZEpKQzVMcnJxOVE bytes 272629760 - 293601280 from API

```

If I do an PV command for the same file in plexdrive or rclone I get way different performance

plexdrive: 
0:03:33 [1.72MiB/s] [====>                             ] 17% ETA 0:16:37 

rclone
0:00:05  [63.6MiB/s] [===>                              ] 13% ETA 0:00:16

My server is located in germany. If you need to know anything more I am happy to hear.

**Comment by animosity22** [comment]
You seem to be comparing 2 different things. Plexdrive isn't built to download fast like rclone. 

It's built to stream. Are you having a problem streaming a file?

**Comment by mitchelp** [comment]
I think that @Keeperjoey should read the README and ask around on our Slack channel.
There are no issues and it isn't fast. Its just made for streaming as @animosity22 alread said.

**Comment by Keeperjoey** [comment]
@animosity22 @mitchhelp yes I cannot play one 4 Mbs file...  I will see if I can get it to work via the slack chat
