### ISSUE TITLE
Not clearing cache

### ISSUE THREAD

**Issue by PiscisSwimeatus** [dweidenfeld/plexdrive#109]
Version 3.0.0
/home/rclone/plexdrive --verbosity=3 --fuse-options=allow_other,read_only --temp=/dev/shm --clear-chunk-max-size=8G /media/PMS

13GB used, oldest chuck currently 40min old
tmpfs            32G   13G   20G  38% /dev/shm

**Comment by mitchelp** [comment]
I don't have those issues and didnt notice anybody else does. Ask around at our slack channel.
