### ISSUE TITLE
Temp folder should inherit the parent folders permissions

### ISSUE THREAD

**Issue by PiscisSwimeatus** [dweidenfeld/plexdrive#111]
It would be nice if the temp folder could inherit the permissions, incase of multi user setups.

:/tmp$ ls -al
drwxrwxrwt  10 root   root    4096 May 19 22:11 .
drwxrwxr-x 168 rclone rclone 12288 May 19 22:15 chunks

**Comment by animosity22** [comment]
So not sure what you mean, but you can set the uid/gid of plexdrive.

You can also set the umask to set the proper rwx if you want.

You can also change the location for multi user setups.

If I'm reading correctly, I think you want to change the umask.

Some examples:
```
felix@plex:~$ umask
0002
felix@plex:~$ touch test
felix@plex:~$ ls -al test
total 8
drwxrwxr-x  2 felix felix 4096 May 19 16:21 .
drwxr-xr-x 26 felix felix 4096 May 19 06:25 ..
felix@plex:~$ rmdir test
felix@plex:~$ touch test
felix@plex:~$ ls -al test
-rw-rw-r-- 1 felix felix 0 May 19 16:21 test
felix@plex:~$ umask 022
felix@plex:~$ rm test
felix@plex:~$ touch test
felix@plex:~$ ls -al test
-rw-r--r-- 1 felix felix 0 May 19 16:21 test
felix@plex:~$ rm test
felix@plex:~$ umask 077
felix@plex:~$ touch test
felix@plex:~$ ls -al test
-rw------- 1 felix felix 0 May 19 16:21 test
felix@plex:~$ rm test
felix@plex:~$ mkdir test
felix@plex:~$ ls -al | grep test
drwx------  2 felix felix  4096 May 19 16:21 test
```

**Comment by PiscisSwimeatus** [comment]
Ahh ill test if the umask parameter works on the temp folder thanks.

**Comment by PiscisSwimeatus** [comment]
Looks like the temp folder is set in the program

plexdrive --umask=0000  /media/PMS

aj@Plex:/tmp$ umask
0000
aj@Plex:/tmp$ ls -al
total 40
drwxrwxrwt 10 root   root   4096 May 19 22:33 .
drwxr-xr-x 23 root   root   4096 May 17 19:55 ..
drwxrwxr-x  2 rclone rclone 4096 May 19 22:33 chunks

**Comment by animosity22** [comment]
I removed the dir before and than re-ran it as an example with 077:

```
drwx------ 2 felix felix  4096 May 19 16:43 chunks
felix@plex:/tmp$ ps -ef | grep plexdrive
felix     6859  6858 52 16:43 pts/1    00:00:06 /home/felix/scripts/plexdrive --umask=077 --chunk-size=26214400 -o allow_other -v 2 /GD
```

**Comment by animosity22** [comment]
@dweidenfeld  - the command helps says "umask int" but you need to do "umask=077". Just need to fix the command help or change the syntax.

**Comment by PiscisSwimeatus** [comment]
Strange your test looks good, but I'm unable to get the "others write" permission. Could you see if you able to get a 777 temp folder with umask 000 on a 777 dir.

**Comment by animosity22** [comment]
Seemed fine. You have to delete it first:

```
felix@plex:~$ rmdir /tmp/chunks/

felix@plex:~$ ls -al /tmp | grep chu
drwxrwxrwx  2 felix   felix    4096 May 19 16:58 chunks

felix@plex:~$ ps -ef | grep plexdrive
felix     8430  8429 64 16:58 pts/2    00:00:12 /home/felix/scripts/plexdrive --umask=000 --chunk-size=26214400 -o allow_other -v 2 /GD
```

**Comment by PiscisSwimeatus** [comment]
Closing this for now, I'm getting the correct/same result as you now, dont know why there was an issues previously.
