### ISSUE TITLE
Stream not buffering quickly enough, specify buffer size similar to rclone?

### ISSUE THREAD

**Issue by peatnik** [dweidenfeld/plexdrive#112]
Hey,

rclone has a `--buffer-size` flag, which improved streaming a lot for me when set to a couple hundred MB, i.e. no more stuttering. Using plexdrive, i do notice occasional stuttering again.
How do i best emulate the --buffer-size behaviour of rclone with plexdrive? Is the chunk-size option the right tool? If so, what are the implications of setting the chunk-size to e.g. 400 MB. Will every request, even a quick sonarr scan, fetch 400 MB of every file? From what i understand, rclone handles streaming very differently so a quick explanation or recommendation would be great!
Thanks

**Comment by Em31Et** [comment]
more explanation [https://github.com/dweidenfeld/plexdrive/issues/55](url)

> e.g. 400 MB. Will every request, even a quick sonarr scan, fetch 400 MB of every file?
Yes

**Comment by animosity22** [comment]
You should have "Analyze Video Files" off or it's going to grab each file and analyze it every time in Sonarr, which isn't a good thing.

If you make the chunk size too big, you are going to wait to download 400MB each time you have to play something, which can lead to slow starts on the stream. 

Did you try with just the default settings and did it not work? I do just a little bigger, but in all honestly, I think leaving the default is just fine.

I use:

```
/home/felix/scripts/plexdrive --chunk-size=26214400 -o allow_other -v 2 /GD >>/home/felix/logs/plexdrive.log 2>&1 &
```

and that's it. I never see any buffer or slow starts.

What's your download as well?

**Comment by animosity22** [comment]
Also, if you have sufficient memory, you can use these settings:
```
Segmented transcoder timeout: 120
Transcoder temporary directory: /dev/shm
Transcoder default throttle buffer: 600
```

I'd do the 1st and 3rd definitely. I'd try to write the transcode to memory if you can, other write to a separate disk from you chunk directory.

**Comment by peatnik** [comment]
thanks, i'll just have to experiment.
but disabling sonarrs analyze function is not an option because i use filebot for post-processing/renaming which makes it hard for sonarr to track downloads.

**Comment by animosity22** [comment]
If you keep analyze on, it's going to go bonkers every time you refresh in sonnar and pull down a lot of data and it will read every file it has.

![image](https://cloud.githubusercontent.com/assets/5088712/26275568/e48fa106-3d31-11e7-9b1d-97869c11d274.png)

You can still have it refresh a show and track files, it just uses the filename information for this:

As an example:
![image](https://cloud.githubusercontent.com/assets/5088712/26275573/08be488e-3d32-11e7-8439-85063e54c6fd.png)


With analyze on, you'll notice your chunk drive go crazy and it grabs every show it monitors (Same with Radarr too)

**Comment by peatnik** [comment]
My plexdrive has been online for 1 day and 18 hours. 
In that time period, 2 radarr and 4 sonarr scans happened.
The chunk directory size is at 86GB now.
I'll keep watching it but that's not too terrible. Although i'm worried that the cleanup functionality is not working as most of those chunks should expire by default after 30 minutes, right?

//Offtopic: Do you know if sonarr will be able to read everything it needs from a non-standard file name like this:  "Show - S01E12 - Episode Name [720p, AVC, AAC].mkv"?

**Comment by animosity22** [comment]
I'm not sure on your latter question. I just use the standard plex naming definitions.

There is a long discussion on this here -> https://github.com/Sonarr/Sonarr/issues/448

To be safe,I keep mine turned off as I did see quite some activity when i was testing before, but maybe if it has the info, it won't analyze, kinda like Plex. I'm not familiar with with the Analyze, but have kept mine off for quite some time now.

**Comment by mitchelp** [comment]
I think that this is solved, it's more a discussion as a issue. Please use our slack channel for that.
