### ISSUE TITLE
Default chunk size and jumpy performance

### ISSUE THREAD

**Issue by erpalma** [dweidenfeld/plexdrive#114]
I'm trying plexdrive (coming from rclone, acd_cli) and I have noticed an irregular download speed when using default chunk size (5M). Usually I can easily saturate my 50 mbit connection but here I can see that the speed vary widley over time with an average of about 70% of my bw. Increasing log level I can see that this is probably due to the dead time between "consecutive"  chunks. Indeed increasing chunk size to an unpractical value of 500M allows me to achieve almost constant full bandwidth. Maybe we can start requesting next chunk a bit before the previous one is completed.

Thank you

**Comment by animosity22** [comment]
With the default values, you should be fine streaming. I use the following as my transcoder settings to just transcode to memory via plex and I write my plexdrive chunks to SSD:

```
Segmented transcoder timeout: 120
Transcoder temporary directory: /dev/shm
Transcoder default throttle buffer: 600
```

I would not expect to see the line saturated as it isn't rclone so you can't compare. You should see some spiky type performance as it grabs chunks to fill the transcode buffer and than sits.

Here's my bandwidth when a movie was playing. I think I have a download or two mixed in as well as I can't separate that out.

![image](https://cloud.githubusercontent.com/assets/5088712/26277656/eefa89d0-3d59-11e7-86f1-3e865239f6ed.png)

**Comment by mitchelp** [comment]
plexdrive isn't made for speed. It's just for streaming. So yes it isn't as fast as rclone.
