### ISSUE TITLE
Some items aren't cached. Unavailable in Plex. Version 3.0.

### ISSUE THREAD

**Issue by savi6566** [dweidenfeld/plexdrive#115]
Some items are marked as unavailable in plex after upgrading from 1.1.0 to 3.0. Cache was deleted first and remade. Tried remaking cache several times with same output. Reverted back down to 1.2.0 and my files are available.

**Comment by animosity22** [comment]
Did you let the cache finish completely building after deleted it? You saw a start and finish message?

```
[HOME/FELIX/SCRIPTS/PLEXDRIVE] [2017-05-20 11:18] INFO   : First cache build process started...
[HOME/FELIX/SCRIPTS/PLEXDRIVE] [2017-05-20 11:18] INFO   : First cache build process finished!
```

Can you share the logs show that message and share what is missing and the logs?

**Comment by jheyneman** [comment]
I switched to 3.0 and deleted my cache. With an older version, it finished in about a day with 400K files or so. This one has been running well over 24 hours building the cache and reports nearly 900K files, which is not correct.

**Comment by animosity22** [comment]
Man that's a lot of files.

I was 7:22 to 7:40 for 100k items:
```
[HOME/FELIX/SCRIPTS/PLEXDRIVE] [2017-05-18 07:40] INFO   : Processed 110329 items / deleted 98 items / updated 110231 items
```

If your cache isn't done, you'll get odd things with files not show up.

My complete GD is 1757 directories, 109393 files at 30TB.

**Comment by Em31Et** [comment]
@jheyneman 

> Warning: You should delete the local cache file first (~/.plexdrive/cache), otherwise, it could be that items are missing/duplicated in your mount. This is necessary because of the upgrade to API v3

**Comment by jheyneman** [comment]
I did delete it per the suggestion on the releases page.

**Comment by jheyneman** [comment]
I don't know what the hell is going on at this point. I certainly do not have that many files.

`[PLEXDRIVE] [2017-05-21 05:50] INFO   : Processed 1000040 items / deleted 9815 items / updated 990225 items
`

**Comment by animosity22** [comment]
Probably a solid start over.

Stop plexdrive, make sure all the processes are dead and delete the cache and start over.

**Comment by jheyneman** [comment]
@animosity22  I removed the cache files and rebooted the machine.  An hour later I have this:
`[PLEXDRIVE] [2017-05-21 16:50] INFO   : Processed 46460 items / deleted 6647 items / updated 39813 items`

There was nothing to delete or update, it's a brand new database.

**Comment by azgul** [comment]
items = transactions, not files

**Comment by azgul** [comment]
@dweidenfeld I think this issue might've been closed too soon.
```
sqlite> select count(*) from api_objects;
35875
```

```
sqlite> select count(*) from api_objects;
35881
```

this is on two databases that are both (supposedly) in sync where the first is a server that's running 24/7 on 3.0.0 exclusively and has been building the database over time (3-4 days at this point, I believe). The second is a fresh build.

I've seen both missing files and folders. For folders its children are in `api_objects` but their parent is not. Causing `ls` on the parent directory to turn out empty.

I am running `plexdrive` with `refresh-interval=1m`
