### ISSUE TITLE
[ QUESTION ] --clear-chunk-age & --clear-chunk-max-size

### ISSUE THREAD

**Issue by ajkis** [dweidenfeld/plexdrive#116]
For example if I set:
`--clear-chunk-max-size=400GB`  (to make sure disk does not get full)
`--clear-chunk-age=730h` ( to keep chunks for 1 month )

**1.**
I assume when `--clear-chunk-max-size` get to 400GB the oldest (access wise) files will be deleted, regardless that `--clear-chunk-age` still did not match criteria ?

**2.**
If I replace/upgrade existing movie with better version (so same name) if the chunks for that movie where already downloaded, are they automatically replaced (when plex access them). 

**3.**
What happens if I delete all chunks while that were not accessed in last minute, would that cause any errors or plexdrive automatically downloaded them when needed ?

I made script to keep chunks 30days and manually deleting them if my disk space gets bellow 1GB
https://github.com/ajkis/scripts/blob/master/plexdrive/plexdrivechunks.sh

**Comment by ajkis** [comment]
It seems there is a race issue: https://github.com/dweidenfeld/plexdrive/issues/104

**Comment by Em31Et** [comment]
@ajkis 
It is not a race issue.
If **--clear-chunk-max-size** is set, --clear-chunk-age is disabled (do not have any effect)
[Source Code](https://github.com/dweidenfeld/plexdrive/blob/master/clean.go#L14)

1) --clear-chunk-max-size have the highest priority.
