### ISSUE TITLE
[CRITICAL BUG] Files in database not showing up in file listing

### ISSUE THREAD

**Issue by zenjabba** [dweidenfeld/plexdrive#117]
I have files that have been put into the database, but they are not being presented to the file system. I'm happy to upload the cache privately so we can figure out what has gone wrong.

**Comment by zenjabba** [comment]
So after more research, I've found out that if the created_at field is AFTER the last_modified time, the plexdrive will not present the file to the file system.

`"1213282"	"0BxYemFFjZ8ptVDNPaFBnVTlkOTg"	"Teen.Witch.1989.1080p.BluRay.x264-SADPANDA.mkv"	"0"	"7031575412"	"2017-05-20 18:09:44.017+00:00"	"https://www.googleapis.com/drive/v3/files/0BxYemFFjZ8ptVDNPaFBnVTlkOTg?alt=media"	"|0BxYemFFjZ8ptdTB5OC1uSDFJOEU|"	"2017-05-20 19:46:13.559989026+00:00"`

**Comment by dweidenfeld** [comment]
Should be fixed in next release. It was a missing DeletedAt Property :+1:
