### ISSUE TITLE
Filename updated but PlexDrive getting confused with files [3.0.0]

### ISSUE THREAD

**Issue by zenjabba** [dweidenfeld/plexdrive#119]
<img width="321" alt="screen shot 2017-05-20 at 9 57 24 pm" src="https://cloud.githubusercontent.com/assets/679864/26280571/7098ff42-3da7-11e7-89f4-1c18834021c3.png">
<img width="591" alt="screen shot 2017-05-20 at 9 57 14 pm" src="https://cloud.githubusercontent.com/assets/679864/26280572/71cc8d48-3da7-11e7-9566-b10c0e2c2a4c.png">

Basically when Sonarr updates the files with fresh versions, PlexDrive doesn't fix up the database to correctly match GoogleDrive.

**Comment by zenjabba** [comment]
[SBIN/PLEXDRIVE] [2017-05-21 02:31] WARNING: Wrong status code &{404 Not Found 404 HTTP/2.0 2 0 map[X-Guploader-Uploadid:[AEnB2UoMKkOPZXG5cSHGvAjTg1rVnmYVef_OM6rZeETE52BDU9L1s28EzJPbE2hYWIxsD7dmbBgyyA9BTIDlyI9jOWseC44pQw] Content-Length:[296] Alt-Svc:[quic=":443"; ma=2592000; v="37,36,35"] Expires:[Sun, 21 May 2017 02:31:00 GMT] Cache-Control:[private, max-age=0] Server:[UploadServer] Vary:[Origin X-Origin] Content-Type:[application/json; charset=UTF-8] Date:[Sun, 21 May 2017 02:31:00 GMT]] 0xc420a4e5c0 296 [] false false map[] 0xc4201b3f00 0xc4205a24d0}
[SBIN/PLEXDRIVE] [2017-05-21 02:31] WARNING: Wrong status code &{404 Not Found 404 HTTP/2.0 2 0 map[Expires:[Sun, 21 May 2017 02:31:01 GMT] Content-Length:[296] Server:[UploadServer] Alt-Svc:[quic=":443"; ma=2592000; v="37,36,35"] Content-Type:[application/json; charset=UTF-8] Date:[Sun, 21 May 2017 02:31:01 GMT] Cache-Control:[private, max-age=0] X-Guploader-Uploadid:[AEnB2UodlVOIyDlgFyxwNPpw9MTLNkMcbWgzCvbrDAtlav21tFGKiGvSY4TjucleRwwD5FI9YeryEaoIUlrdfyjy7Aj_6jOa8Q] Vary:[Origin X-Origin]] 0xc420584c80 296 [] false false map[] 0xc42000ba00 0xc4205a24d0}

**Comment by dweidenfeld** [comment]
I never tested renaming files, yet .... will be an enhancement for a future release ;)

**Comment by dweidenfeld** [comment]
Fixed in next release (it was a side effect of the "missing files").
