### ISSUE TITLE
Multiple Config

### ISSUE THREAD

**Issue by dany20mh** [dweidenfeld/plexdrive#12]
Hi,

Thanks for all the support so far, this is just a request.

So I was wondering if you could be able to setup multiple config information for the mount, like what rclone do, it’s only one config file but include different mount location and profiles.

**Comment by jrarseneau** [comment]
Just use the `-config` string as identified in the README.

That way you could have multiple google drive accounts and mount them using :

`plexdrive -config ~/.google1 <mount point>`

**Comment by ronaldiu89** [comment]
Hi!

I am working with a friend trying to create a VPS with plexdrive. We want to add both accounts of google drive, his account and my account... We don't know nothing about linux, and is our first time using an VPS (Bytesized) and the PlexDrive. It is possible to add both accounts in the same VPS using Plexdrive?

I would beg all the help and clarification you can give me.

Thanks!

**Comment by RXWatcher1** [comment]
You would need to run two instances of plexdrive, each one would have its
own config dir and Mount point. If you wanted to tie them together so it
looked like a single drive then you need some type of unioning software
like unionfs or mergerfs.

Good luck!

**Comment by ronaldiu89** [comment]
Thanks!

No, I prefer that they look like two independent folders.

So to run two instances of plexdrive, what I need to do? Sorry again...I am new with linux VPS... I am following this manual: https://bytesized-hosting.com/pages/plexdrive

Thanks again

**Comment by ronaldiu89** [comment]
And It is possible to install two differents Plex Servers in the same VPS? I mean, we want to share the VPS, but each one want to have his own server and library...

Thanks.

**Comment by 2600box** [comment]
Easiest to manage would be to run them as different users, you can specify the user of your services in systemd config.
