### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by MorphyDK** [dweidenfeld/plexdrive#120]
Hi dweidenfeld.

I installed v.3.0.0. but before I started the , I deleted the cache as you informed us about.
Started my plex server and then plexdrive in screen, and then I see this "error": 

Running Ubuntu 16.04LTS 
i7 3930K
2 x 3TB HD in raid 0
64GB memory
1GB up/down.

plex@DevilBox:~$ fusermount -uz /home/plex/plexdata
fusermount: entry for /home/plex/plexdata not found in /etc/mtab
plex@DevilBox:~$ plexdrive --uid=1002 --gid=1002 -o allow_other -v 2 /home/plex/plexdata --refresh-interval=1m -c /home/plex/.plexdrive/
[PLEXDRIVE] [2017-05-21 15:01] INFO   : Mounting path /home/plex/plexdata
[PLEXDRIVE] [2017-05-21 15:01] INFO   : Using clear-by-interval method for chunk cleaning
[PLEXDRIVE] [2017-05-21 15:01] INFO   : First cache build process started...
[PLEXDRIVE] [2017-05-21 15:02] INFO   : Processed 460 items / deleted 96 items / updated 364 items
[PLEXDRIVE] [2017-05-21 15:03] INFO   : Processed 920 items / deleted 179 items / updated 741 items
[PLEXDRIVE] [2017-05-21 15:04] INFO   : Processed 1380 items / deleted 179 items / updated 1201 items
[PLEXDRIVE] [2017-05-21 15:04] INFO   : Unmounting path /home/plex/plexdata
panic: send on closed channel

goroutine 71 [running]:
main.(*Drive).startWatchChanges.func1(0xc4200e9e01)
       /go/src/github.com/dweidenfeld/plexdrive/drive.go:125 +0x7c6
main.(*Drive).startWatchChanges(0xc4200e9ec0, 0xdf8475800)
       /go/src/github.com/dweidenfeld/plexdrive/drive.go:157 +0x84
created by main.NewDriveClient
       /go/src/github.com/dweidenfeld/plexdrive/drive.go:67 +0x269

Everything seems to be running just fine - after this error.. Mount is still there, I can still stream my movies etc.. all is updating and working .

Dont know if its a bug or not.. but here you have the details as requested from Slack :)

**Comment by animosity22** [comment]
I'd delete the cache and wait for the cache to say "Finished" before accessing it.

**Comment by MorphyDK** [comment]
Ok but I couldn't access anything - the mounted folder came up as soon the scan was done.

**Comment by animosity22** [comment]
You should see a line like this when it's done:

```
] [2017-05-18 07:40] INFO   : First cache build process finished!
```

**Comment by MorphyDK** [comment]
I saw that :) . Everything is working as it should. I showed the "error" to dweidenfeld in Slack, he asked me to post in here  :) .

**Comment by animosity22** [comment]
Not based on the logs you posted in your opening post. It's not there.

**Comment by MorphyDK** [comment]
Its running fine . Media is available as well.

**Comment by mitchelp** [comment]
This issue is solved, closing..
