### ISSUE TITLE
Whilst Plexdrive is processing transactions, file system is NOT available

### ISSUE THREAD

**Issue by zenjabba** [dweidenfeld/plexdrive#123]
It seems what when transactions are being processed (after finishing the initial build) the file system waits for the transactions to complete before answering the call to present the file system.

On a very busy system (3000 transactions each min) it's killing me due to it writing each transaction to the SQL database on a slow old HDD. 

2 ideas.

1. Multithreaded transaction process
2. Create an option to have the SQL database fully populated into ram

**Comment by animosity22** [comment]
3. Put in a small SDD. They are pretty cheap these days and I put my plex library data and this on a SSD.
4. You can always copy it into /dev/shm or mount a small tmp filesystem from memory. Just have to copy it in and copy it out on startup/shutdown.

**Comment by zenjabba** [comment]
Hosting provider doesn't offer SSD.. I have 64gb of ram, would be a good idea to allow plexdrive to use it

yea, no...

**Comment by animosity22** [comment]
You can just do something like:

Shutdown plexdrive
Copy your .plexdrive into /dev/shm/plexdrive
Pass the -c and start it up with the /dev/shm/plexdrive
When you shutdown, copy back to your home directory so you don't lose changes on reboots.

That was my #4 with what I was saying.

**Comment by xyber411** [comment]
@animosity22 I wish I had your up-time confidence...

**Comment by animosity22** [comment]
@xyber411  - why? you normally aren't writing that many changes in between power outages. You could also cycle it each night at 3am or something. I run a small UPS at home as well to get an orderly shutdown. We're talking Linux here not Windows so I rarely ever experience a 'crash'.

His question was to use memory so I offered an option :)

**Comment by dweidenfeld** [comment]
I already thought about a RAM-only database. Will be implemented in an upcoming release

**Comment by dweidenfeld** [comment]
Implemented for next release.
