### ISSUE TITLE
Anyone else have an issue using --clear-chunk-max-size not working?

### ISSUE THREAD

**Issue by trulow** [dweidenfeld/plexdrive#127]
I am noticing that the --clear-chunk-max-size flag does not seem to be working since my /tmp/chunks directory is currently at 92G even though I have set --clear-chunk-max-size=10G with my run command. Anyone else seeing this issue?

Currently running the system under 14.04

**Comment by seuffert** [comment]
no problems here, working nicely with --clear-chunk-max-size=10G

**Comment by trulow** [comment]
@seuffert could you please list the full run command that you use so I can compare it to mine? Do you also use the -t flag when you run plexdrive?

**Comment by seuffert** [comment]
> plexdrive -c /home/DIR/config --chunk-size=5M --clear-chunk-age=24h --clear-chunk-max-size=10G -o allow_other,read_only -t /tmp/plexdrive/pd -v 2 /home/DIR/mountpoint

**Comment by xyber411** [comment]
I also have this issue. I am going to be removing all traces to start from scratch here in the next few hours.  I'll let you know how it goes. 
For my own, it has not deleted anything on its own since 1.1. I'm currently on 2.1, as 3.0 gave me issues. When I remove everything, I'll start again with 3.0.

**Comment by PiscisSwimeatus** [comment]
There is issues with clear-chunk-max-size. I have done quite a bit of testing on it. 1: It only deletes one chunk for each chunk it downloads. Therefore, the cache will never be smaller than it is when the app is started. 2: There is some leakage so the cache will grow bigger over time and due to #1 never get cleaned up.

**Comment by PiscisSwimeatus** [comment]
No need to rebuild the database. Just a manual delete of the cache/chunk folder.

**Comment by trulow** [comment]
@PiscisSwimeatus Thanks, I guess I can just have a script running on cron to clear out the cache once a day to prevent my server from filling up in the meantime.

**Comment by Dopefish123** [comment]
This is what I'm using (ajkis script as the base, but I'd deleting the whole chunk dirs instead):

PD:
--clear-chunk-interval=43800m0s --clear-chunk-age=43800m0s

CRON:
`#!/bin/bash

PLEXDRIVETEMP=/tmp/plexdrive/GoogleAJ/chunks
MINDISKSPACE=50000000
CURDISKSPACE=$(df -k $PLEXDRIVETEMP | tail -1 | awk '{print $4}')

echo "MINDISKSPACE=$MINDISKSPACE"
echo "CURDISKSPACE=$CURDISKSPACE"

while [[ $CURDISKSPACE -le $MINDISKSPACE ]]
do
	IFS= read -r -d $'\0' line < <(find $PLEXDRIVETEMP -mindepth 1 -maxdepth 1 -type d -printf '%T@ %p\0' 2>/dev/null | sort -z -n)
	CHUNKDIR="${line#* }"
	echo "Delete: $CHUNKDIR"
	rm -rf $CHUNKDIR
	CURDISKSPACE=$(df -k $PLEXDRIVETEMP | tail -1 | awk '{print $4}')
	echo "CURDISKSPACE=$CURDISKSPACE"
done
`

**Comment by xyber411** [comment]
Some have modified a script ajkis wrote.  I added a bit where it will only remove files older than a portion of 1 day.  Here's my contribution:

#!/bin/bash

MTIME=.16666 #any file with a modification time greater than this portion of 1 day will be removed.  .166 is approximately 4 hours.
PLEXDRIVETEMP=/tmp/plexdrive/GoogleDrive1/chunks
MINDISKSPACE=5000000 #5GB
CURDISKSPACE=$(df -k $PLEXDRIVETEMP | tail -1 | awk '{print $4}')

echo "MINDISKSPACE=$MINDISKSPACE"
echo "CURDISKSPACE=$CURDISKSPACE"

while [[ $CURDISKSPACE -le $MINDISKSPACE ]]
do
IFS= read -r -d $'\0' line < <(find $PLEXDRIVETEMP -mindepth 1 -maxdepth 1 -type d -printf '%T@ %p\0' 2>/dev/null | sort -z -n)
CHUNKDIR="${line#* }"
echo "Delete: $CHUNKDIR"
find $PLEXDRIVETEMP -type f -mtime $MTIME -delete
find $PLEXDRIVETEMP -type d -mtime $MTIME -empty -delete
CURDISKSPACE=$(df -k $PLEXDRIVETEMP | tail -1 | awk '{print $4}')
echo "CURDISKSPACE=$CURDISKSPACE"
done

**Comment by Dopefish123** [comment]
I removed the previous post since i wanted to polish the script a bit before posting. #1 the scripts need some controls, for example a break for infinate while loop if unable to delete folders. #2 your added find delete should be outside the while loop

**Comment by Dopefish123** [comment]
Here is the script i'm using:

#!/bin/bash

if pidof -o %PPID -x "$0"; then
   echo "Already running, exit"
   exit 1
fi

PLEXDRIVETEMP=/tmp/plexdrive/GoogleAJ/chunks
MINDISKSPACE=50000000
CURDISKSPACE=$(df -k $PLEXDRIVETEMP | tail -1 | awk '{print $4}')
FORCEMINAGE=120
FORCEMAXAGE=1440


HRDISKSPACE=$(echo "$CURDISKSPACE" | awk '{ sum=$1 ; hum[1024**2]="Gb";hum[1024]="Mb";hum[0]="Kb"; for (x=1024**3; x>=1024; x/=1024){ if (sum>=x) { printf "%.2f %s\n",sum/x,hum[x];break } }}')
echo "Starting with $HRDISKSPACE free diskspace"
HRCHUNKSPACE=$(du -s $PLEXDRIVETEMP | awk '{ sum=$1 ; hum[1024**2]="Gb";hum[1024]="Mb";hum[0]="Kb"; for (x=1024**3; x>=1024; x/=1024){ if (sum>=x) { printf "%.2f %s\n",sum/x,hum[x];break } }}')
echo "Starting with $HRCHUNKSPACE used chunkspace"

find $PLEXDRIVETEMP -mmin +$FORCEMAXAGE -amin +$FORCEMAXAGE -cmin +$FORCEMAXAGE -type f -delete

while [[ $CURDISKSPACE -le $MINDISKSPACE ]]
do
        IFS= read -r -d $'\0' line < <(find $PLEXDRIVETEMP -mmin +$FORCEMINAGE -amin +$FORCEMINAGE -cmin +$FORCEMINAGE -type f -printf '%T@ %p\0' 2>/dev/null | sort -z -n)
        CHUNK="${line#* }"
        if [[ -z "$CHUNK" ]]; then
                break
        fi
        rm $CHUNK
        CURDISKSPACE=$(df -k $PLEXDRIVETEMP | tail -1 | awk '{print $4}')
done

find $PLEXDRIVETEMP -mindepth 1 -empty -delete

CURDISKSPACE=$(df -k $PLEXDRIVETEMP | tail -1 | awk '{print $4}')
HRDISKSPACE=$(echo "$CURDISKSPACE" | awk '{ sum=$1 ; hum[1024**2]="Gb";hum[1024]="Mb";hum[0]="Kb"; for (x=1024**3; x>=1024; x/=1024){ if (sum>=x) { printf "%.2f %s\n",sum/x,hum[x];break } }}')
echo "Ended with $HRDISKSPACE free diskspace"
HRCHUNKSPACE=$(du -s $PLEXDRIVETEMP | awk '{ sum=$1 ; hum[1024**2]="Gb";hum[1024]="Mb";hum[0]="Kb"; for (x=1024**3; x>=1024; x/=1024){ if (sum>=x) { printf "%.2f %s\n",sum/x,hum[x];break } }}')
echo "Ended with $HRCHUNKSPACE used chunkspace"

**Comment by dweidenfeld** [comment]
There are some problems in 3.0.0. They will be tested and fixed in the next release.
