### ISSUE TITLE
Change accounts?

### ISSUE THREAD

**Issue by joemarshalljm** [dweidenfeld/plexdrive#128]
I lost access to my Drive account - how do I change my settings to mount a different account?

**Comment by ethanfel** [comment]
yep i would like to know too :)

**Comment by animosity22** [comment]
You can delete your cache and token.json and update the config.json with the new client id and secret id.

```
felix@plex:~/.plexdrive$ ls -al
total 48132
drwxrwxr-x  2 felix felix     4096 May 23 07:24 .
drwxr-xr-x 25 felix felix     4096 May 22 14:13 ..
-rw-r--r--  1 felix felix 49266688 May 23 07:24 cache
-rw-rw-r--  1 felix felix      139 May  3 10:56 config.json
-rw-r--r--  1 felix felix      302 May  9 12:58 token.json
```

**Comment by joemarshalljm** [comment]
Thanks, deleted cache & token.json, and ran

`./plexdrive /path/to/my/mount`

and everything seems to be rebuilding
