### ISSUE TITLE
Failed to chdir to mountpoint

### ISSUE THREAD

**Issue by mechanimal82** [dweidenfeld/plexdrive#129]
Hoping someone can help me. I'm running the latest Plexdrive (3.0) on a clean install and a clean booted machine. plexdrive is owned by root:root and chmod 755 and my user (dan) has full owner permissions to the folders, and this has worked fine for previous versions.  Plexdrive is in '/usr/bin/plexdrive' and I'm then running the command: 

`plexdrive mount /home/media/plexdrive`

I add my credentials OK and after providing the authorisation code from Google Drive I get an error:

`mount helper error: fusermount: failed to chdir to mountpoint: permission denied`

I then notice that in the directory I was in when running the command I have a new folder: /mount

However, this folder is not accessible and if attempting to run plexdrive again I get a fusermount error that /home/dan/mount is inaccessible. 

Any thoughts? Why am I getting a random mount folder appear? I've been running plexdrive for a few weeks now... it seems this only happened when I removed plexdrive from my system completely in order to be able to change the Google account it should be caching.

Thanks

**Comment by animosity22** [comment]
Having a tough time following as you seem to conflict.

Your command you say you mount to "/home/media/plexdrive" but you reference "/home/dan/mount"

Where are you trying to mount to?

**Comment by mechanimal82** [comment]
Hi.

That's it. Setting the mount to /home/media/plexdrive but for some reason a new mount folder is created in whichever root folder I'm in and then it seems like plexdrive is attempting to mount to that. I wonder if it's part of the program to create a temporary mount whilst authenticating and then chdir once complete... And for whatever reason this is failing

**Comment by animosity22** [comment]
So if you do:

```
sudo fusermount -u /home/media/plexdrive
ls -al /home/media
```
What is the output?

Also, if you do a:
```
ps -ef | grep plexdrive
```

What's the output? Not running twice?

**Comment by mechanimal82** [comment]
here's the output of those commands... BTW - thanks for helping... this is really bugging me and I'm still fairly new to Linux:

```
dan@Ubuntu-1704-zesty-64-minimal:~/scripts$ sudo fusermount -u /home/media/plexdrive
fusermount: failed to unmount /home/media/plexdrive: Invalid argument
dan@Ubuntu-1704-zesty-64-minimal:~/scripts$ ls -al /home/media
total 20
drwxr-xr-x 6 dan  dan  4096 May 23 16:35 .
drwxr-xr-x 6 root root 4096 May  9 19:52 ..
drwxr-xr-x 1 root root    0 May 23 18:54 cloud
drwxr-xr-x 5 dan  dan  4096 May 21 00:58 local
drwxr-xr-x 1 dan  dan  4096 May 21 00:58 plex
drwxrwxr-x 2 dan  dan  4096 May 18 11:47 plexdrive
dan@Ubuntu-1704-zesty-64-minimal:~/scripts$ ps -ef | grep plexdrive
dan      11785 10240  0 19:05 pts/0    00:00:00 grep --color=auto plexdrive
```

**Comment by animosity22** [comment]
Ha. Ok. I missed something as I glanced over it. 

Just run:

```
plexdrive /home/media/plexdrive
```
 to validate, the mount isn't needed.

I usually run with:
```
plexdrive -o allow_other /home/media/plexdrive
```

Allow other lets plex or something else read your files as Plex usually runs as the user "plex".

If you get an error launching that about fuse.conf, as your root user, just uncomment the allow_other line in /etc/fuse.conf:
```

# /etc/fuse.conf - Configuration file for Filesystem in Userspace (FUSE)

# Set the maximum number of FUSE mounts allowed to non-root users.
# The default is 1000.
#mount_max = 1000

# Allow non-root users to specify the allow_other or allow_root mount options.
user_allow_other
```

**Comment by mechanimal82** [comment]
What an idiot. I was confusing plexdrive with rclone and adding a mount argument. Works now if I write it in the command line... However now it won't start from a systemd startup. Grrr
