### ISSUE TITLE
 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by rafuz** [dweidenfeld/plexdrive#131]
I have this issues in the last days

Platform: Ubuntu 16.10

Plexdrive start command:
/usr/bin/plexdrive -o allow_other --clear-chunk-age=24h --clear-chunk-max-size=200G -t /xxx/xxx/.plexdrivecache /xxx/xxx/gdrive

Notes:
I user a fairly large chunk-max-size because I have a lot of people whatching the same media every day.
No problems during playback or library update.

Syslog:
`May 21 09:19:03 cloudserver systemd[1]: Started Plexdrive.
May 21 09:19:03 cloudserver plexdrive[12477]: 2017/05/21 09:19:03 mount helper error: fusermount: failed to open /etc/mtab: Permission denied
May 23 04:52:03 cloudserver plexdrive[12477]: panic: runtime error: invalid memory address or nil pointer dereference
May 23 04:52:03 cloudserver plexdrive[12477]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7c0b08]
May 23 04:52:03 cloudserver plexdrive[12477]: goroutine 121436703 [running]:
May 23 04:52:03 cloudserver plexdrive[12477]: main.deleteOldestFile.func1(0xc420a97980, 0x3e, 0x0, 0x0, 0xd646e0, 0xc420bee180, 0x0, 0x0)
May 23 04:52:03 cloudserver plexdrive[12477]: #011/go/src/github.com/dweidenfeld/plexdrive/buffer.go:271 +0x38
May 23 04:52:03 cloudserver plexdrive[12477]: path/filepath.walk(0xc420189d70, 0x21, 0xd6b2a0, 0xc423bd4ea0, 0xc4204cad00, 0x0, 0x20)
May 23 04:52:03 cloudserver plexdrive[12477]: #011/usr/local/go/src/path/filepath/path.go:372 +0x2fe
May 23 04:52:03 cloudserver plexdrive[12477]: path/filepath.Walk(0xc420189d70, 0x21, 0xc4204cad00, 0x8ed800, 0x0)
May 23 04:52:03 cloudserver plexdrive[12477]: #011/usr/local/go/src/path/filepath/path.go:398 +0x14c
May 23 04:52:03 cloudserver plexdrive[12477]: main.deleteOldestFile(0xc420189d70, 0x21, 0x31ff7d85c0, 0x0)
May 23 04:52:03 cloudserver plexdrive[12477]: #011/go/src/github.com/dweidenfeld/plexdrive/buffer.go:279 +0x119
May 23 04:52:03 cloudserver plexdrive[12477]: main.cleanChunkDir(0xc420189d70, 0x21, 0x20, 0xc4241006e0)
May 23 04:52:03 cloudserver plexdrive[12477]: #011/go/src/github.com/dweidenfeld/plexdrive/buffer.go:257 +0x98
May 23 04:52:03 cloudserver plexdrive[12477]: main.(*Buffer).ReadBytes.func2()
May 23 04:52:03 cloudserver plexdrive[12477]: #011/go/src/github.com/dweidenfeld/plexdrive/buffer.go:170 +0x3d
May 23 04:52:03 cloudserver plexdrive[12477]: created by main.(*Buffer).ReadBytes
May 23 04:52:03 cloudserver plexdrive[12477]: #011/go/src/github.com/dweidenfeld/plexdrive/buffer.go:174 +0x1393
May 23 04:52:03 cloudserver systemd[1]: plexdrive.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 23 04:52:04 cloudserver systemd[1]: plexdrive.service: Unit entered failed state.
May 23 04:52:04 cloudserver systemd[1]: plexdrive.service: Failed with result 'exit-code'.`

The service ran for about 2 days without issues.
Then started with this error. Is has already happened 4 times in the span of 24h.
It seems to happen only during the media maintainance of Plex.

**Comment by animosity22** [comment]
When you say 'media maintenace', what is checked and what is running?

Just like other folks, I think you are hitting an issue when you are cleaning up something needed and the max size is causing a problem. You can check what you need to analyze via https://github.com/ajkis/scripts and show what needs to be analyzed.

You can also analyze via his script which does it a bit cleaner and in a more one by one fashion.

```
felix@plex:~$ plex-library-stats
24.05.2017 06:32:24 PLEX LIBRARY STATS
Media items in Libraries
Library =   TV
  Items = 13733

Library =  Movies
  Items = 1431

Library = Exercise
  Items = 270

Library = MMA
  Items = 42

Library = Misc
  Items = 7

17161 files in library
0 files missing analyzation info
2 media_parts marked as deleted
2 metadata_items marked as deleted
0 directories marked as deleted
15482 files missing deep analyzation info.
```

**Comment by rafuz** [comment]
These are my stats:

10120 files in library
1290 files missing analyzation info
4 media_parts marked as deleted
9 metadata_items marked as deleted
28 directories marked as deleted
29 files missing deep analyzation info.

I will try to run analysis with these scripts, they seem much less aggressive than plex media analysis.
I will write back if I get errors

**Comment by animosity22** [comment]
That's not bad. Just a little to analyze. I usually just cron the analyze to ensure everything is good. 

I run a pretty default setup to mount:
```
/home/felix/scripts/plexdrive --chunk-size=25M -o allow_other -v 2 /GD
```

I've had 7 people streaming and let everything run and I haven't seen a crash yet. Every crash seems to come back to max chunk size as the config option so it seems to be related to something looking for a piece of data that was just removed due to activity. I keep my chunks on a 250GB SSD root volume and never go above 30-40GB at most with 7 streams.

Once you have everything analyzed, you'll see that usage drop down. I know when I first analyzed, I jumped up to 300-400GB of use, but I'm running 1Gb Fios as well so I get a lot downloaded.

**Comment by rafuz** [comment]
I will try to change the options used in the mount.
Anyway if I try to run plex-analyze-cli.py I get this result:

/plex$ ./plex-analyze-cli.py
To analyze: 0

**Comment by animosity22** [comment]
Oh, you are probably good, I changed mine to ignore samples and some other things that can't be analyzed:

```
query="select count(*) From media_items Inner Join metadata_items On media_items.metadata_item_id = metadata_items.id Where media_items.bitrate Is Null And Not metadata_items.metadata_type = 12"
```
The issue before with analyze was this if uploaded to ACD, the mod time wasn't supported and it was change it to the upload time. Plex would see that as a new file and analyze it. With GD, it support mod times, so if you have it analyzed locally and than upload, it works fine and won't re-analyze the file.

My scheduled tasks are:
![image](https://cloud.githubusercontent.com/assets/5088712/26404391/bc6e009c-405f-11e7-91c0-3ae7dcbfc1d8.png)

**Comment by rafuz** [comment]
So using plexdrive on Google I can activate "Library auto update" based on mod times of directories?

**Comment by animosity22** [comment]
I don't see why not.

I use Sonarr/Radarr to drive Library updates as it should be action based rather than a time gated event in my mind.

**Comment by dweidenfeld** [comment]
Duplicate.
