### ISSUE TITLE
Mount Drops

### ISSUE THREAD

**Issue by sbcrumb** [dweidenfeld/plexdrive#132]
For whatever reason my mount will randomly drop. If I put a remount script in place that is all well and good but then my rclone crypt mount is also messed up and will need a remount. Here are the logs before it happens. I am on 2.0, but have seen this on 3.0 2.1.1 and 2.1 as well Running Ubuntu 16.04LTS
Command to mount is 
/usr/sbin/plexdrive211 -c /dev/shm/.plexdrive -v 3 -o allow_other --uid=1000 --gid=1000 /home/plex/mounts/plxdrive

Ok lets try this

https://pastebin.com/Aear6mgv

**Comment by Em31Et** [comment]
Can you post a readable log (line by line) and full command

**Comment by sbcrumb** [comment]
I put the logs in pastebin hopefully it formats it better.

**Comment by dweidenfeld** [comment]
Should be fixed in next release, otherwise please open a new issue, with an embedded readable log. Thx
