### ISSUE TITLE
Ignoring directory/node from cache

### ISSUE THREAD

**Issue by ewan2395** [dweidenfeld/plexdrive#133]
At this present time plexdrive caches everything which is located in the root directory. Is there any way to prevent the caching of a selected directory/node?

I've compiled plexdrive with this #103, however it still continues to cache everything rather than just the node specified in the arguments.

**Comment by dweidenfeld** [comment]
No. An exclusion is not possible right now.

**Comment by JorgenPhi** [comment]
Why was this issue closed?
