### ISSUE TITLE
Issue on some clients resuming playback from midway through

### ISSUE THREAD

**Issue by geekcroft** [dweidenfeld/plexdrive#135]
Hi all,

Some clients (such as Plex Web) work fine when I skip to the middle of a plexdrive hosted file.

However some other clients (Such as my OperaTV SmartTV App or w/ever its called) cause an error;
[PLEXDRIVE] [DATE/TIME] WARNING Wrong status code &{416 Requested Range Not Satisfiable 416....

(Full error @ https://i.imgur.com/7OSmoI1.png - sadly couldn't get a text copy of this just yet) 

Any ideas?

**Comment by geekcroft** [comment]
Update: Looks like it's all clients. 

Seems to be trying to retrieve all the chunks of the file up until the part I am resuming at - is there a way to fix this?

**Comment by haljordan2814** [comment]
Those of us in the Slack room have not seen this behavior. You need to give more data.  What version of plexdrive are you running? If 3.0.0 I suggest that you install 2.0 or 2.1.1 instead. Are you using default settings? Are you in a fuse mount? What is the base OS ? What speedtest results do you see? What is your geographical location ? What gdrive are you using (.eu .com ?)

**Comment by geekcroft** [comment]
- Plexdrive version 3.0.0. Any reason why you suggest 2.0 or 2.1.1 instead?
- Mount options are;
plexdrive -v 2 -o allow_other /home/Plex/ACD/.acd-sorted/
- Ubuntu 15.10 
- Speedtest;
Download: 609.83 Mbit/s
Upload: 154.49 Mbit/s
- Server is in GER (Heztner) 
- Not sure what GDrive I am using - signed up from the UK for a Business GSuites account so I presume EU?

**Comment by Em31Et** [comment]
All media format or specific media format?
Some media may need the whole file to fast forward.

**Comment by geekcroft** [comment]
Tested on the following file;

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '0c0b99f27ec74438be4b24a1640425e4.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.72.101
  Duration: 02:10:48.27, start: 0.000000, bitrate: 1584 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 704x400 [SAR 1:1 DAR 44:25], 1384 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      handler_name    : SoundHandler

I can test other files if need be? 

FWIW the same file worked fine on RClone/ACD.

**Comment by savahu** [comment]
@geekcroft Do you perhaps have an nginx reverse proxy in front of your Plex instance at Hetzner?

Do you also experience failures of playback after pausing and resuming?

**Comment by geekcroft** [comment]
@savahu No, going direct. Have never had any peering issues.
No issues playing/pausing/resuming as long as I dont stop playing and try to resume later.

**Comment by ikvirsingh** [comment]
I'm experiencing the same issue :(

**Comment by geekcroft** [comment]
I suspect it's trying to stream the file from the start up to where you are
resuming. If this takes too long then Plex Transoder times out and gives
you the "video didn't start playing in time"

If I watch on Nethogs it's pulling down at 20-50mb/s whilst trying to
resume.

**Comment by ikvirsingh** [comment]
I think so too. If I restart my machine and have the chunk folder cleared, it works then. I haven't tried on version 2.0 or 2.1.1 though. I'm also on 3.0.

**Comment by geekcroft** [comment]
@dweidenfeld I can provide sample media for testing to see if you can reproduce if you want?

**Comment by zenjabba** [comment]
I think I might have more information on this problem... If you try to resume a movie after the chunks have been deleted, plexdrive seems to have a problem restarting the stream.
