### ISSUE TITLE
[Request] Obtain multiple video formats from Google

### ISSUE THREAD

**Issue by madknave** [dweidenfeld/plexdrive#137]
Do you think it would be possible to add this feature?

https://github.com/thejinx0r/node-gdrive-fuse/issues/59

This feature could eliminate the transcoding that Plex does, by using Google's already processed videos, and at the same time reduce some bandwidth.

**Comment by madknave** [comment]
You are right about the encrypted files, which I use for personal and confidential information; for videos I just prefer the convenience of having it non-encrypted (for Plexcloud mostly).

The different encodes would be just present in the folder, [Plex tries selecting](https://support.plex.tv/hc/en-us/articles/200250387-Streaming-Media-Direct-Play-and-Direct-Stream) the best file out of it for playback, that's how I understand it anyway.

**Comment by dweidenfeld** [comment]
Sorry, but most users encrypt there complete video library. I don't think this is a useful feature and I do not have the time to implement it myself.
