### ISSUE TITLE
insufficientFilePermissions when attempting to delete via plexdrive

### ISSUE THREAD

**Issue by zenjabba** [dweidenfeld/plexdrive#138]
When I attempt to delete it returns this error: [PLEXDRIVE] [2017-05-25 21:07] DEBUG  : googleapi: Error 403: The user does not have sufficient permissions for this file., insufficientFilePermissions

Confirmed you have to 'own' the file in Google Drive and not just have Google Drive 'edit' privilege to affect a delete of file through PlexDrive. Can we update the delete function to work as expected.

**Comment by dweidenfeld** [comment]
What is your expectation? If you do not have the permission to delete the file, you cannot delete it.

**Comment by louis-lau** [comment]
Plexdrive is read-only, why would you be able to delete files?

Try rclone rm gdrive:/file.txt

**Comment by zenjabba** [comment]
Plexdrive is read only but it does have delete capability.  It was added [here](https://github.com/dweidenfeld/plexdrive/commit/8eead52c70258687fa95acb2fec00563c2bd2078)

**Comment by zenjabba** [comment]
Basically you do have permission to delete the file, because you have been given edit permission on the share. The issue seems to be if it's a "shared folder" you cannot delete it, but if you directly own it, it deleted fine. The expectation is if it's a shared folder it will also delete the file.

**Comment by louis-lau** [comment]
Heh, the more you know. Thanks.

**Comment by dweidenfeld** [comment]
Fixed in next release.
