### ISSUE TITLE
WARNING: Could not write chunk temp file /tmp/chunks/0B6awGxxxx/xxxxxx

### ISSUE THREAD

**Issue by micneon** [dweidenfeld/plexdrive#139]
Hi, 

I had a loop of that with Lib Scan in message Log:

WARNING: Could not write chunk temp file /tmp/chunks/0B6awGui23d9gxxxxxxxx/2018508800

Frist that i have manual mkdir WARNING: /tmp/chunks/0B6awGui23d9gxxxxxxxx the Scan realy continue.
After some Time the next Error: 
/tmp/chunks/0B6awGui23d9gSHEyTmxxxxxxx/1242562560

First i create the dir the Scan will work again.

Space 
df -h tells:
tmp     21G   13G  6.8G  66% /tmp

df -i tells:
tmp   1376256    6708 1369548    1% /tmp

System is Centos7

**Comment by seuffert** [comment]
have a look at https://github.com/dweidenfeld/plexdrive/issues/122
