### ISSUE TITLE
How to delete files?

### ISSUE THREAD

**Issue by memnos** [dweidenfeld/plexdrive#14]
I've mounted my gdrive with plexdrive.
I don't know if it is a problem with plexdrive or not but i cannot delete a file.
I have this error:
rm: cannot remove 'MOVIE_NAME.mkv': Input/output error

Any suggestion?
Tnx

**Comment by dweidenfeld** [comment]
The file system is currently read-only. You cannot delete or insert new files. See #10 for write support.
