### ISSUE TITLE
find doesnt traverse directory structure with plexdrive.

### ISSUE THREAD

**Issue by RXWatcher1** [dweidenfeld/plexdrive#140]
neither`find . -name '*.mkv'` nor `find . -iname '*.mkv' `will traverse the plexdrive directory structure.
It  will find files on the top layer but wont go any deeper than that.

I am running plexdrive 2.1.1

They will traverse the rclone directory structure.

I would like to have some shell script that check each file so I have find go through and find all of the mkvs and check them for specific languages and subtitles.

Thanks!

**Comment by azgul** [comment]
> I would like to have some shell script that check each file so I have find go through and find all of the mkvs and check them for specific languages and subtitles.

Beware that a partial read counts as a full download towards your 10 TB daily download quota. So if you iterate through _all_ the things you will run out quickly. Might as well use `rclone mount` then :)

**Comment by RXWatcher1** [comment]
I realize that but there will be other use cases where I just want to find a single file that is several layers down via a script. Hopefully its doable because I would prefer not to have both plexdrive mounted(for plex playback) and rclone mounted just to run a script against it to find a file.

**Comment by animosity22** [comment]
Works fine for if you use a fuse mount over it.

I mount via plexdrive and a fusemount for local media to present a single cloud/local mountpoint.

**Comment by RXWatcher1** [comment]
I am using a fuse union mount. It will traverse and find my local content but not the content on the plexdrive mount. I have also pointed my search directly at the plexdrive mount with the same results. It will not traverse the dir structure. It will find files in the first level.

**Comment by animosity22** [comment]
Must be the rclone mount in my flow that fixes it. Clearly, just encrypt your stuff :)

**Comment by RXWatcher1** [comment]
This is where we have a difference of opinion. I purposefully choose to not do so. To each his/her own.

**Comment by spuniun** [comment]
I just discovered this somewhat annoying issue and discovered you can force find to traverse the subdirectories with -L so I guess the plexdrive mount makes those directories appear to be symbolic links.

**Comment by dweidenfeld** [comment]
Working in next version.
