### ISSUE TITLE
chunks downloaded twice

### ISSUE THREAD

**Issue by seuffert** [dweidenfeld/plexdrive#141]
- current plexdrive build (from git)
- plexdrive mount with small chunk size (4MB)
- rclone crypt mount on top with bandwidth limiter (5MB/s)
- fast reading (like a local copy)

the debug log and bandwidth consumption tells me that every chunk is being downloaded twice.
rclone stats & actual copy rate show that it is limited to the correct bandwidth as specified to rclone crypt mount. 
The resulting consumed network interface bandwidth is roughly equal to double the rclone bandwidth.

raising the chunk size (8MB) makes this go away almost completely

**Comment by Ninjouz** [comment]
which version ? cuz there was a bug like this on previous version (<2.1.1 IIRC)

**Comment by seuffert** [comment]
@Ninjouz 
as stated in the first post: "current plexdrive build from git"

**Comment by dweidenfeld** [comment]
Builds from git are not supported. Please checkout the release section

**Comment by seuffert** [comment]
seriously? how is one supposed to actively support development if your are not able to report bugs in the "current" code?

**Comment by dweidenfeld** [comment]
Yes. You can provide code to fix the issue. 
The master branch is always work in progress, so I am already aware of most of the issues in master, but you can always support by writing code to fix issues in master.
