### ISSUE TITLE
Backup the cache

### ISSUE THREAD

**Issue by EldonMcGuinness** [dweidenfeld/plexdrive#143]
Is there a way to backup the cache file as it seems to take **QUITE** a while to build up. Can one simply copy the cache file and just restore it if there is an issue? I tried recently copying one from another machine and that did not work. :/

If the plain old copy will not work, can a function be built into the app to make a backup of the DB when it completes a good sync. I've been having issues where the sync never seems to complete after a while and I have to delete the cache and let it rebuild.

**Comment by animosity22** [comment]
You can just copy it. It's a sqlite DB. I do that all the time with Plex as well as this to keep a safe copy.

**Comment by EldonMcGuinness** [comment]
@animosity22 That is what I thought, but why would I not be able to transfer the contents of the plexdrive folder from one device to another and it continue to work?

**Comment by dweidenfeld** [comment]
It is safe to copy the cache file if there is no write action running. If a write is active you should see a cache-journal file next to the cache file.
