### ISSUE TITLE
3.1.0 beta, files missing

### ISSUE THREAD

**Issue by l3uddz** [dweidenfeld/plexdrive#145]
Hey,

Noticing some files going missing from the plexdrive mount, even though they are indeed on google drive:

http://i.imgur.com/RaTOvN9.png

Seems the entire Season 6 folder is missing, amongst other files from other shows. Anything you need me to try?

**Comment by dweidenfeld** [comment]
If you delete the cache and rebuild it is the folder still missing?
Or is an other folder missing then?

**Comment by l3uddz** [comment]
Deleted the cache and rebuilt, and the folder does indeed now appear. However like you suspected, other files are now missing.

**Comment by zenjabba** [comment]
seeing the same problem

**Comment by scoopydude2002** [comment]
Notice this too on 3.0. Files seem to appear again after some time.

**Comment by dweidenfeld** [comment]
Everyone who's not aware: If you build the current master you will have the latest 3.1.0-beta ... please check if you still have missing files/folders. 
The latest beta should fix this issue.

**Comment by dweidenfeld** [comment]
Should be fixed in next release. Got feedback from @l3uddz and @zenjabba

**Comment by ajkis** [comment]
Just fyi if, deleted files are not being removed from plexdrive ( latest master version )

**Comment by ajkis** [comment]
@dweidenfeld This is definitely one of the critical issues, please condsider rolling back to API 2 since it started to happen on API 3 upgrade.

**Comment by dweidenfeld** [comment]
Fixed in next version.

**Comment by jaum20** [comment]
I'm still facing this problem in 5.1.0
