### ISSUE TITLE
Only use Subdir for Plexdrive

### ISSUE THREAD

**Issue by micneon** [dweidenfeld/plexdrive#146]
Is it possible to use only subdirectories of the GDrive with Plexdrive?

I have for example a folder for media files and others for other files and Plexdrive always goes the whole GDrive through but it would only need media. In the other directories are more than 2000000 files ....

**Comment by zenjabba** [comment]
Plexdrive uses the gdrive transaction logs to build your file system, so it has to go through from the first transaction all the way to the current one meaning it needs to process each and every file.

This is something that currently isn't going modified as it's the way to get the efficiency up to the required amount and keep your google drive and usage level down to not being banned.

**Comment by FlukiestEmperor** [comment]
Going through the entire transaction log and caching million of files seems like the opposite of efficiency and preventing bans. That could potentially take weeks to finish. 

If I just want a folder mounted that contains a few thousand files, caching just that folder seems like a much better solution than going through potentially years of transactions and millions of files.

**Comment by zenjabba** [comment]
But google doesn't present us with that view... The supported way is to download the transaction logs and build the filesystem from that. It's not caching "millions of files", it's building an index for those files so it can build them on the fly when you request a file system view.

When you have google present to us the transaction log of just those folders, of course that can be implemented, but nobody has done that yet, so it cannot be done.

**Comment by FlukiestEmperor** [comment]
What about recursively going through a specified folder to build an index?
