### ISSUE TITLE
Can't set root-node-id

### ISSUE THREAD

**Issue by realcanadrian** [dweidenfeld/plexdrive#148]
I'm trying to use the following command to mount my GDrive:

`plexdrive --uid=1000 --gid=1000 -o allow_other -v 2 --root-node-id=MediaFolder /home/username/media/gd-encrypted`

And I'm getting the following error:

`unknown flag: --root-node-id`

Using plexdrive 3.0.0 on Ubuntu 16.10

**Comment by ewan2395** [comment]
plexdrive 3.0.0 doesn't have this feature. 

You'll need to compile the master branch yourself until the next release.

**Comment by zenjabba** [comment]
3.1 is not released yet (which has this function). Feel free to build the current master if you need it.
