### ISSUE TITLE
WARNING: Could not delete oldest chunk

### ISSUE THREAD

**Issue by mitchelp** [dweidenfeld/plexdrive#149]
Got this error from time to time:
`[USR/SBIN/PLEXDRIVE] [2017-06-01 14:59] WARNING: Could not delete oldest chunk`

mount setting:
`/usr/sbin/plexdrive /myfolder -m localhost --clear-chunk-max-size=100G -o allow_other --refresh-interval=30s --temp=/root/.plexdrive/tmp -v 2`

It's definitely not permissions as I run plexdrive as root.

**Comment by dweidenfeld** [comment]
If you're able to reproduce the issue please try to with `-v3` enabled.

**Comment by mitchelp** [comment]
Does not do any harm.. Seems to work just fine. Closing..
