### ISSUE TITLE
Getting api_objects.object.id error

### ISSUE THREAD

**Issue by zenjabba** [dweidenfeld/plexdrive#15]
(UNIQUE constraint failed: api_objects.object_id)
[2017-05-06 18:52:42]

This is often whilst something is playing.

**Comment by dweidenfeld** [comment]
Could you please unmount, delete the ~/.plexdrive/cache file, mount and let the cache build up first. after the cache has been built successfully, the message should not show again.

**Comment by animosity22** [comment]
I had that first time and just remounted and it was fine.

**Comment by zenjabba** [comment]
Will try remounting it first then rebuilding cache

**Comment by zenjabba** [comment]
Remounting didn't work, so I'm rebuilding the cache from scratch. I thought it allowed direct access to the current files in Gdrive, but it seems it needs to finish building up the cache before the files become active.

**Comment by dweidenfeld** [comment]
Yes. My first thought was you build up the cache while you're accessing the files. But this doesn't seem like a valuable measure to me. 

In the next release, I will refactor the cache building process, that you will only be able to access files that are already in the cache. This should increase the performance and avoid errors like the one you got.

**Comment by zenjabba** [comment]
Opening this again, after a full cache refresh, still seeing the errors..

**Comment by dweidenfeld** [comment]
@zenjabba 
Please use the newest release, start with ```-log-level 4``` and post your logs here.

**Comment by zenjabba** [comment]
`[PLEXDRIVE-LINUX-AMD64] [2017-05-08 11:09] DEBUG  : Storing object 0BxYemFFjZ8ptRU1HRHZOOXNCbjg in cache
[PLEXDRIVE-LINUX-AMD64] [2017-05-08 11:09] DEBUG  : Deleting object 0BxYemFFjZ8ptT2FxOEtTeXhsV3c

(UNIQUE constraint failed: api_objects.object_id)
[2017-05-08 11:09:25]
[PLEXDRIVE-LINUX-AMD64] [2017-05-08 11:09] TRACE  : Change &{false 0xc420c34e00 0BxYemFFjZ8pteUpGa3I1VWJvS28 23802055 drive#change 2017-05-08T02:09:52.672Z https://www.googleapis.com/drive/v2/changes/23802055 <nil>  file {0 map[]} [] []}
[PLEXDRIVE-LINUX-AMD64] [2017-05-08 11:09] DEBUG  : Storing object 0BxYemFFjZ8ptT2FxOEtTeXhsV3c in cache

(UNIQUE constraint failed: api_objects.object_id)
[2017-05-08 11:09:25]
[PLEXDRIVE-LINUX-AMD64] [2017-05-08 11:09] DEBUG  : Deleting object 0BxYemFFjZ8pteUpGa3I1VWJvS28
[PLEXDRIVE-LINUX-AMD64] [2017-05-08 11:09] DEBUG  : Storing object 0BxYemFFjZ8pteUpGa3I1VWJvS28 in cache
[PLEXDRIVE-LINUX-AMD64] [2017-05-08 11:09] TRACE  : Change &{false 0xc420c35180 0BxYemFFjZ8ptTDVKcjhnN0VwVHM 23802056 drive#change 2017-05-08T02:09:52.672Z https://www.googleapis.com/drive/v2/changes/23802056 <nil>  file {0 map[]} [] []}
[PLEXDRIVE-LINUX-AMD64] [2017-05-08 11:09] DEBUG  : Deleting object 0BxYemFFjZ8ptTDVKcjhnN0VwVHM

(UNIQUE constraint failed: api_objects.object_id)
[2017-05-08 11:09:25]
[PLEXDRIVE-LINUX-AMD64] [2017-05-08 11:09] TRACE  : Change &{false 0xc420c35500 0BxYemFFjZ8ptQnkzNXVZcVZ4V0U 23802057 drive#change 2017-05-08T02:09:52.672Z https://www.googleapis.com/drive/v2/changes/23802057 <nil>  file {0 map[]} [] []}
[PLEXDRIVE-LINUX-AMD64] [2017-05-08 11:09] DEBUG  : Storing object 0BxYemFFjZ8ptTDVKcjhnN0VwVHM in cache
[PLEXDRIVE-LINUX-AMD64] [2017-05-08 11:09] DEBUG  : Deleting object 0BxYemFFjZ8ptQnkzNXVZcVZ4V0U

(UNIQUE constraint failed: api_objects.object_id)
[2017-05-08 11:09:25]
[PLEXDRIVE-LINUX-AMD64] [2017-05-08 11:09] DEBUG  : Storing object 0BxYemFFjZ8ptQnkzNXVZcVZ4V0U in cache
[PLEXDRIVE-LINUX-AMD64] [2017-05-08 11:09] TRACE  : Change &{false 0xc420c35880 0BxYemFFjZ8ptak9EdFZkdjhHc1k 23802058 drive#change 2017-05-08T02:09:52.672Z https://www.googleapis.com/drive/v2/changes/23802058 <nil>  file {0 map[]} [] []}
[PLEXDRIVE-LINUX-AMD64] [2017-05-08 11:09] DEBUG  : Deleting object 0BxYemFFjZ8ptak9EdFZkdjhHc1k
[PLEXDRIVE-LINUX-AMD64] [2017-05-08 11:09] DEBUG  : Storing object 0BxYemFFjZ8ptak9EdFZkdjhHc1k in cache

(UNIQUE constraint failed: api_objects.object_id)
[2017-05-08 11:09:25]
[PLEXDRIVE-LINUX-AMD64] [2017-05-08 11:09] TRACE  : Change &{false 0xc420c35c00 0BxYemFFjZ8ptOWVTSDJSR0xjY1k 23802059 drive#change 2017-05-08T02:09:52.672Z https://www.googleapis.com/drive/v2/changes/23802059 <nil>  file {0 map[]} [] []}
[PLEXDRIVE-LINUX-AMD64] [2017-05-08 11:09] DEBUG  : Deleting object 0BxYemFFjZ8ptOWVTSDJSR0xjY1k

(UNIQUE constraint failed: api_objects.object_id)
[2017-05-08 11:09:25]
[PLEXDRIVE-LINUX-AMD64] [2017-05-08 11:09] TRACE  : Change &{false 0xc420c8e000 0BxYemFFjZ8ptMVVCRVhlM0FkZGs 23802060 drive#change 2017-05-08T02:09:52.672Z https://www.googleapis.com/drive/v2/changes/23802060 <nil>  file {0 map[]} [] []}
[PLEXDRIVE-LINUX-AMD64] [2017-05-08 11:09] DEBUG  : Storing object 0BxYemFFjZ8ptOWVTSDJSR0xjY1k in cache
[PLEXDRIVE-LINUX-AMD64] [2017-05-08 11:09] DEBUG  : Deleting object 0BxYemFFjZ8ptMVVCRVhlM0FkZGs

(UNIQUE constraint failed: api_objects.object_id)
[2017-05-08 11:09:25]
[PLEXDRIVE-LINUX-AMD64] [2017-05-08 11:09] INFO   : Processed 920 items / deleted 19 items / updated 901 items
[PLEXDRIVE-LINUX-AMD64] [2017-05-08 11:09] DEBUG  : Storing object 0BxYemFFjZ8ptMVVCRVhlM0FkZGs in cache
`

**Comment by dweidenfeld** [comment]
I changed the storing/loading process from the cache mechanism. 
Please test the next release, if the release still has those issues, you can reopen the issue.
