### ISSUE TITLE
Music library scan very slow

### ISSUE THREAD

**Issue by mdesdin** [dweidenfeld/plexdrive#150]
Anyone scanning music here? Movies and shows scan works fast, but music is extremely slow. Same plex but using OCAMLFUSE for mounting performs OK.

**Comment by zenjabba** [comment]
What version?

**Comment by mdesdin** [comment]
Sorry, hit the submit button too early!
My environment:
Ubuntu 16.04, Plex Server is 1.7.1 and Plexdrive is latest release 3.0.0

**Comment by zenjabba** [comment]
Please join the Slack channel so we can help you out. 3.0.0 is a buggy release and we have "fresher" test versions

**Comment by mdesdin** [comment]
sure, thanks
