### ISSUE TITLE
Plexdrive stops working / database is locked

### ISSUE THREAD

**Issue by M0V3** [dweidenfeld/plexdrive#156]
When mounting with plexdrive, all files get accessible.
After switching the file to play or starting a second stream, the files get unavailable.
All folders from the mount disappear and can't be accessed anymore.
Sometimes the files reappear after a few moments.

Log (-v 4)
https://pastebin.com/i1mTUq3R

Log (-v 4) when trying to ls the mount
https://pastebin.com/7Xxu5z2y

Log (-v 4) reappearing files
https://pastebin.com/E9BKpg3j

**Comment by M0V3** [comment]
Deleted .plexdrive, let it redo the cache and now everything is working.

**Comment by M0V3** [comment]
Aaand it stopped working again.

**Comment by animosity22** [comment]
What version are you running? What's your mount command? I've had 3-4 streams all going at the same time.

**Comment by M0V3** [comment]
I had it running for at least a week, the problems have just started.
I'm running v3.0.0, my mount command is
/usr/local/bin/plexdrive -o allow_other -o allow_other -v 4 --refresh-interval=1m /gdrive

**Comment by M0V3** [comment]
Okay, it seems like this is the current situation:

plexdrive is mounted in a KVM (proxmox) and when the I/O usage goes up, the files disappear.
When downloading (with pyLoad) with a speed higher than like 8MB/s it happens, when starting to extract an archive it happens.

**Comment by animosity22** [comment]
I think your use case is very different from mine. I just use plexdrive to stream movies via plex only.

Any local downloads get staged to local disk for extract/etc and I upload stuff older than 30 days to my GD via rclone move.

**Comment by M0V3** [comment]
I should clarify this.
I'm **NOT accessing the plexdrive** mount with anything else than Plex.
When the I/O usage of the **local disk** goes up, the files disappear.

**Comment by animosity22** [comment]
The way plexdrive works is that it downloads via chunks to a temporary file system for playing. Are you seeing disks busy on the temp area that it's trying to download to? You can use iotop or something like that to validate.

**Comment by micneon** [comment]
or us that command to find out what is us that dir.
lsof | grep "/gdrive"

maybe an backups system from your proxmox hoster :-P  ? From hostsystem

**Comment by animosity22** [comment]
@micneon - you can just do lsof /gdrive as well as it takes directory names too :)

**Comment by M0V3** [comment]
@micneon I'm hosting the VM and there are no automated backups. At least for that VM.
Thanks for your help guys, gonna look into that when I'm home.

**Comment by dweidenfeld** [comment]
The database is getting improved in the next version. So I think you should wait for the next version.

**Comment by cardinalfan1** [comment]
@M0V3 were you able to figure this out?
