### ISSUE TITLE
Crash when attempting to play a new video on Plex

### ISSUE THREAD

**Issue by aftadros** [dweidenfeld/plexdrive#158]
I keep experiencing a crash occurring after I have played multiple videos on Plex. 

I am running plexdrive v3.0.0 amd64, on Debian 8.

The command I am using to start plexdrive is the following: 
./plexdrive /home/plex/.cloud-sorted --clear-chunk-age=24h --clear-chunk-max-size=100G &

The crash I am seeing is the following:
 panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7c0b08]

goroutine 38621953 [running]:
main.deleteOldestFile.func1(0xc42065ccf0, 0x28, 0x0, 0x0, 0xd646e0, 0xc42065cd50, 0x0, 0x0)
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:271 +0x38
path/filepath.walk(0xc4201d63f4, 0xb, 0xd6b2a0, 0xc4217ec4e0, 0xc4206ea660, 0x0, 0x20)
        /usr/local/go/src/path/filepath/path.go:372 +0x2fe
path/filepath.Walk(0xc4201d63f4, 0xb, 0xc4206ea660, 0x8ed800, 0x0)
        /usr/local/go/src/path/filepath/path.go:398 +0x14c
main.deleteOldestFile(0xc4201d63f4, 0xb, 0x1912c24ad3, 0x0)
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:279 +0x119
main.cleanChunkDir(0xc4201d63f4, 0xb, 0x20, 0xc420f6e1a0)
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:257 +0x98
main.(*Buffer).ReadBytes.func2()
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:170 +0x3d
created by main.(*Buffer).ReadBytes
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:174 +0x1393

**Comment by aftadros** [comment]
I just read the documentation a little better to see that "clear-chunk-max-size" overrides "clear-chunk-age" so my command can be improved. However, I don't think that invalidates this issue and the cause of the crash should still be addressed.

**Comment by animosity22** [comment]
Did you try by running without both options set and see if you have the problem still?

**Comment by aftadros** [comment]
Yes, I have been doing that and I have not seen a crash so far, but I will let you know if I do. Thanks for the suggestion.

**Comment by dweidenfeld** [comment]
Already fixed in the next release. Will be published soon.
