### ISSUE TITLE
[ Feature Request ] DB change from sqlite3 to boltdb (native golang full api)

### ISSUE THREAD

**Issue by ajkis** [dweidenfeld/plexdrive#161]
Due poor sqlite performance I strongly suggest switching plexdrive  to native golang BoltDB.
https://github.com/boltdb/bolt

Since cache db is quite small I would suggest that always kept in memory and dumped on disk once per minute so when plexdrive is unmount & mount it loads latest local/hdd copy back into memory. 
( on unmount the latest should be dump locally as well )

@dweidenfeld if you consider this, dont forget to read: https://github.com/boltdb/bolt#caveats--limitations

p.s. Running plexdrive with full database server such as Postgres or MySQL Mongo etc.. should not be required.

**Comment by ajkis** [comment]
Btw drive is using it as well: https://github.com/odeke-em/drive

**Comment by dweidenfeld** [comment]
The first version was implemented that way. It is slower than SQLite because the queries get much more complicated.

I am currently trying to work with different data stores, but I think MongoDB fits best.
