### ISSUE TITLE
Big jump in API usage since 3.0.0

### ISSUE THREAD

**Issue by TonioRoffo** [dweidenfeld/plexdrive#162]
I have been using 2.x since may 14th, and the Google API dashboard quotums show ~288 queries per day (although I'm uploading 12h out of 24h at full line speed, 2MB per second)

I have switched to version 3 and have uploaded a night to see API queries rise to ~11 thousand.  This in itself is not a worry as daily query limit is a billion.

However, I have a few peaks of >200 (up to 205) API calls per 100 seconds - which is limited at 1000 before ban sets in.

Is this by design or should I worry?

**Comment by dweidenfeld** [comment]
The API calls just have been changed, there are no new API calls.
I think the increase of calls is based on a change of your setup.
