### ISSUE TITLE
[ Feature request ] Rebuild cache on logic change

### ISSUE THREAD

**Issue by ajkis** [dweidenfeld/plexdrive#167]
Please add that if saved cache need to be deleted due new update logic changed that its automatically done by plex drive ( in same query that will modify the current mongodb )

p.s. Or drop the whole DB and recreate it.

**Comment by dweidenfeld** [comment]
This should be done automatically if the version stored in mongodb is different to the programs version.

**Comment by ajkis** [comment]
Also consider clearing chunks ( once you put them in mongodb) if chunk size setting was changed.

**Comment by dweidenfeld** [comment]
Thought about it again, I don't think this is necessary anymore, because we are all fine with boltdb and there won't be any change in the storage. Otherwise it should auto update ;)
