### ISSUE TITLE
Could not get object root from API

### ISSUE THREAD

**Issue by shenzo1** [dweidenfeld/plexdrive#17]
Great project!

I am encountering this issue when I try re-mount after unmounting gdrive. If I delete the cache in .plexdrive, then I go through the authentification process and plexdrive mounts properly. Maybe I am not meant to unmount each time I am done with using plexdrive?

| => ./plexdrive -log-level 3 .mnt
[PLEXDRIVE] [2017-05-07 00:46] DEBUG  : log-level            : DEBUG
[PLEXDRIVE] [2017-05-07 00:46] DEBUG  : config               : /Users/shenzo/.plexdrive
[PLEXDRIVE] [2017-05-07 00:46] DEBUG  : temp                 : /var/folders/9n/kpv_7r9116nccgczvmvmh93w0000gp/T/
[PLEXDRIVE] [2017-05-07 00:46] DEBUG  : chunk-size           : 5242880
[PLEXDRIVE] [2017-05-07 00:46] DEBUG  : refresh-interval     : 5m0s
[PLEXDRIVE] [2017-05-07 00:46] DEBUG  : clear-chunk-interval : 1m0s
[PLEXDRIVE] [2017-05-07 00:46] DEBUG  : fuse-options         : 
[PLEXDRIVE] [2017-05-07 00:46] DEBUG  : Opening cache connection
[PLEXDRIVE] [2017-05-07 00:46] DEBUG  : Migrating cache schema
[PLEXDRIVE] [2017-05-07 00:46] DEBUG  : Authorizing against Google Drive API
[PLEXDRIVE] [2017-05-07 00:46] DEBUG  : Loading token from cache
[PLEXDRIVE] [2017-05-07 00:46] INFO   : Mounting path .mnt
[PLEXDRIVE] [2017-05-07 00:46] DEBUG  : Checking for changes
[PLEXDRIVE] [2017-05-07 00:46] DEBUG  : Getting change id from cache
[PLEXDRIVE] [2017-05-07 00:46] INFO   : First cache build process started...
[PLEXDRIVE] [2017-05-07 00:46] DEBUG  : Getting object root
[PLEXDRIVE] [2017-05-07 00:46] DEBUG  : Could not find object root in cache, loading from API
[PLEXDRIVE] [2017-05-07 00:46] DEBUG  : Get https://www.googleapis.com/drive/v2/changes?alt=json&includeDeleted=true&maxResults=1000: net/http: TLS handshake timeout
[PLEXDRIVE] [2017-05-07 00:46] WARNING: Could not get changes
[PLEXDRIVE] [2017-05-07 00:46] DEBUG  : Storing change id 1 in cache
[PLEXDRIVE] [2017-05-07 00:46] DEBUG  : Get https://www.googleapis.com/drive/v2/files/root?alt=json: net/http: TLS handshake timeout
[PLEXDRIVE] [2017-05-07 00:46] DEBUG  : Could not get object root from API
[PLEXDRIVE] [2017-05-07 00:46] DEBUG  : Could not load object root from API
[PLEXDRIVE] [2017-05-07 00:46] DEBUG  : Could not get root node

**Comment by dweidenfeld** [comment]
This doesn't seem like a bug with the program for me. I looks like a SSL/TLS problem. Please update your ca-certificates and check if you can access the googleapi address by curl or something else ;)

**Comment by shenzo1** [comment]
OK thanks. But I have no problem mounting plexdrive when the cache has been deleted. And I can curl to the googleapi address to get an access token or a refresh token. Curl is at the latest version 7.54 with ssl/tls installed. This only happens when I unmount plexdrive and try to remount it _without_ deleting the cache. Any other idea?

**Comment by jrsdead** [comment]
I am having the same issue on macOS 10.11.6  It will fully load in if its running like a first mount but not on subsequent mount.  Any ideas?

**Comment by huangbong** [comment]
@jrsdead same here. OS X 10.11.6. Works on the first mount but then if you disconnect and try re-mounting it fails with Could not get object root from API

**Comment by shenzo1** [comment]
@jrsdead sorry for the late answer, I just saw your comment. No I am still having the same problem mounting plexdrive immediately after unmounting it. If I do wait what is an uncertain amount of time, plexdrive will mount again without the object root error. I have installed plexdrive on many Ubuntu systems and it works flawlessly. Must have something to do with the Mac version. Yet it seems that some of us using Mac don't have this problem. Please post if you find a solution.

**Comment by huangbong** [comment]
@dweidenfeld see above ^ and are you on 10.12? I think it's broken for 10.11 for some reason...

**Comment by shenzo1** [comment]
@huangbong Since upgrading to 10.12, I don't have the re-mounting issue anymore with plexdrive 2.0. I tried 2.1 and 4.0 and get a playback issue where the video streaming stops in Plex after 5 secs.

**Comment by dany20mh** [comment]
@shenzo1 for playback issue, try V2.1.0 and it will be fine.

**Comment by shenzo1** [comment]
Thanks @dany20mh. v2.0 actually works well. I had playback issue when upgrading to 2.1.0 or 4.0. v2.0 has proved the most stable for me. Are you on 4.0?

**Comment by dany20mh** [comment]
@shenzo1 That's interesting, maximum version I can go without any problem is V2.1.0

**Comment by drpau** [comment]
unfortunately this has been labeled as "wont fix" where it is not a client issue, it is a plexdrive issue.  I have found that i am unable to use any of the provided 5.0 releases on osx 10.13 due to the above issue. 

By going back to 4.1->2.0 i do not have the issue but i have other speed issues which i am working through.  

When running `dd if=/mount/file | pv | dd of=/dev/null` i receive a small burst of data then a significant pause, then more data, and pause, repeat.  I am hesitant to put it as an issue due to possibly being marked as "wont fix"
