### ISSUE TITLE
Use of root-node-id

### ISSUE THREAD

**Issue by zSeriesGuy** [dweidenfeld/plexdrive#170]
Using Plexdrive 4.0.0 trying to use root-node-id.
In my gdrive root is a folder called Plex. I would like it to be the root mounted with Plexdrive.
I am specifying --root-node-id="Plex" and getting:

root@PlexVPS:/lib/systemd/system# /usr/bin/plexdrive /PlexGD -o allow_other,read_only --chunk-size=8M --clear-chunk-age=1h -v 3 --root-node-id="Plex"
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : verbosity            : DEBUG
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : root-node-id         : Plex
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : config               : /root/.plexdrive
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : temp                 : /tmp
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : mongo-host           : localhost
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : mongo-user           :
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : mongo-password       :
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : mongo-database       : plexdrive
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : chunk-size           : 8M
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : refresh-interval     : 5m0s
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : clear-chunk-interval : 1m0s
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : clear-chunk-age      : 1h0m0s
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : clear-chunk-max-size :
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : fuse-options         : allow_other,read_only
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : UID                  : 0
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : GID                  : 0
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : Umask                : ----------
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : speed-limit          :
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : Opening cache connection
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : Authorizing against Google Drive API
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : Loading token from cache
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : Checking for changes
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : Getting start page token from cache
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] INFO   : Mounting path /PlexGD
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : Last change id found, continuing getting changes (79431)
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] INFO   : First cache build process started...
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] INFO   : Using clear-by-interval method for chunk cleaning
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : Getting root from API
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : Storing page token 79431 in cache
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] INFO   : First cache build process finished!
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : googleapi: Error 404: File not found: Plex., notFound
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] WARNING: Could not get object Plex from API
[USR/BIN/PLEXDRIVE] [2017-06-10 11:15] DEBUG  : cannot obtain root node: Could not get root object

I have tried different settings for root-node-id such as /Plex, ./Plex, etc.
Always the same results.
What am I doing wrong?

Without the root-node-id, it mounts successfully.
root@PlexVPS:~# ls -l /PlexGD/
total 0
drwxr-xr-x 1 root root 0 Mar 15 20:34 Plex

I noticed that the 404 message has a period after the node and before the comma. Could there be a length parsing error in the code? Or am I doing this wrong?

BTW, thank you so much for your work on this project.

**Comment by zenjabba** [comment]
--root-node-id= is the last string from the web URL for the folder.

**Comment by zSeriesGuy** [comment]
ah...thank you. I have it working now.

**Comment by crimsdings** [comment]
can we update README.md to reflect this better - came here with the same issue
