### ISSUE TITLE
New files not appearing in mount

### ISSUE THREAD

**Issue by markjwiggins** [dweidenfeld/plexdrive#171]
I had plexdrive working but any content added after ~30-May (realise the date is likely irrelevant) does not seem to appear in the mount.
I can see the files when logging into GDrive via browser, but not found within the plexdrive mount.

Cache appears to be complete, this started with plexdrive v2, and have now upgraded to v4 but the same content is found, i.e. not anything new.

I mounted via rclone and the files do appear (but subsequently hit the API ban), after the ban re-mounted with plexdrive and still no newer files.
I have tried deleting the cache, token.json & config.json in ~/.plexdrive and re-set up, also to no avail.
Is there something else I need to completely delete and restart cache?

**Comment by dweidenfeld** [comment]
No, this should be sufficient. 

Maybe your files are shared, with an option that is not supported by plexdrive, yet?

**Comment by markjwiggins** [comment]
Thanks @dweidenfeld 
I assume you mean share settings on the actual GDrive files.
I haven't changed anything that I am aware of, did you have any share options in mind that I could check?

**Comment by markjwiggins** [comment]
@dweidenfeld, I seem to of resolved, not entirely sure how but I did do two things and it seems to of worked...
* I did have "Convert uploaded to Google Format", which I wouldn't of thought got enacted for my files, but I turned this off
* I re-set my uploading authorization, again

And the new file seems to appear, I'm guessing it was to do with my uploading, and them getting corrupted or something somehow, rather than the Google setting.
Thank you for your help...
Feel free to close the ticket
