### ISSUE TITLE
Not all files showing in 4.0.0

### ISSUE THREAD

**Issue by hrc1079** [dweidenfeld/plexdrive#172]
I installed 4.0.0 and not all the files appear to be showing. When I mount with Google OCAML they're available but when mounting with Plexdrive they're not.  The only thing i'm noticing is there are duplicate directories on the ones that seem to have missing files.  Has anyone else seen this?

**Comment by zenjabba** [comment]
Thought this was fixed for 4.0. Will need more information as not everybody is seeing this problem.

**Comment by hrc1079** [comment]
Rclone Mount

<img width="662" alt="screen shot 2017-06-10 at 5 03 28 pm" src="https://user-images.githubusercontent.com/26352450/27007194-0cf0da92-4dff-11e7-80f2-a755727cd214.png">

Plexdrive mount

<img width="670" alt="screen shot 2017-06-10 at 5 04 07 pm" src="https://user-images.githubusercontent.com/26352450/27007197-1a3d30e2-4dff-11e7-9082-4d9cfef9f635.png">

**Comment by zenjabba** [comment]
Going to need to get a dump of your database.

**Comment by hrc1079** [comment]
not the greatest linux user here.  What's the best way of doing that?

**Comment by hrc1079** [comment]
[plexdrive.zip](https://github.com/dweidenfeld/plexdrive/files/1066260/plexdrive.zip)

I think this is what you're after.

**Comment by hrc1079** [comment]
Any ideas? The only workaround I can do at the moment is create a new directory and place the files in there.  I then re-pointed Sonarr to go to the newly created directory.  I tried deleting the problem directories and for some reason they just remained on Plexdrive.  Deleted the database and re-cached didn't solve the issue either.

**Comment by zenjabba** [comment]
Update to 4.1.0-latest-nightly
