### ISSUE TITLE
Deletion of shared files via Plex UI Returns Error stable ver 4.0.0

### ISSUE THREAD

**Issue by christeasdale** [dweidenfeld/plexdrive#173]
PLEXDRIVE] [2017-06-10 15:17] WARNING: Could not unsubscribe object 0B6370jvEMO0pWnZTOC00aUJ3WVU (Ballers - S02E02.mkv) from API

So when a file is deleted via a Plex client the file which is shared from one account to another is correctly deleted from Google Drive but the above error is returned and error is shown in Plex client UI as well.  The file is then still shown as available in local mounted folder until the next time Plexdrive "checks from changes"  default 5mins.  But if I delete similar shared file via CLi "rm" command or delete in WinSCP deletion works as expected without "warnings" or "errors".

**Comment by dweidenfeld** [comment]
How does plex delete files?

**Comment by christeasdale** [comment]
I am not sure how Plex deletes a file in Linux.  I tried checking Plex logs and could really find anything to helpful.  But I did double check and with all settings exactly the same.  If I add a file that is owned by the Google Drive account that is mounted as opposed to shared from another then Plex can delete it correctly with no errors and it is instantly removed from the mounted folder in Ubuntu.  But with more testing I have discovered using WinSCP to delete that there is a delay in PlexDrive deleting Google shared files of up to a few seconds before the deleted item is actually removed from the mounted folder in Ubuntu.  But if it is a Google Drive file that is owned then the deletion and removal from mounted folder in Ubuntu is instant.  So I think this is the problem.  Plex attempts deletion and when the file is slow to be removed Plex stops deletion and returns and error which then orphans the file.  I don't know if this helps.  I am not a coder.

**Comment by dweidenfeld** [comment]
Files should be deleted instantly and the API call should be handled in the background... If the API call is not successful the file is allowed to reappear.

**Comment by desimaniac** [comment]
I have plexdrive installed on my linux system and can't delete from Plex either. Get the message "There was a problem deleting this item."

**Comment by dweidenfeld** [comment]
#222
