### ISSUE TITLE
Intelligent cache sharing between multiple instances of plexdrive?

### ISSUE THREAD

**Issue by xyber411** [dweidenfeld/plexdrive#174]
I have 2 mirrored GDrive accounts, and was wondering what would happen if I attempted to use the same cache for both of them?  

My current method has them both writing to their own cache directories, but this means that if one goes down, the other cannot benefit from the cache that has already been downloaded.  
  Also, I only have 64GB to dedicate to the cache (a local SSD), so I currently have each halved at the maximum size of 60% of 30GB (18GB) as was recommended in the README.  Not really a problem, as I have Gb internet, but I'd really like to be able to use 60% of 60GB, rather than have to limit myself to 18GB which quite a few of my streamed files are larger than that.  Also, I notice that since I only use one of the GDrives at a time, the maximum I usually see in use is around 20GB.  I just wish I could get that number closer to 50GB without as much risk of killing the mount via full cache.

So, I guess I'd like to put in a feature request:
Intelligent cache sharing between multiple instances of plexdrive.

**Comment by dany20mh** [comment]
@xyber411 
I don't have 2 try, but can't you point both of them to 1 directory for temp chunk download using `-t` ?

**Comment by xyber411** [comment]
Correct, I /could/, but I have to wonder what would happen.  I know it's unexplored territory, and I'd test it myself, but I have the wife factor to be careful of.  I don't wanna hear "Your crap never works when I want it to" again. lol

**Comment by dany20mh** [comment]
@xyber411 
Test it when that factor is not available 😆

**Comment by xyber411** [comment]
@dany20mh 
I think the next time that is going to happen will be in about 2 weeks...
That's why I was hoping someone else had already tested it / had something off-production to test with. 
 The difficulty of kids and stay at home parents.

**Comment by dany20mh** [comment]
I thought it might work, but the chunks are save base on the file ObjectID, which it will be different from GDrive 1 and GDrive 2 that you have.

**Comment by xyber411** [comment]
@dany20mh

Thank you for having a look.  Seems it'll have to be a new feature request then.

**Comment by dweidenfeld** [comment]
not necessary anymore
