### ISSUE TITLE
PlexDrive - ERROR  : Could not open mongo db connection

### ISSUE THREAD

**Issue by SimonLefisch** [dweidenfeld/plexdrive#175]
I receive the error above when trying to configure plexdrive ($ plexdrive config) in Ubuntu to hunt my Google Drive. I already input my client I'd and secret. This is with Plexdrive 4.0.

**Comment by hrc1079** [comment]
Did you install mongo db?  Could be a permission issue also.

**Comment by Joshua1337** [comment]
Install MongoDB

https://docs.mongodb.com/manual/administration/install-on-linux/

**Comment by yrh1** [comment]
I am having the same issue.
I already installed MongoDB and verified that it is running.

**Comment by mitchelp** [comment]
There is no issue with plexdrive and mongodb this is related to the installation of Mongo. Ask around at our slack channel for help.
