### ISSUE TITLE
Systemd : PLexdrive can't start automatically

### ISSUE THREAD

**Issue by vampywiz17** [dweidenfeld/plexdrive#178]
Hello there,

I try to set to Plexdrive autostart with systemd. but i found  a problem:

```
jún 14 23:39:19 ubuntu systemd[1]: Started Plexdrive.
jún 14 23:39:42 ubuntu plexdrive[1570]: [USR/BIN/PLEXDRIVE] [2017-06-14 23:39] ERROR  : Could not open mongo db connection
jún 14 23:39:42 ubuntu plexdrive[1570]:
jún 14 23:39:42 ubuntu systemd[1]: plexdrive.service: Main process exited, code=exited, status=4/NOPERMISSION
jún 14 23:39:42 ubuntu fusermount[2050]: /bin/fusermount: failed to unmount /mnt/plexdrive: Invalid argument
jún 14 23:39:42 ubuntu systemd[1]: plexdrive.service: Control process exited, code=exited status=1
jún 14 23:39:42 ubuntu systemd[1]: plexdrive.service: Unit entered failed state.
jún 14 23:39:42 ubuntu systemd[1]: plexdrive.service: Failed with result 'exit-code'.

```
I think it try to start plexdrive too early and need to wait mongodb start.

If i start the servive after startup, it working well.

**Comment by zenjabba** [comment]
put in your system 

After=mongodb.service

**Comment by vampywiz17** [comment]
It not work, same errror... It possible that is a permission problem?

**Comment by vampywiz17** [comment]
Problem solved. :)

I use hamachi on server and the problem that the systemd script set to wait that network starting, but after my server disconnect the connection (start hamachi service) and need some second that rebuild again.

So i add this line to systemd script:

`ExecStartPre=/bin/sleep 80`

Now working well.
