### ISSUE TITLE
(New feature) Manually trigger check for changes

### ISSUE THREAD

**Issue by mattmac24** [dweidenfeld/plexdrive#18]
Firstly, great work on this project. It is working fantastically for me.

I imagine it is a fairly common usage case to upload with Rclone and then update Plex to add in the new content. However apart from setting a very low refresh interval which seems wasteful(I'm currently using 10s) you must wait until plexdrive notices the change and then send the command to Plex to tell it to update.

I think it would be good if it was possible to send a command to plexdrive telling it to check for changes, this would help my script and improve the process of uploading and adding content to my plex server. I've stopped using a union-fs temporary local cache of the files because they have a different mod-time and plex sees them as different files.

**Comment by dweidenfeld** [comment]
Why don't you set the Plex library scan interval to 15 min. Working great for me.

My setup uses the plexdrive defaults, plex to 15 min refresh rate and upload with rclone. A change will be detected by plex within 20 minutes.

**Comment by mattmac24** [comment]
Good suggestion, having avoided that option for months trying to avoid bans it is nice to remember that I can use it again. But this is not my preferred way of doing things.

Firstly, if I have just added whatever content to Sonarr/Radarr chances are I am wanting to watch it ASAP and don't like the idea of having to wait 1-20 mins hitting refresh for it to show up. Currently it usually takes me no more then 8 minutes between adding something to Sonarr/Radarr and it showing up in Plex, I don't want to increase that time unnecessarily.

Secondly, maybe this is me being OCD but I like my setup to be proactive and event driven, not reactionary in general. My script adds the content to Plex and then checks the Plex database to make sure it has has been added correctly and then sends me a notification of the success/failure.

So if this is something you would be happy to add I would use it and probably turn the refresh-interval off or to 24 hours. But if not I understand as maybe you don't see much value in it.

Is there any negatives to setting a refresh-interval of 10 seconds?

**Comment by chris243** [comment]
What is the refresh interval at now? In my set up I only upload once 100gb of local storage is used so I just need to know how long it takes for plexdrive to find these files so I can add a delay to my script. I shut my server down in the process so it's not a big deal how long the interval is set at.

**Comment by mattmac24** [comment]
The default is listed in the readme as 5 minutes.
  -refresh-interval duration
    	The number of minutes to wait till checking for changes (default 5m0s)

This description should probably be updated because it is not actually the number of minutes, inputting just a number will not work. you need to input the 'unit' as well (h,m,s)

**Comment by zenjabba** [comment]
I'm running mine at 30s and seems to be working fine.

**Comment by dweidenfeld** [comment]
You can set the interval to 1 second if you want. It will just queue your refresh requests. So if one refresh is still active, the next request will wait for the first one to finish.
Please have a good look on your quota, I am not quite sure how many requests are fine for you... Scanning every second means 1 * 60 * 60 * 24 = 86400 API calls a day just for refreshing your content. You have to add the API calls starting a movie etc. ;)

I am not quite sure if I got you right @mattmac24... you want to start the refresh manually with an external trigger or do you want the program to execute your script after it has detected changes?
The second way looks more idiomatic to me.

**Comment by mattmac24** [comment]
Ideally I want to be able to start the refresh manually with an external trigger

**Comment by dweidenfeld** [comment]
Well, I don't think that you will profit with an external trigger. You achieve the same results just setting the refresh interval for example to 30s (or lower).
You will only reduce the API call count with an external hook.

**Comment by mattmac24** [comment]
Fair enough, there doesn't seem to be any harm in using a much lower refresh interval, just a lot of unnecessary API calls in my case.

**Comment by mcadam** [comment]
Hi guys, just had the problem in plex of showing the file twice, I suppose it scanned it before when it was appearing in rclone then from plexdrive after the refresh.
@zenjabba do you mind putting your options you are using to mount rclone and plexdrive, I am currently using same configuration as you as in plexdrive=RO:rclone=RW.

Cheers for the good work @dweidenfeld, just changed from node-gdrive-fuse, because only got it to work without refresh, to plexdrive, and everything is working as well as before for now, and much simplified configuration :)

**Comment by zenjabba** [comment]
The latest beta of rclone can replace plexdrive completely, and it also includes uploading via CoW. 

Make sure you are using the latest rclone and then remove plexdrive.

**Comment by Dulanic** [comment]
I disagree with this. Rclone cache causes me API bans.

**Comment by mcadam** [comment]
I want to wait a bit more to switch to rclone cache, I have seen some people still getting some bans and when I tried it the time to actually start streaming on plex was faster with plexdrive, I prefer to keep plexdrive until the quirks are resolved on rclone cache :)

Right now I am having issues with the mount plexdrive=RO:rclone=RW, I am getting permission denied on trying to delete a file from the unionfs mount. Any ideas? Again would be nice to see your options passed to the command. 

Cheers for the help

**Comment by Dulanic** [comment]
@dweidenfeld made a great program in plexdrive and I still find it much better than rclone cache myself. 

This is the script I use which I forked from madlundt version which uses unionfs. I converted it to use mergerfs.

Fork:
https://github.com/Dulanic/cloud-media-scripts
Original:
https://github.com/madslundt/cloud-media-scripts

**Comment by mcadam** [comment]
Thank @Dulanic just tried mergerfs and it works same as unionfs and also delete succesfully: here is my command for those interested:
```
mergerfs -o defaults,nonempty,allow_other,direct_io,use_ino,category.create=ff,category.search=ff,minfreespace=0,uid=1000,gid=100 /mnt/gdrive-plexdrive=RO:/mnt/gdrive-rclone /mnt/media
```
