### ISSUE TITLE
WARNING: Could not read object

### ISSUE THREAD

**Issue by kecinzer** [dweidenfeld/plexdrive#180]
Hi Dominik.
I have mounted my GDrive with plexdrive successfuly, but I can't read any files. I getting this warning:

USR/BIN/PLEXDRIVE] [2017-06-16 10:46] WARNING: Could not read object 0Byu8_SOia1GcWUJGMXFjMDgwR1U (mountcheck) / StatusCode: 403

It looks like issue with access rights?

When mounting I using only this options:
-m localhost \
-o allow_other \

**Comment by zenjabba** [comment]
403 generally tells us you have hit either an API limit or usage limit.
