### ISSUE TITLE
[Feature Request] Rename files/directories

### ISSUE THREAD

**Issue by ErAzOr2k** [dweidenfeld/plexdrive#181]
Hi dweidenfeld,

can you please add the ability to rename files and/or folders on the plexdrive mount?

Thank you

**Comment by dweidenfeld** [comment]
I am sorry I had to revert the PR, but it has been merged too early.. There is still the problem with multi-directory files. 
Those files still get deleted. So please fix this (just pass the parent object id in the function and only remove this parent and do not remove all parents). Then I can merge it ;)

**Comment by ErAzOr2k** [comment]
ok thanks for your feedback.
I'll fix it
