### ISSUE TITLE
Following the the Guide fails

### ISSUE THREAD

**Issue by cheremo** [dweidenfeld/plexdrive#182]
Hi all,

first of all: im a noob! ;)
And maybe someone could help me and others that get stuck in the TUTORIAL.md.

i followed step by step the tutorial (and didnt du anything more).
- plexdrive is working, playback via plex is also working.
- rclone is installed but something does not work (see below).

--> i don't need the encryption (but if possible i would take) but the real thing i want is to be able to synchronize in both ways (when I try to upload s.th. to  /mnt/plexdrive/ it'll fail. (i think for this I need the rclone and unionfs-fuse?)
```
[local-crypt]
remote = /mnt/plexdrive/encrypted
filename_encryption = standard
password = *** ENCRYPTED ***
password2 = *** ENCRYPTED ***
```

But when I want to start rclone in step 13 with the command "systemctl start rclone.service" get this error:
```
Failed to create file system for "local-crypt:": didn't find section in config file
systemd[1]: rclone.service: main process exited, code=exited, status=1/FAILURE
fusermount[17792]: /bin/fusermount: failed to unmount /mnt/media: Invalid argument
systemd[1]: rclone.service: control process exited, code=exited status=1
```

what am i doing wrong? :(

**Comment by zenjabba** [comment]
you don't have the --config line in the systemd script... Please take this over to the rclone forum [if](https://rclone.org) you have any more issues as they can help you better.
