### ISSUE TITLE
Mount drops randomly when streaming large files

### ISSUE THREAD

**Issue by bFanek** [dweidenfeld/plexdrive#183]
My plexdrive mount randomly unmounts without printing out any errors other than the "could not find children" Warnings.
I'm currently using:
`plexdrive -v 2 --clear-chunk-age=2h --refresh-interval=1m --chunk-size=100M --umask=0 -o allow_other,read_only /Users/Basel/.cloud/`

After playing 3-5 minutes of the movie, the mount drops and I have to remount it and encfs again.
Smaller files like episodes seem to be okay.

I'm under Mac OSX and using 2.0.1 (because of a known bug on mac on later versions where videos keep skipping a minute or two every few seconds). I'm decrypting using encfs on top of plexdrive.

Any ideas? thanks!

**Comment by dweidenfeld** [comment]
2.0.1 has some issues with autorecovering from errors. I am currenlty working on a mac os x version with better performance. This should fix macos issues and will be more stable #67
