### ISSUE TITLE
Can't play split rar files in Kodi

### ISSUE THREAD

**Issue by syaifulnizamyahya** [dweidenfeld/plexdrive#184]
I split my media into smaller file size using Winrar for easier upload. These rar files can be played in Kodi if the files is local. But if the files is mounted using plexdrive, Kodi cant play it. If the media is not split, Kodi can play just fine for both local on plexdrive mounted.

The rar files are stored(not compressed) in 100mb files with old winrar protocol. A split rar files looks like this, A.Movie.part002.rar. 

This is the command for plexdrive

```
 screen -S plexdrive -d -m plexdrive \
 --fuse-options=\
 allow_other\
 ,read_only\
  \
 --verbosity=3 \
 /mnt/user/Cloud/
 
```

I suspect this issue is related to the plexdrive mounting command. Any advice?

Thanks.

**Comment by zenjabba** [comment]
Use plex?

**Comment by dweidenfeld** [comment]
I think the performance is not good enough. I am currently working on it #67

**Comment by TheMightyBattleCat** [comment]
@syaifulnizamyahya Just a thought, Have you seen or tried using <https://github.com/hasse69/rar2fs> as an intermediate mount? Since your RAR's are uncompressed, it offers it's own caching for volume spanning. Just throwing it out there! Rclone crypt > rar2fs > plexdrive?
