### ISSUE TITLE
What is the unit of chunk-size?

### ISSUE THREAD

**Issue by syaifulnizamyahya** [dweidenfeld/plexdrive#187]
What is the unit for chunk size? is it bits or bytes?

I want to set my chunksize to be 5400 megabits. What number should I put?

**Comment by animosity22** [comment]
It depends on what you end it with:

```
  --chunk-size string
    	The size of each chunk that is downloaded (units: B, K, M, G) (default "5M")
```

So 5M would be 5 megabytes. 5K would be 5 kilobytes.
