### ISSUE TITLE
Drive periodically stops working

### ISSUE THREAD

**Issue by Krandor1** [dweidenfeld/plexdrive#189]
I'm having an issue where once in a while the drive seems to stop working even though in some cases everything is running.

Case in point right now.

krandor@Krandor:/mnt/done/tv$ ps -aef | grep mongo
root     10627     1  0 Jun21 ?        00:13:28 /usr/bin/mongod --quiet --config /etc/mongod.conf

krandor@Krandor:/mnt/done/tv$ ps -aef | grep plexdrive
root     10628     1  4 Jun21 ?        01:46:00 /home/owner/plexdrive -o allow_other --clear-chunk-max-size=10G /mnt/plexdrive
root     10689     1  0 Jun21 ?        00:20:34 rclone mount --allow-other plexdriveenc: /mnt/gdrive

krandor@Krandor:/mnt/done/tv$ ls /mnt/plexdrive
krandor@Krandor:/mnt/done/tv$

If I go to the mongodb directory outside of diagnostic data none of the other files have been updated in over a day.

16777262 -rw-r--r--  1 root    root        36864 Jun 21 17:34 collection-0-927324240125084820.wt
16777266 -rw-r--r--  1 root    root     46067712 Jun 21 23:01 collection-2-927324240125084820.wt
16777270 -rw-r--r--  1 root    root        36864 Jun 21 23:01 collection-6-927324240125084820.wt
16777264 drwxr-xr-x  2 root    root         4096 Jun 23 07:06 diagnostic.data
16777263 -rw-r--r--  1 root    root        36864 Jun 21 17:34 index-1-927324240125084820.wt
16777267 -rw-r--r--  1 root    root      9289728 Jun 21 23:01 index-3-927324240125084820.wt
16777268 -rw-r--r--  1 root    root      1765376 Jun 21 23:01 index-4-927324240125084820.wt
16777269 -rw-r--r--  1 root    root     46215168 Jun 21 23:01 index-5-927324240125084820.wt
16777271 -rw-r--r--  1 root    root        16384 Jun 21 17:33 index-7-927324240125084820.wt
16777250 drwxr-xr-x  2 root    root         4096 Jun 21 17:34 journal
16777260 -rw-r--r--  1 root    root        16384 Jun 21 17:33 _mdb_catalog.wt
16777249 -rw-r--r--  1 root    root            6 Jun 21 17:33 mongod.lock
16777259 -rw-r--r--  1 root    root        36864 Jun 21 23:01 sizeStorer.wt
16777261 -rw-r--r--  1 root    root           95 Jun 19 14:58 storage.bson
16777252 -rw-r--r--  1 root    root           49 Jun 19 14:58 WiredTiger
16777257 -rw-r--r--  1 root    root         4096 Jun 21 17:33 WiredTigerLAS.wt
16777251 -rw-r--r--  1 root    root           21 Jun 19 14:58 WiredTiger.lock
16780501 -rw-r--r--  1 root    root         1004 Jun 21 23:01 WiredTiger.turtle
16777253 -rw-r--r--  1 root    root        61440 Jun 21 23:01 WiredTiger.wt

**Comment by dweidenfeld** [comment]
Fixed in next version.
