### ISSUE TITLE
Feedback during setup.

### ISSUE THREAD

**Issue by Dimtar** [dweidenfeld/plexdrive#19]
So i have installed plexdrive.

I run "./plexdrive /home/cloud"
Enter my details, do the verification link in the browser and paste the code back into the SSH session. Then I wait, so far an hour has passed but nothing has happened visually. I can see the mount and the files inside it but the initial SSH session is still "stuck" at the authorization code.

Is this normal? If so, would it be an idea to notify the user something is happening and to expect a wait so they don't think the system has hung? If its not normal behavior, is there an idea as to what I may have done wrong?

Thanks.

**Comment by johnpowell** [comment]
Mount with -log-level 3 and it will let you know its progress. It will tell you when it finishes building the cache.

**Comment by dweidenfeld** [comment]
```log-level 2``` is sufficient and will not spam your terminal session.

You should also run the program as daemon or in a screen session. Please check my init script for example ;)
