### ISSUE TITLE
[BUG] File copy never finish with 4.1.0-beta-1498656614

### ISSUE THREAD

**Issue by ajkis** [dweidenfeld/plexdrive#194]
The file copy never finishes 
Test
`pv --bytes --progress --rate --average-rate --timer --eta "/mnt/cloud/tmp/100M.file" > "~/tmp/"`
or 
`cp "/mnt/cloud/tmp/100M.file" "~/tmp/"`

**Comment by dweidenfeld** [comment]
lets discuss that in slack ;)

**Comment by ajkis** [comment]
UPDATE 
Copy finish but its waiting for around 2 minutes and after further testing I found out its --chunk-load-timeout thats causing it.

I changed from default 30 seconds to 2 seconds and files was copied in 15 seconds.( compared to 125 seconds before )
