### ISSUE TITLE
Suggestion: Track Major Versions in Separate Branches

### ISSUE THREAD

**Issue by YipYup** [dweidenfeld/plexdrive#196]
I think it would be an improvement if you had a branch for your latest 1.x, 2.x, 3.x, and 4.x for example. That way, if someone wanted to propose a code change or evaluate the code in the 3.x latest, they could easily do so. While generally most users would want to download and use only the latest, it may be of value for people to be able to pull up and compare changes between the major versions through branching. Further, you could have develop and release branches for your upcoming features and track them separately than the v1/2/3/4 . x masters. This is an awesome article which addresses four common workflow methods, the logic behind them, and gives example scenarios of what and why. I don't want to get into telling you what to do, nor do I have the experience to do so, but I thought this might be worth a look. Hope this is beneficial. Thanks for your awesome development work!

https://www.atlassian.com/git/tutorials/comparing-workflows#gitflow-workflow

**Comment by 2600box** [comment]
Indeed, with the upcoming shift back to Bolt from MongoDB it seems important to have a clearly defined branch.

**Comment by dweidenfeld** [comment]
I planned to use GitFlow, but after the next release for a clean cut. So the master will always be the stable version.
I don't want v-*.*.* branches, because people will think that I will support old versions. I don't have the time to manage multiple versions, so the master will be the only source of truth.
