### ISSUE TITLE
[Feature Request] Chunk deletion logic suggestion/enhancement if possible

### ISSUE THREAD

**Issue by TheMightyBattleCat** [dweidenfeld/plexdrive#197]
Just a suggestion regarding the chunk clearing logic. Currently as I understand it, it either starts to delete by added date order (oldest first) once the chunk size has been reached though **clear-chunk-max-size**, or you can specify a time based on when it was last accessed **--clear-chunk-age**. I was wondering how feasible it would be when the chunk max size is reached, it then deletes the least accessed chunks/cache, keeping the more recently accessed files still in the cache despite being the oldest?

As a scenario I have 1TB assigned for **clear-chunk-max-size**. A few of my friends with kids literally loop some kids movies all day every day to keep them quiet, until they are bored and binge loop on a new title. If they were the first added to the cache then they would be the first deleted, despite probably being the most recently accessed. Just a thought! 

Thanks for all your hard work with this. It’s a great project and is making huge progress considering how young it is.

**Comment by dweidenfeld** [comment]
The last access date will be used. So the most "unused" chunk will be deleted first. But the logic is not that stable. The next release will improve the logic.
