### ISSUE TITLE
Few Questions

### ISSUE THREAD

**Issue by animosity22** [dweidenfeld/plexdrive#2]
I'm assuming on first launch, it's building the cache up? I was waiting for that to finish up I think.

Also, I'm assuming I can just pass the standard fuse options? I was trying to make sure allow_other works as well.

**Comment by dweidenfeld** [comment]
Hi, yes you're right. It will first update its cache. But you will also be able to traverse the directories directly, because it also supports a "live fetch".

The fuse options are not supported by now, but I think I can implement it fast (not today ;) )

**Comment by dweidenfeld** [comment]
Closed with #6
