### ISSUE TITLE
4.1.0-beta-1498397749 - WARNING: Could not update/save object

### ISSUE THREAD

**Issue by 2600box** [dweidenfeld/plexdrive#200]
my plexdrive stopped working overnight “Jul 02 02:14:05 debian plexdrive[410]: [USR/BIN/PLEXDRIVE] [2017-07-02 02:14] WARNING: Could not update/save object”

using 4.1.0-beta-1498397749 on debian

gdrive is unlimited and my system disk has 60% free. api requests are only 41,000 for today

i am using rclone crypt on top of plexdrive

stopping plexdrive and starting it again - no other changes - and it works normally again.

**Comment by zenjabba** [comment]
2600box restarted the process and it continued.
