### ISSUE TITLE
5.0.0-beta.1498837265 has many 'WARNING: Timeout while requesting chunk' and dies with 'killed'

### ISSUE THREAD

**Issue by 2600box** [dweidenfeld/plexdrive#203]
Decided to give 5.0.0-beta.1498837265 a try because 4.1 was causing issues.  

5.0 throws many 'WARNING: Timeout while requesting chunk' as it retries the same chunks. Then it died with 'killed'. I did a lazy unmount and restarted plexdrive and rclone. 

I am using defaults with `plexdrive -v 2 /mnt/plexdrive` while rclone crypt mount is also defaults.

**Comment by ajkis** [comment]
This is the last production ready version: https://github.com/dweidenfeld/plexdrive/releases/tag/4.1.0-beta-1498397749
