### ISSUE TITLE
5.0.0 latest best breaks chunk max size and clear chunk age

### ISSUE THREAD

**Issue by jscottdouglas** [dweidenfeld/plexdrive#204]
not sure if this has been noted but both commands get broken in the 5.0 beta, was using --clear-chunk-max-size=300G --clear-chunk-age=24h with 4.0 release thought i'd give 5.0 a try and found those two commands dead.

**Comment by dany20mh** [comment]
These are the new command you can use with V5

```
Danials-iMac:~ danial$ ./plexdrive5
Usage of ./plexdrive5:
  --cache-file string
    	Path the the cache file (default "/Users/danial/.plexdrive/cache.bolt")
  --chunk-load-ahead int
    	The number of chunks that should be read ahead (default 2)
  --chunk-load-retries int
    	Number of retries to load a chunk (default 3)
  --chunk-load-threads int
    	The number of threads to use for downloading chunks (default 4)
  --chunk-load-timeout duration
    	Duration to wait for a chunk to be loaded (default 10s)
  --chunk-size string
    	The size of each chunk that is downloaded (units: B, K, M, G) (default "5M")
  -c, --config string
    	The path to the configuration directory (default "/Users/danial/.plexdrive")
  -o, --fuse-options string
    	Fuse mount options (e.g. -fuse-options allow_other,...)
  --gid int
    	Set the mounts GID (-1 = default permissions) (default -1)
  --max-chunks int
    	The maximum number of chunks to be stored on disk (default 10)
  --refresh-interval duration
    	The time to wait till checking for changes (default 5m0s)
  --root-node-id string
    	The ID of the root node to mount (use this for only mount a sub directory) (default "root")
  -t, --temp string
    	Path to a temporary directory to store temporary data (default "/var/folders/p1/5_hc57d54wnc53wsnqdjpb_00000gn/T/")
  --uid int
    	Set the mounts UID (-1 = default permissions) (default -1)
  --umask value
    	Override the default file permissions
  -v, --verbosity int
    	Set the log level (0 = error, 1 = warn, 2 = info, 3 = debug, 4 = trace)
  --version
    	Displays program's version information
```

**Comment by zenjabba** [comment]
No longer needed, so they were removed. Please check the readme(https://github.com/dweidenfeld/plexdrive/tree/develop#usage) so you can see the new commands.

**Comment by dany20mh** [comment]
@zenjabba 
Just the quick question about those then, how the process of chunk will handle now, if they save in temporary folder, when they get delete and is there any max to them?

**Comment by zenjabba** [comment]
basically the chunk is only around 50MB now by default and gets deleted very quickly. The chunk process has changed since 4.0 (--max-chunks).

**Comment by jscottdouglas** [comment]
That's where I was going with this, I typically watch the same shows at night so the chunks never really get removed for those few shows, since i had it set at 24 hours with a max size of 300G

**Comment by dany20mh** [comment]
@zenjabba 

So we assume that we using the default value (for chunk size "5Mb"), are we talking about the whole folder that is 50MB now or the chunk for each file (when they playing) get to that size.

I'm just asking this to understand how this is working now, cause if it's not that much of size now, I can use a RAM Disk with like size of 10Gb and that has very good speed of read and write, and I really not much caring of internet speed of re-downloading chunks again.

**Comment by zenjabba** [comment]
Current the chunk folder will not (by default) go 10X over the chunk size so it will be 50MB in total. 
/dev/shm would be a great place for it to live if your operating system supports it.

**Comment by jscottdouglas** [comment]
with all this being said i also noticed it's mounting doesn't seem to do permissions correctly in debian jessie.

/usr/local/bin/plexdrive/plexdrive.5.0.0 /diskpool/gotest -o allow_other --config=/home/srv1/.plexdrive --temp=/diskpool/tmp --umask=022 --verbosity=2

d----w--w-  1 srv1 srv1    0 May 22 23:24 google
d----w--w-  1 srv1 srv1    0 May 22 23:24 .google

I tried also without the umask, 4.0 mounts it properly.

drwxr-xr-x  1 srv1 srv1    0 May 22 23:24 google
drwxr-xr-x  1 srv1 srv1    0 May 22 23:24 .google
