### ISSUE TITLE
How to mount an existing crypt drive in Plexdrive?

### ISSUE THREAD

**Issue by richardtheb** [dweidenfeld/plexdrive#206]
Hey all, I am experimenting with Plexdrive. Looks good so far, but I am not clear on something: how do I mount an existing crypt drive? I have my media on GDrive in a crypt folder that I can read in rclone, but the tutorial on mounting this in plexdrive (this onehttps://github.com/dweidenfeld/plexdrive/blob/master/TUTORIAL.md) seems to create a new google drive user rather than use the existing one.  I assume that's because of the OAuth approach that plexdrive uses. 

How do I adapt this for an existing crypt drive?

**Comment by 2600box** [comment]
in your `.rclone.conf` copy the configuration for your rclone crypt and change the remote: to your local directory and change the name for this config. don't change the passwords.

See below:

```
[rclone_crypt]
type = crypt
remote = rclone:bucket
filename_encryption = standard
password =
password2 =

```
becomes

```
[local_crypt]
type = crypt
remote = /mnt/plexdrive/bucket
filename_encryption = standard
password =
password2 =
```
