### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by memnos** [dweidenfeld/plexdrive#207]
Hi all,
is it i'm using plexdrive 5.0.0-beta.1499405619 and i have a cpu using always between 98-100% as you can see in the attached picture.
Is it normal?
My chunks are:
51M     /tmp/chunks/
My cache.bolt is 25M

Tnx
![plexdrive](https://user-images.githubusercontent.com/25641404/28007960-ce66bd00-6555-11e7-8fbe-7f726a7d6c47.jpeg)

**Comment by dweidenfeld** [comment]
Yes this is normal, because of the higher bandwidth usage.
I will try to improve it in the future ;)

**Comment by memnos** [comment]
But it is so, also when i'm not using plex.
If i reboot my server, then cpu usange is zero.
It seems that during usage cpu usage grows but doesn't goes down when the use of bandwidth is stopped

**Comment by romainwurtz** [comment]
Same issue on me end with nothing running I get > 150% CPU after 24H.
