### ISSUE TITLE
High cpu usage with no usage

### ISSUE THREAD

**Issue by Dopefish123** [dweidenfeld/plexdrive#210]
Ubuntu 16.04
Plexdrive 5.0.0-beta.1499807689

/usr/bin/plexdrive /media/PMS/ --verbosity=3 --fuse-options=allow_other,read_only --chunk-size=8M --max-chunks=1000 --config=/home/aj/PlexdriveGoogleG3 --cache-file=/home/aj/PlexdriveGoogleG3/cache.bolt

After usage the CPU does not drop but stays very high:
![skjermbilde](https://user-images.githubusercontent.com/4976642/28126682-76ffefd8-672a-11e7-9501-27e8cd0493a2.PNG)

**Comment by Dopefish123** [comment]
Why close the issue without any explanation, it’s not solved?

**Comment by dany20mh** [comment]
@Dopefish123 
Because you are using beta version and he knows about it, so he close it to prevent the confusion of other people at least, and this issue reported before already.

**Comment by Dopefish123** [comment]
How about just replying; it is a known issue which will be resolve in the next production release, before just closing it. It would give the project much positive/better interactions with its users.

**Comment by dany20mh** [comment]
@Dopefish123 
As I said, it's because you didn't check, he already replied there.
https://github.com/dweidenfeld/plexdrive/issues/207

**Comment by Dopefish123** [comment]
I saw that and could give more details why it does not apply:
> Yes this is normal, because of the higher bandwidth usage.
> I will try to improve it in the future ;)

First off, to use two full cores at 100% idling has nothing to do with bandwidth and does not make sense. He does not say it is solved, just might be improved in the future and closed it.
