### ISSUE TITLE
Database Cache Does Not Change to Config Location

### ISSUE THREAD

**Issue by Kolmain** [dweidenfeld/plexdrive#211]
When specifying a config location with `-c /path/to/config`, the cache file for the database remains in `~/.plexdrive/cache` which breaks multiple mounts.

**Comment by Kolmain** [comment]
On the latest 5.0 beta.

**Comment by dany20mh** [comment]
@Kolmain 

I never use it before, but did you tried to use this :

```
--cache-file string
    	Path the the cache file (default "/Users/danial/.plexdrive/cache.bolt")
```

**Comment by dweidenfeld** [comment]
there is an extra option for this now.

**Comment by Kolmain** [comment]
Is it the `--cache-file`? and which release is it in?
