### ISSUE TITLE
File size of plexdrive file links?

### ISSUE THREAD

**Issue by FaeDine** [dweidenfeld/plexdrive#217]
Not an issue, just a question.

**How much space does a link to a file mounted on Google Drive take up on the local file system? Is it just a few KB?**

I ask because I'm mounting in a system with a large block size (1MB) I had to large file storage and I think the files are using up way more space than they need to. I'm curious how much space they actually take up to adjust my drive accordingly.

Thanks!

**Comment by dweidenfeld** [comment]
It should be free. So no size is required here... only the meta information in the cache is required. Those meta information are only a few kb.
