### ISSUE TITLE
Allow for specific folder to be mounted

### ISSUE THREAD

**Issue by kilabyte** [dweidenfeld/plexdrive#22]
Instead of mounting the entire drive which in my case contains media and drive documents, mount just a specific folder (the media folder in this case). This should improve indexing performance.

**Comment by kilabyte** [comment]
I have a fork already that is someone doing this. @dweidenfeld if you want to assign it to me

**Comment by dweidenfeld** [comment]
@kilabyte how long do you think you need to finish this feature? Maybe we can add it to the next release?

**Comment by kilabyte** [comment]
@dweidenfeld I haven't worked on it since the other day. I have it listing the children but with a child object it doesn't have the same struct as a File. So i am re-looking at just to filter the File list instead. But i wont be able to work on it until tomorrow.

**Comment by scoopydude2002** [comment]
Can be probably be added using the libfuse module as with and_cli: --modules="subdir,subdir=/folder"

**Comment by wrboyce** [comment]
I've implemented this feature and sent a PR - #103

**Comment by dweidenfeld** [comment]
Included in the next release.
But be aware that the function implemented by @wrboyce is kind of "fake" ... it will not give you performance improvements. It will only be an "optical change" on how the root folder is displayed.
