### ISSUE TITLE
5.0.0-beta.1499930518 crashing on Raspberry PI 3 B

### ISSUE THREAD

**Issue by kecinzer** [dweidenfeld/plexdrive#220]
Yesterday I tried plexdrive 5.0.0-beta.1499930518 on my new RPI 3B and I found that I can mount my Google Drive just well, but when Plex scanning attached folder, plexmount consumes all RAM of RPI (1GB) and then crashed. I tried increase SWAP size, but result was the same.
Today I tried stable version plexdrive 4.0.0 and its working without issues. RAM is consumed as well, but plexdrive hold Google Drive mounted without crash.

Is there some big change in version 5.0.0?

**Comment by dweidenfeld** [comment]
Yes... most data is now stored in memory... so i think 1gb ram is just not enough. you could try to recuce the max-chunks to 2 or so but then you'll also have to reduce the load-ahead value etc ;)

**Comment by kecinzer** [comment]
Thank you for explanation.
Is there any choice to set this behaviour by parameter? As I can't upgrade RAM on my Raspberry Pi 3.

**Comment by dweidenfeld** [comment]
like i said... try
`--max-chunks=2 --chunk-load-threads=1 --chunk-check-threads=1 --chunk-load-ahead=1` or something like that.

Just play around with those settings ;)
