### ISSUE TITLE
No way to specify temporary folder in 5.0 (develop)

### ISSUE THREAD

**Issue by Thinkscape** [dweidenfeld/plexdrive#221]
Where did the `-t` flag go?

The temp files used to grow quite large... I want to be able to specify where to store them.

**Comment by Thinkscape** [comment]
Found it, sorry:

```
  --cache-file string
    	Path the the cache file (default "~/.plexdrive/cache.bolt")

```

**Comment by dany20mh** [comment]
V5 doesn’t use the temp folder anymore, that’s just the cache file for the changes, in this version, everything get save on the RAM
