### ISSUE TITLE
Is the latest release working for anyone?

### ISSUE THREAD

**Issue by cardinalfan1** [dweidenfeld/plexdrive#224]
I'm not seeing a flood of comments on this forum, so I'm guessing this is working for mostly everyone.... but this latest 5.0 release is not working at all for me. Did anything change about it, any ports need to be forwarded or anything?

**Comment by ajkis** [comment]
More then likely you did not use mount command.

**Comment by cardinalfan1** [comment]
Haha, nope that's not it.
Here's the last version that is working for me: 5.0.0-beta.1499930518

Here's my mount command:
`plexdrive mount -o allow_other,read_only -c /settings/.plexdrive --gid=$PGID --uid=$PUID --root-node-id="<...>" /cloud/.remote-read-encrypt &`

I can successfully mount and get the directory structure... but when I try to read any file it hangs and refuses to execute

**Comment by cardinalfan1** [comment]
> [PLEXDRIVE] [2017-08-03 21:48] TRACE  : FUSE -> [ID=0xcb] Lookup 0x4a gen=16 valid=1m0s attr={valid=1m0s ino=687293345586657407 size=1362211345 mode=-rw-r--r--}
> [PLEXDRIVE] [2017-08-03 21:48] TRACE  : FUSE <- Read [ID=0xcc Node=0x31 Uid=0 Gid=0 Pid=24253] 0x2 4096 @0x9b8 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock
> [PLEXDRIVE] [2017-08-03 21:48] TRACE  : FUSE -> [ID=0xcc] Read 0
> [PLEXDRIVE] [2017-08-03 21:48] TRACE  : FUSE <- Release [ID=0xcd Node=0x31 Uid=0 Gid=0 Pid=0] 0x2 fl=OpenReadOnly+OpenDirectory+OpenNonblock rfl=0 owner=0x0
> [PLEXDRIVE] [2017-08-03 21:48] TRACE  : FUSE -> [ID=0xcd] Release
> [PLEXDRIVE] [2017-08-03 21:48] TRACE  : FUSE <- Open [ID=0xce Node=0x3f Uid=0 Gid=0 Pid=24268] dir=false fl=OpenReadOnly
> [PLEXDRIVE] [2017-08-03 21:48] TRACE  : FUSE -> [ID=0xce] Open 0x2 fl=0
> [PLEXDRIVE] [2017-08-03 21:48] TRACE  : FUSE <- Read [ID=0xcf Node=0x3f Uid=0 Gid=0 Pid=24268] 0x2 4096 @0x0 dir=false fl=0 lock=0 ffl=OpenReadOnly

This is the trace output of plexdrive when Im trying to read any file

**Comment by 2600box** [comment]
bring it back to basics and remove all the variables. delete your cache and do a simple plexdrive mount -v 3 /mnt/plexdrive

**Comment by Buervenich** [comment]
Same problem for me. When mounting with 5.0.0, I can see my file structure but Plex can't find any media, it just conontini

**Comment by Buervenich** [comment]
Same problem for me. When mounting with 5.0.0, I can see my file structure but Plex can't find any media, it just scans and scans until I abort it.

I tried to read a simple text file from the mounted volume, this makes nano hang up completely.

**Comment by cardinalfan1** [comment]
I tried deleting the cache.bolt file without success.... I also tried regenerating the auth files.... Are there any other files to try and delete

**Comment by danjames92** [comment]
go back to basics like @2600box said and then start adding stuff 1 by 1.

**Comment by cardinalfan1** [comment]
plexdrive mount -o allow_other -c /settings/.plexdrive/ /cloud/.remote-read-encrypt &

Still no success....

**Comment by danjames92** [comment]
Whers your mount?

I see no mnt/plexdrive

On 5 Aug 2017, at 21:41, cardinalfan1 <notifications@github.com<mailto:notifications@github.com>> wrote:


plexdrive mount -o allow_other -c /settings/.plexdrive/ /cloud/.remote-read-encrypt &

Still no success....

**Comment by Dimtar** [comment]
I am having the same issue. OP, out of interest is your drive full of a lot of files? By that I mean like lots of small files (not media)

**Comment by cardinalfan1** [comment]
@Dimtar I would say a mix of small and large files.
@danjames92 mount is `/cloud/.remote-read-encrypt`

I tried running the same thing on a different machine and it seems to be working, so it's probably something to do with my setup. I have a VM behind proxmox, so I'm wondering does plexdrive use any network connections that may potentially be firewalled? Any ports that need to be exposed?

Thanks

**Comment by cardinalfan1** [comment]
I was looking through the changelog between 5.0.0-beta.1499930518 and 5.0.0-beta.1501179373 and the only thing has changed is the icon ... which doesn't make sense, because that's when it stops working for me. Maybe there's something wrong with the compiled version I'm using for amd64-linux?

**Comment by Dimtar** [comment]
@cardinalfan1 how big is your cache db once its built?

**Comment by cardinalfan1** [comment]
8mb

**Comment by Dimtar** [comment]
Is it possible you're being 24 hour banned? How long did your initial cache build take?

**Comment by cpiscos** [comment]
The 5.0.0 release build caused plex to hang on scan when creating a new library. Using 5.0.0-beta.1499930518 that @cardinalfan1 mentioned works alright though and quickly scanned through my libraries.

It'd be nice if we had a complete changelog between beta versions.

**Comment by cardinalfan1** [comment]
@Dimtar Don't think it's a ban because I can immediately switch to the 5.0.0-beta.1499930518 build and it will build cache file/work correctly

**Comment by Dimtar** [comment]
I'll give it a try as well and report back.

**Comment by Dimtar** [comment]
Can confirm, switching to 5.0.0-beta.1499930518 means things work fine.

**Comment by syaifulnizamyahya** [comment]
Can confirm that latest stable release worked for me. The only problem I have is when I didnt delete the old version cache file. I also delete my config file so that I can generate new config.

**Comment by cardinalfan1** [comment]
Tried rebuilding from source, doesn't seem to help

**Comment by Dimtar** [comment]
The stable works for me but only for a little while, like a scan starts very fast and then falls off to nothing and I have to force close everything and unmount manually. Maybe is there a switch to turn up the amount of memory or something it uses? Is it running out of memory maybe and then stalling?

**Comment by dany20mh** [comment]
@dimtar

You can set max-chunk in lower amount which that helps you use less memory, default it 10

**Comment by cardinalfan1** [comment]
Figured out the issue. Plexdrive was setting the following settings to zero by default:
> --chunk-check-threads int
> --chunk-load-ahead int
> --chunk-load-threads int
I just manually set them to the default options in the command line parameters, which resoved the issue. I am closing this issue, but for future reference for anyone... Plexdrive may automatically set the options for some of these things on a virtual machine (which I have), so you just have to set them manually.

**Comment by dany20mh** [comment]
@cardinalfan1 
The reason for setting it automatic is the get best result Nasr on the system core that you have, but some people like you when they use virtual machine, that don’t report correct amount of core and they get into the problem.

For later on, always use `./plexdrive -h` and that will show you all the default setting.
