### ISSUE TITLE
416 error

### ISSUE THREAD

**Issue by jxer** [dweidenfeld/plexdrive#226]
any help 5.0.0

`[PLEXDRIVE] [2017-08-06 22:33] DEBUG  : Request
----------
&{GET https://www.googleapis.com/drive/v3/files/0B7b3VlF8exkfNnotMDdnY2ItU28?alt=media HTTP/1.1 1 1 map[Range:[bytes=104857600-115343360]] <nil> <nil> 0 [] false www.googleapis.com map[] map[] <nil> map[]   <nil> <nil> <nil> <nil>}
----------

[PLEXDRIVE] [2017-08-06 22:33] DEBUG  : Response
----------
&{416 Requested Range Not Satisfiable 416 HTTP/2.0 2 0 map[X-Guploader-Uploadid:[AEnB2UrRQOCQhFa0ZZEhWQ065vAsZTPVNVI3Uxkj9ynCq1hj0JY8-XJTe7E12YWJIZzio0f4Yedj8hfGhKJhuqVVZGjyYq5XFw] Expires:[Mon, 07 Aug 2017 02:33:21 GMT] Server:[UploadServer] Alt-Svc:[quic=":443"; ma=2592000; v="39,38,37,36,35"] Content-Range:[bytes */104857600] Vary:[Origin X-Origin] Content-Type:[application/json; charset=UTF-8] Date:[Mon, 07 Aug 2017 02:33:21 GMT] Cache-Control:[private, max-age=0] Content-Length:[225]] 0xc4638b03a0 225 [] false false map[] 0xc47ef70600 0xc420398bb0}
`

**Comment by jxer** [comment]
https://pastebin.com/6AFrmwEm

can't get git hub to format correctly

**Comment by zenjabba** [comment]
means google couldn't get the block you were looking for. Basically something broke on googles side.

**Comment by jxer** [comment]
its causing plex to crash with a error, anything i can do?

**Comment by zenjabba** [comment]
nope, it's a google problem. 400 range errors are server problems, 500 are client.

**Comment by jxer** [comment]
ok i was looking at https://github.com/dweidenfeld/plexdrive/issues/121

he indicated it should not occur anymore, so i wasn't sure.

is this a common thing?

**Comment by zenjabba** [comment]
there is nothing you can do about it, google couldn't get the object you asked for.. is it common, nope does it happen sure... what the system should do is request it again but when you're streaming video it means it has to stop... not sure what else anybody can do if google isn't give you the part you requested.

**Comment by jxer** [comment]
ok ty
