### ISSUE TITLE
Wrong Client

### ISSUE THREAD

**Issue by alternativesurfer** [dweidenfeld/plexdrive#227]
I input bad client info when setting up PlexDrive and now cannot find a way to get past the "authorization code" screen.
I've deleted the app and all folders I could find referencing PlexDrive, re-downloaded, however when running PLexdrive it drops me right back into the "paste the auth code" step of setup, rather than letting me start over.

Any help would be greatly appreciated!
Thanks!

**Comment by dany20mh** [comment]
So run the app with only -h command and that shows your config folder, and then delete that folder and you can setup the whole thing again.

**Comment by alternativesurfer** [comment]
I don't think -h works in PlexDrive5, as it didn't do anything for me.
But that did give me the idea of specifying a new directory for Config which worked.
Thank you!

**Comment by dany20mh** [comment]
You have to use it like `./plexdrive -h` and that will show you the default value and all the command
