### ISSUE TITLE
Plexdrive 5.0 -Transport Endpoint not connected

### ISSUE THREAD

**Issue by Jazzman666** [dweidenfeld/plexdrive#229]
Hi 

Started with a new fresh ubuntu server and its updated.

Following steps has been used to install:
screen -d -R home
wget https://github.com/dweidenfeld/plexdrive/releases/download/5.0.0/plexdrive-linux-amd64
mv plexdrive-linux-amd64 /usr/bin/plexdrive
chmod +x /usr/bin/plexdrive
mkdir pdrive

Mounting the drive:
plexdrive mount -o allow_other --max-chunks=20000 -v 2 pdrive/

It does start to mount and process the first cache completed.
Some time after i get the error: Transpoint Endpoint is not connected.

I have used fusermount -u pdrive
then remounted again, seems to work for some time then the samme issue occurs.

I do have a large libary with content, dont know if that is making the plexdrive to crash.

Anyways apologize for my bad english in advance.

**Comment by dweidenfeld** [comment]
Hm... do you have a full error log? Please mount again with `-v3` and provide the logs.
I would also recommend running plexdrive as systemd service or something like that. Screen is not the "most fault tolerant" solution ;)

**Comment by Jazzman666** [comment]
I have mounted the plexdrive now with v-3 and where can i find the logs :D?

Is this the guide i need to follow if i wish to setup plexdrive as systemd service?
https://github.com/dweidenfeld/plexdrive/blob/master/TUTORIAL.md

Once again thank you for the fast reply.

**Comment by dweidenfeld** [comment]
Yep the tutorial is a good start, but maybe you have to adjust the scripts to your environment. The logs are just printed to stdout so there is no log file or something like that.

If you setup plexdrive with the tutorial you should find the log files with:
```
journalctl -u plexdrive
```

**Comment by Jazzman666** [comment]
Seems it stopped working again.
I will take a closer look at the guide, and adapt it to my current setup.

Seems it stopped working again.
I got this when i connected to the server:

created by net/http.(*http2Transport).newClientConn
        /usr/local/go/src/net/http/h2_bundle.go:5892 +0x728

goroutine 48367 [chan receive]:
github.com/dweidenfeld/plexdrive/mount.(*Object).Read(0xcac15b0810, 0x7f30b3774f68, 0xce1c992540, 0xd1af3fd420, 0xc71416c8a0, 0x1001, 0x0)
        /tmp/build/36d0981b/go/src/github.com/dweidenfeld/plexdrive/mount/mount.go:237 +0xec
bazil.org/fuse/fs.(*Server).handleRequest(0xc4202b8000, 0x7f30b3774f68, 0xce1c992540, 0x9e71e0, 0xcac15b0810, 0xce1c992480, 0x9ebe60, 0xd1af3fd420, 0xc42052bef8, 0xc42002fe80, ...)
        /tmp/build/36d0981b/go/src/bazil.org/fuse/fs/serve.go:1249 +0x998
bazil.org/fuse/fs.(*Server).serve(0xc4202b8000, 0x9ebe60, 0xd1af3fd420)
        /tmp/build/36d0981b/go/src/bazil.org/fuse/fs/serve.go:878 +0x495
bazil.org/fuse/fs.(*Server).Serve.func1(0xc4202b8000, 0x9ebe60, 0xd1af3fd420)
        /tmp/build/36d0981b/go/src/bazil.org/fuse/fs/serve.go:425 +0x6e
created by bazil.org/fuse/fs.(*Server).Serve
        /tmp/build/36d0981b/go/src/bazil.org/fuse/fs/serve.go:426 +0x3c4

Dont know if this helps out.

**Comment by zmike808** [comment]
I'm going to guess you ran out of RAM? Try changing your max chunks from 20000 to default, and see if it's any better.

**Comment by Jazzman666** [comment]
That is possible 😃
I tried with changing max chunks to default. 
The same issue still occured. 

I have reinstalled Ubuntu 16.04 and will try it again.

**Comment by zmike808** [comment]
@Jazzman666 How long does it take the crash to occur? Is it within a few minutes, or does it occur at completely random intervals? You said in your initial post that it was sometime after, but it would help to know how long it takes. Also, if you have the disk space try using -v4 to get maximum verbosity, but be warned your log file will fill up fairly quick.

**Comment by Jazzman666** [comment]
@zmike808 
The crash occurs random at times anything between 5 min - 30 min.
But i think the issue is resolved.
On my ubuntu installation i had Quickbox.io installed and ran the plexdrive setup with a user i created for the quickbox web interface.

I ran a fresh install of ubuntu 16.04 and ran the setup for now its running smooth.

Thanks all for the input and closing this issue.
