### ISSUE TITLE
Google Cloud Action Required

### ISSUE THREAD

**Issue by rhummelmose** [dweidenfeld/plexdrive#231]
Hi!

I've been using your software for some time now, thank you.

I just received the following e-mail from Google:

> Hello Google Cloud Platform/APIs Developer,
> 
> We've recently detected activity on your Google Cloud Platform/APIs project ID X that appears to violate our Terms of Service. Please take a moment to review the Google Cloud Platform Terms of Service or the applicable Terms of Service for the specific Google API you are using.
> 
> It appears that your project is committing denial of service attacks.To protect our users, we have set an outbound bandwidth rate limit on your project.
> 
> We will suspend your project in 3 days unless you correct the problem by ensuring your project traffic directed at third-parties is expected, and that your project has not been compromised. Visit the Google Developers Console at https://console.developers.google.com for detailed instructions.
> 
> If your project begins to seriously interfere with the service or other users, we may be forced to suspend it before the 3-day period is up. Responding quickly is the best way to keep this from happening.

Any ideas? I only have the Google Drive API enabled.

**Comment by dweidenfeld** [comment]
What settings do you use for plexdrive?
What are you doing with plexdrive, that could occur such a high load?

**Comment by rhummelmose** [comment]
@dweidenfeld I only use it for Plex. There are periode watching most of the time, the max nummer of streams ever is 7.

I use the default settings for plexdrive.

**Comment by rhummelmose** [comment]
This is how the usage looks:
<img width="2032" alt="skaermbillede 2017-08-16 14 39 02" src="https://user-images.githubusercontent.com/620878/29363556-c642f140-8290-11e7-99e5-79b851d1a571.png">

**Comment by dweidenfeld** [comment]
Looks very... bored... 
What are your quota limits?

**Comment by rchiechi** [comment]
Same here, only I have significantly less traffic. The only similarity is a spike in errors on Aug 14. (I can't take a screenshot at the moment.)

**Comment by rhummelmose** [comment]
@dweidenfeld see below:
<img width="2032" alt="skaermbillede 2017-08-16 20 42 27" src="https://user-images.githubusercontent.com/620878/29379659-74ef481a-82c3-11e7-86dd-603065e45060.png">

**Comment by rhummelmose** [comment]
Probably related: https://forum.rclone.org/t/warning-for-google-developer-account/3591

**Comment by M0V3** [comment]
Received the same email, I'm still on plexdrive 4.0.0.


Usage:  
![DRK-RAT.RUN - Screenshot hosting](https://drk-rat.run/img/148VglljAMrwxh.png)  
Quota:  
![DRK-RAT.RUN - Screenshot hosting](https://drk-rat.run/img/882TvTegN2ksCD.png)

**Comment by ratherDashing** [comment]
I got the same e-mail as well, updated plexdrive to 5 and plex to 1.8 yesterday.  Maybe downgrade to plexdrive 4?

**Comment by emreuenal** [comment]
@ratherDashing I am using v4 and got the same email

**Comment by ItsCompletelyYourFault** [comment]
Same here, v4 and this email.

Far below any limit, 8msg/s, max 10k per day.
Error spikes at 11. Aug.
I don't see an actual traffic limit in means of GB, and assume to use <4GB/day.

I wonder whether something is wrong with plexdrive (like earlier this year a similiar Amazon tool was bleeding auth tokens) and whether they start banning specially plexdrive - or mount tools in general... 

Sad. Google and Plexdrive had been working like a charm.

**Comment by flpotro** [comment]
Same here, almost 0 traffic... and I got this email too

**Comment by jonfinley** [comment]
Not having same issue but figured I would share my usage: v4
<img width="1331" alt="screen shot 2017-08-16 at 5 39 12 pm" src="https://user-images.githubusercontent.com/23283167/29386506-2fba0a8c-82aa-11e7-8a9a-626950294ae5.png">

**Comment by dany20mh** [comment]
Out of curiosity, what’s the os you guys use and what the system that you have?
Is it just PlexDrive by itself?
Is it connected to other stuff (such as rclone, unionfs, ...)
Is your API shared with other app?

**Comment by flpotro** [comment]
@dany20mh Ubuntu, just Plexdrive, no other stuff, the api is not shared with other app

**Comment by gorkarevilla** [comment]
Same here with almost any traffic and v5. Any ideas?

**Comment by SuperPants321** [comment]
I just got the same email. Plexdrive 3.0.0, Ubuntu 14.04. Nothing else using the same API.

**Comment by Keeperjoey** [comment]
Is everyone that got the mail NA? It seems that way

**Comment by gorkarevilla** [comment]
I'm not NA... So that is not the problem IMO.

**Comment by dany20mh** [comment]
If I ask, it's because I don't know most of you guys keep your stuff encrypted and using rclone mount and unionfs with Linux, so I'm not sure if it's just PlexDrive, or it's they way you been using it.

**Comment by SuperPants321** [comment]
I am using unionfs, but not encrypted.

**Comment by Keeperjoey** [comment]
Who of you is using rclone mount ?

**Comment by M0V3** [comment]
Im using rclone mount on a second machine for uploading.

**Comment by rchiechi** [comment]
I just got an email saying everything is fine and apologizing for the misunderstanding... A bug on their end maybe?

**Comment by M0V3** [comment]
![DRK-RAT.RUN - Screenshot hosting](https://drk-rat.run/img/4JCOw3AvyMmACF.png)

Yup, received that too.  Seems like this was an error on googles end.

**Comment by rhummelmose** [comment]
Same here :) Sorry for the inconvenience @dweidenfeld

**Comment by dweidenfeld** [comment]
:D ... so.. Plexdrive just know the Google policies better than the Google employees ;) :D
