### ISSUE TITLE
-clear-chunk-max-size in version 5.0?

### ISSUE THREAD

**Issue by silvether** [dweidenfeld/plexdrive#232]
Is there any replacement for `-clear-chunk-max-size` in version 5.0?

**Comment by ajkis** [comment]
No, since chunks are not stored on disk anymore, they just reside in memory.

**Comment by silvether** [comment]
It would be nice to have a feature to direct this to disk. It was extremely useful to be able to hit a cached version of an entire file a whole day later, without hitting Google. I may have to downgrade to 4.0 to get this working again. Also, how long is the file/folder hierarchy cached for before it has to grab it all from Google again?

**Comment by dweidenfeld** [comment]
The folder structure is cached by the changes API provided by Google. There is no cache invalidation mechanism.

Chunking to disk will come back in the future, but I cannot say when ;)
