### ISSUE TITLE
Request - No need Client ID and Client Secret

### ISSUE THREAD

**Issue by thibrex** [dweidenfeld/plexdrive#24]
Hey, 
With my drive account I can't create my own client id and client secret. Is it possible to do like rclone with a api shared to every users if we can't create own api?
Thanks!

**Comment by zenjabba** [comment]
You can create one with just your regular gmail account. The Client ID and Secret do not need to be the same account.

**Comment by kilabyte** [comment]
If you sign up for another Google account and use that for the api it should work. The authorization uses the api for reporting/tracking but you login to your drive account after the fact with the link provided by plexdrive. Then after the link you'll login to your drive account and get back a token you put in the console for the api to access. I use my personal drive account to mount and I have a business account that has all my aps from all my apps.

**Comment by thibrex** [comment]
Ok thank you It works! :)

**Comment by zenjabba** [comment]
Glad it helped. Enjoy.
