### ISSUE TITLE
WARNING: Wrong status code 503

### ISSUE THREAD

**Issue by Nottt** [dweidenfeld/plexdrive#240]
I keep seeing this errors? 

Like this :

WARNING: Wrong status code 503 for &{0BwLQ63MvDonpc1JucVJjRExLSGM xxxx.mkv

My mount options are `ExecStart=/usr/sbin/plexdrive mount -c /root/plexdrive --cache-file=/root/plexdrive/cache.bolt -v 2 -o allow_other --max-chunks=500 --chunk-load-ahead=250 /mnt/plexdrive`

My system has 2 CPU cores and 7.5 GB of ram.

**Comment by dweidenfeld** [comment]
Google Drive has had huge problems the last days and 503 means that the Google Drive services was not available. Maybe you're one of the guys that still have those problems... we can just wait for Google to fix the issues.

This is nothing plexdrive can fix ;)

**Comment by Nottt** [comment]
I'm still seeing this with some files and also error 500 sometimes :/
