### ISSUE TITLE
5.0 Mac version is missed?

### ISSUE THREAD

**Issue by carlosrovira** [dweidenfeld/plexdrive#245]
Hi, can't see a link for the Mac version of 5.0 (something like:  https://github.com/dweidenfeld/plexdrive/releases/download/5.0.0/plexdrive-darwin-amd64)

beta version exist but not release, or I'm missing something

Thanks!

**Comment by dweidenfeld** [comment]
Please ask in the slack channel. I cannot compile a Mac version myself, because there had been many issues with OpenSSL whenever I compiled a Mac version on Linux ;)

But there is a guy called dany20 .. he compiled a mac version himself ;)

**Comment by carlosrovira** [comment]
Thanks Dominik,

I get yesterday the build from Dany. Very useful thanks.

Could you consider to accept to upload his build with the rest of releases? it would be of great help for people like me on macOs, and will benefit your project.

Thanks in advance!

Carlos

**Comment by calabro** [comment]
I would like the MacOS version please.

**Comment by 2600box** [comment]
here is dany20 compiled version from slack:

https://slack-files.com/T5EP2Q1GA-F7AFL8EH2-fc7afbac5a

**Comment by calabro** [comment]
thank you :)

**Comment by carlosrovira** [comment]
Thanks 2600box, but I'm talking about something more sustainable over time ;) a collaboration to bring macOs version to the downloads page with every release. That would be awesome! :)

Thanks

**Comment by zenjabba** [comment]
This is the sustainable model, because MacOS isn’t able to be built automatically.

**Comment by dweidenfeld** [comment]
Well. The OpenSSL implementation in Go seems not to be cross-compilable. So there is no general solution for it right now.

I am working on a Rust version of plexdrive (which should be faster with better memory usage etc.) this will/should be able to be cross compiled. But I don't have the time to work on it right now. I think I will get it working in december (but don't pin me down to that) ;)
