### ISSUE TITLE
Unable to download from plexdrive mount

### ISSUE THREAD

**Issue by mikeferr** [dweidenfeld/plexdrive#249]
Wondering if someone could help me get this working on Ubuntu 16.04.2 LTS (vultr vps).

I entered the following:

wget https://github.com/dweidenfeld/plexdrive/releases/download/5.0.0/plexdrive-linux-amd64

mv plexdrive-linux-amd64 plexdrive
mv plexdrive /usr/bin/

chown root:root /usr/bin/plexdrive
chmod a+x /usr/bin/plexdrive
chmod 777 /usr/bin/plexdrive

copied my cache.bolt file from backup

plexdrive mount -v 4 -o allow_other /mnt/plexdrive

entered my client ID/Secret

I can see my files and browse the mount but cant download anything. Any idea what's wrong?

`[USR/BIN/PLEXDRIVE] [2017-09-30 00:54] TRACE  : FUSE <- Open [ID=0x46 Node=0x4 Uid=0 Gid=0 Pid=1882] dir=false fl=OpenReadOnly
[USR/BIN/PLEXDRIVE] [2017-09-30 00:54] TRACE  : FUSE -> [ID=0x46] Open 0x4 fl=0
[USR/BIN/PLEXDRIVE] [2017-09-30 00:54] TRACE  : FUSE <- Read [ID=0x47 Node=0x4 Uid=0 Gid=0 Pid=1882] 0x4 4096 @0x0 dir=false fl=0 lock=0 ffl=OpenReadOnly`

**Comment by bassrock** [comment]
Seeing the same issue as well.

**Comment by felixbuenemann** [comment]
I'm seeing the same when using 5.0.0 on Ubuntu Xenial, all ready from the drive immediately hang:

```
[PLEXDRIVE] [2017-10-04 23:48] TRACE  : FUSE -> [ID=0x3d] Lookup 0x7 gen=2 valid=1m0s attr={valid=1m0s ino=4455726659688538060 size=5710690 mode=-rw-r--r--}
[PLEXDRIVE] [2017-10-04 23:48] TRACE  : FUSE <- Open [ID=0x3e Node=0x7 Uid=0 Gid=0 Pid=1876] dir=false fl=OpenReadOnly
[PLEXDRIVE] [2017-10-04 23:48] TRACE  : FUSE -> [ID=0x3e] Open 0x1 fl=0
[PLEXDRIVE] [2017-10-04 23:48] TRACE  : FUSE <- Read [ID=0x3f Node=0x7 Uid=0 Gid=0 Pid=1876] 0x1 4096 @0x0 dir=false fl=0 lock=0 ffl=OpenReadOnly
```

I've mounted the drive with `-o allow_other,read_only` and the problem happens both when mounting as a user and when mounting as root.

**Comment by felixbuenemann** [comment]
Problem happens with both stock fuse 2.9.4 and 2.9.7 backport packages on xenial amd64. I also tried recompiling plexdrive with go-1.8 on the same system with the same result.

**Comment by animosity22** [comment]
No issues on:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

```
go version
go version go1.8.3 linux/amd64
```

```
/usr/bin/unionfs-fuse -V
unionfs-fuse version: 1.0
FUSE library version: 2.9.4
fusermount version: 2.9.4
using FUSE kernel interface version 7.19
```

Been running for months with no issues.

**Comment by felixbuenemann** [comment]
I'll have to upgrade the system to more than 512 MB RAM and see if that fixes the problem. I noticed that under normal usage on my Mac, were plexdrive works fine is uses about 500 MB RAM when the chunks cache is full with default settings, so that would work.

I'm not sure that's the issue though, because I was trying to copy a single 5 MB file directly after mounting, so the cache should be empty.

**Comment by animosity22** [comment]
I can't imagine trying to run plexdrive with 512MB of ram as it uses memory to store the chunks let alone streaming an actual 500MB-20GB movie.

My 'plex' usage hits anywhere from 500MB to ~GB with people streaming and plexdrive jumps anywhere around 300MB to a GB or so depending on how much I'm streaming from my GD.

**Comment by felixbuenemann** [comment]
I just tried with memory on the VM bumped to 1 GB with the same result: Trying to read immediately hangs the reading process.

Memory usage was 78 MB of 1 GB so it is definitely not related to an out-of-memory condition.

**Comment by animosity22** [comment]
I don't use my plexdrive mount for anything else than plex and doing stuff.

I use rclone to pload and plex to play. Never tried to copy or read a file.

What's in the logs? Are you seeing the cache process finished as well?

I see something like this in my logs on startup:

```
[HOME/FELIX/SCRIPTS/PLEXDRIVE] [2017-10-06 12:05] INFO   : Mounting path /GD
[HOME/FELIX/SCRIPTS/PLEXDRIVE] [2017-10-06 12:05] INFO   : First cache build process started...
[HOME/FELIX/SCRIPTS/PLEXDRIVE] [2017-10-06 12:05] INFO   : Processed 4 items / deleted 4 items / updated 0 items
[HOME/FELIX/SCRIPTS/PLEXDRIVE] [2017-10-06 12:05] INFO   : First cache build process finished!
```
Are you sure you account isn't API banned? That would hang a download too.

**Comment by felixbuenemann** [comment]
Copying with rclone works fine.

I think this might be a thread deadlock, because it started working after I upgraded the VM to 2 CPUs.

To summarize:

* 1 CPU / 512 MB RAM: read hangs
* 1 CPU / 1 GB RAM: read hangs
* 2 CPU / 2 GB RAM: works

**Comment by felixbuenemann** [comment]
I think it's actually a far more trivial bug:

https://github.com/dweidenfeld/plexdrive/blob/7898e4f82b8446d5199c37a79693786ff7204e09/main.go#L45

```go
argChunkLoadAhead := flag.Int("chunk-load-ahead", runtime.NumCPU()-1, "The number of chunks that should be read ahead")
```

So Load-Ahead with 1 CPU will be zero chunks …

**Comment by animosity22** [comment]
Oof. Who uses 1 CPU these days? :)

Yeah, I have 8 cores going on.

**Comment by felixbuenemann** [comment]
For VMs that is pretty common.

**Comment by felixbuenemann** [comment]
There are also several options set to `runtime.NumCPU()/2` which is 0 in integer math.

**Comment by animosity22** [comment]
Nice find too!

**Comment by felixbuenemann** [comment]
OK; I'll try to come up with a PR to fix this.

**Comment by felixbuenemann** [comment]
With the changes from PR #250 Plexdrive now works with 1 CPU / 1 GB RAM.

512 MB will probably only work with disk caching (@geoah is working on that).

**Comment by bassrock** [comment]
@felixbuenemann is there a branch or PR for the disk caching to look at?

**Comment by felixbuenemann** [comment]
@bassrock It is in [geoah/plexdrive@master](https://github.com/geoah/plexdrive). It currently has a bug with deleting chunks, but geoah wanted to work on that this weekend.

**Comment by geoah** [comment]
Just FYI: Disk caching is very slow on magnetic disks and especially systems with high i/o.
Works pretty ok on systems with local SSDs but I haven't tested it on DO, AWS with EBS volumes, etc.

Deletion has been fixed on but I have only tested this on bare metal and only during development etc.

**Comment by blt7cd** [comment]
@felixbuenemann Can you help me out with renaming the user directory?  What user directory? I git cloned @geoah fork but don't see what I need to rename.  The build does indeed fail though. Sorry, I'm not super familiar with compiling and building on linux.

**Comment by felixbuenemann** [comment]
Well I renamed the geoah folder in `$GOPATH/src/github.com` to `dweidenfeld` so the imports are working. However I'm no longer using this port because disk caching performance was pretty bad and I've since upgraded the memory on my VM to 1 GB which works fine with in memory caching.

**Comment by lowprofileusername** [comment]
@felixbuenemann  How can I use your fix is there a bin that I can download? Thanks. I'm currently experiencing same issue with 1cpu vm under debian 9.
Thanks. I'm new to github. not familiar with it. sorry for that.

**Comment by felixbuenemann** [comment]
@lowprofileusername You can either build it yourself:

```sh
go get -d -u github.com/dweidenfeld/plexdrive
cd ${GOPATH:-$HOME/go}/src/github.com/dweidenfeld/plexdrive
curl -fsL https://github.com/dweidenfeld/plexdrive/pull/250.diff | patch -Np1
go install
cp  ${GOPATH:-$HOME/go}/bin/plexdrive /usr/local/bin/
```

or download a [plexdrive binary with the patch for amd64-linux from my dropbox](https://www.dropbox.com/s/tm508jc3be82irn/plexdrive.gz?dl=1), `gunzip` it and move it to `/usr/local/bin`.

If you have a working go environment I recommend the first optiona, as it's better than running binaries obtained from random people on the internet. 😃

**Comment by lowprofileusername** [comment]
Thanks for your help. I will try to build one myself:P

**Comment by felixbuenemann** [comment]
Since #250 has been merged a simple `go get -u github.com/dweidenfeld/plexdrive` should now suffice.
