### ISSUE TITLE
Mount Specified Folder

### ISSUE THREAD

**Issue by kanenses** [dweidenfeld/plexdrive#251]
Hello,

I no that is not a issue, but how can I mount plexdrive to a specified folder and not to root of drive?

Thank you

**Comment by dweidenfeld** [comment]
Not possible right now. This has been discussed multiple times

**Comment by jant90** [comment]
Unless I understood the question wrong, isn't this possible with the `--root-node-id` option? Just open the desired folder in the webinterface of Google Drive, copy the folder ID from the address bar and use that with the `--root-node-id` option when mounting.

**Comment by ChrisColotti** [comment]
This would be super useful.  I keep all media in one folder but the overall drive is large so it takes a long time to rebuild a cache if I need to do so.
