### ISSUE TITLE
Version for windows

### ISSUE THREAD

**Issue by monelivorno** [dweidenfeld/plexdrive#253]
Meanwhile I want to thank the author and all his staff who spend their time creating and helping. Thank you very much.

I would like to ask if there is a chance that you will create a version for Windows?
If technically possible, I'm sure it will attract a lot of people who for other reasons can not go to linux but who would like to take advantage of the power of the cloud. Currently there are no programs that ban the ban eg from GDrive, there are paid programs but do not avoid 100% ban.
I'm sure the same people who pay for these programs are not always effective, would like to pay a program that really works like Plexdrive.
What do you think?

**Comment by dweidenfeld** [comment]
Windows doesn't support fuse or other filesystem wrappers that are implemented in go or rust. Sorry
