### ISSUE TITLE
High bandwidth usage every minute or so

### ISSUE THREAD

**Issue by kade-robertson** [dweidenfeld/plexdrive#255]
Here's a NetHogs screenshot using the majority of my 100Mbps connection:

![8.7MB/s](https://i.imgur.com/BEhs9al.png)

It seems to spike like this for 10-30s every minute or so, what exactly is it doing? I've only got a  1.4TB encrypted drive and the cache was built already (cache.bolt is around 24MB). Just wondering if it's normal behaviour when the drive content isn't changing. There's also nothing accessing it, no Plex users or anything.

**Comment by kade-robertson** [comment]
I tried setting the `--refresh-interval` setting and it did nothing. Still happens every minute.

**Comment by animosity22** [comment]
What's using the bandwidth? Do you have a plex scan or something updating your library?

**Comment by kade-robertson** [comment]
Nothing is. Plex scans are done by the hour only, nothing else is updating it.

**Comment by animosity22** [comment]
Turn up the logging by using -v 2 or maybe even -v 3 to see what's hitting the files and you might be able to track it down via that route.

It's not normal behavior and something is causing the IO.

**Comment by kade-robertson** [comment]
I've got it on -v 3, here's a gist of what's happening: https://gist.github.com/kade-robertson/f92b16a1b5bd33288d877d835d9de58d

Again, there's no way this could be from new files because there hasn't been any updates to the drive for over 2 hours.

**Comment by animosity22** [comment]
New files don't cause old ones to be downloaded. You'd see only things like this for file updates:

```
[HOME/FELIX/SCRIPTS/PLEXDRIVE] [2017-10-25 04:03] INFO   : Processed 4 items / deleted 0 items / updated 4 items
[HOME/FELIX/SCRIPTS/PLEXDRIVE] [2017-10-25 04:05] INFO   : Processed 2 items / deleted 0 items / updated 2 items
[HOME/FELIX/SCRIPTS/PLEXDRIVE] [2017-10-25 04:06] INFO   : Processed 2 items / deleted 0 items / updated 2 items
[HOME/FELIX/SCRIPTS/PLEXDRIVE] [2017-10-25 04:08] INFO   : Processed 20 items / deleted 0 items / updated 20 items
[HOME/FELIX/SCRIPTS/PLEXDRIVE] [2017-10-25 04:09] INFO   : Processed 6 items / deleted 0 items / updated 6 items
```

Since all your stuff is encrypted, it's hard to guess what files are being hit and causing it. Are you using anything else that could be doing scans? Sonarr? Radarr? Any other scheduled scripts? Users that might be kicking a scan off? Plex Media Analysis?

**Comment by kade-robertson** [comment]
There aren't any extra scripts and aside from the scheduled scans of Plex (which aren't on that short of an interval). I did look for some info lines which do indicated that the data is actually being processed at an interval I set, and presumably only when stuff is actually updating since the lines didn't show every 10 minutes.

**Comment by kade-robertson** [comment]
I just checked one of the most recent chunk IDs to see what it was downloading, it's a file that was uploaded a week ago. Why would it be getting old files? It seems to be downloading chunks of a mix of both.

**Comment by animosity22** [comment]
In my setup, I use rclone over an encrypted plexdrive mount and if you can check using lsof what process is hitting the files, that might help:

```
root@plex:~# lsof /TV
COMMAND     PID USER   FD   TYPE DEVICE   SIZE/OFF   NODE NAME
Plex\x20M 15191 plex   95r   REG   0,49 1646669964 225869 /TV/The Wire/The.Wire.S02E10.HDTV-720p.mkv
root@plex:~# lsof /GD
COMMAND  PID  USER   FD   TYPE DEVICE   SIZE/OFF                 NODE NAME
rclone  4350 felix    6r   REG   0,46 1647072028 15653234634434416881 /GD/smu5ej34ujbdoip1cm3mlk92q4/da69he7g480he7l5n0jeak1fo8/j8el86fm8m6mvkslfcau6aq67vonj5326tel04c6p03155s6qvlg
root@plex:~#
```

In my example, I'm watching a show from my GD and I can see it's plex requesting the file.

**Comment by kade-robertson** [comment]
Hm, I am getting that Plex is accessing a file, but nobody is playing it and that particular library is NEVER scanned unless done manually.. I disabled all of the automatic stuff I could find, any way of diagnosing what portion of Plex is doing it?

**Comment by animosity22** [comment]
plexdrive just mounts and really doesn't do anything but scan for changes which is minimal at best. You can see in the plexdrive logs that something is causing the file to be downloaded. I'd guess analysis, but if you have all that turned off, it's gotta be something in there.

You can check the plex logs as well during the scans to see whats going on:

```
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Scanner.log
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/Plex Media Server.log
```

Usually the scanner log and server logs are the places that I start. I'd still validate it's plex by using the lsof commands to be sure.

**Comment by kade-robertson** [comment]
I think I figured it out, thank you for all your help!

To anyone wondering, it seems to have been caused by Sub-Zero, a subtitle agent. It seems it schedules itself to rescan all "recent" media files to see if better subtitles exist. I just ended up deleting mine, but presumably if you set it up to only scan when media is first added it would work too.
