### ISSUE TITLE
MacOS High Sierra build

### ISSUE THREAD

**Issue by Azuraxe** [dweidenfeld/plexdrive#260]
Hi,
Will there be a MacOS high sierra build of 5.0?
All the code is there, just no download link for MacOS under releases?
Thanks.

**Comment by spigots** [comment]
Here's 5.0 compiled on HS

https://mega.nz/#!ks1gDCab!EgP6Bsmlf38KP3CugK3YYfwQyC3JlLJI31Elcv5D_to

**Comment by Azuraxe** [comment]
Absolute legend!

**Comment by dweidenfeld** [comment]
Just for you to notice: I cannot build OSX releases myself. They start, but will fail with strange errors, so please use Slack for OSX releases (some guys there build the code themselves).
