### ISSUE TITLE
how to replace -t usage?

### ISSUE THREAD

**Issue by aegie** [dweidenfeld/plexdrive#262]
Well, I've used before "-t" to point to the temp in my /home partition, but this no longer works.
   /usr/local/bin/plexdrive mount $MPOINT \
                       -o allow_other \
                       -t /home/plex/temp \
                       -v 2 &>>$LOGFILE &
I've tried to find a replacement, but couldn't. 
Could you please point me into the right direction?
Thank you!

**Comment by kuarthepirat** [comment]
The current stable version of plexdrive no longer has the -t option because all chunks are kept in the RAM. Therefor it is no longer necessary to point it to a temp-directory.

**Comment by aegie** [comment]
Oh, thanks for the explanation! All good then!
