### ISSUE TITLE
Panic On No Home Directory

### ISSUE THREAD

**Issue by bassrock** [dweidenfeld/plexdrive#263]
I am currently trying to start plexdrive on a FreeNAS startup script. However at the point the script runs no home drive is set on FreeNAS. It seems the following line is causing the application to panic: https://github.com/dweidenfeld/plexdrive/blob/208b3e37022c8cf07047e3818b9ab486eaaf52ee/main.go#L34

Is there a reason the application panics here instead of offering this as a configuration parameter?

**Comment by bassrock** [comment]
I have fixed this and submitted a pull request.

**Comment by KennyVB** [comment]
hmm i got this error as of today, is it merged yet?

**Comment by felixbuenemann** [comment]
No and as far as I can see there never was a pull request to get this fixed.

**Comment by bassrock** [comment]
@felixbuenemann The pull request is here. https://github.com/dweidenfeld/plexdrive/pull/268
