### ISSUE TITLE
Plexdrive in windows

### ISSUE THREAD

**Issue by j0shii** [dweidenfeld/plexdrive#265]
Would it be possible to compile it for Windows?
as "go" is multiplatform and although fuse is not compatible, with winfsp it can be emulated, as rclone does some time ago and is currently implementing cache.
Sorry for my bad English.

**Comment by Admin9705** [comment]
Someone would have to make it.  If you ever did, you would be world as a world wide hero!

**Comment by bassrock** [comment]
For windows try, drive file stream. Supposed to be pretty solid for this use there.

**Comment by Loomaanaatii** [comment]
File stream is extremely laggy when first downloading files for streaming (buffering).

**Comment by Admin9705** [comment]
@bassrock , file stream is not a good choice. If plex scans it, you'll get nailed with the API ban.

**Comment by syaifulnizamyahya** [comment]
Docker maybe?

**Comment by syaifulnizamyahya** [comment]
Rclone is a good candidate for mounting gdrive on windows. But be careful as you might get ban when do plex scan.

**Comment by dweidenfeld** [comment]
You can use rclone if you want. 
I am already planning a platform independent version of plexdrive for all OS, but it is still in a very early alpha phase and not released yet ;)
