### ISSUE TITLE
Streams are buffering

### ISSUE THREAD

**Issue by Azuraxe** [dweidenfeld/plexdrive#269]
Hi,
I had to revert back to Version 4 to get Plexdrive working properly which is fine, but I am having streaming issues with the buffering.

My average file size is around 700mb-1GB, so TV Shows with a bitrate of around 2500 kb/s (HEVC content). I am able to stream directly off Google drive not a problem, however, when it comes to Plexdrive, the stream stops and buffers every 20-30 seconds with the first buffer occurring 5 seconds into the stream.

With an internet speed of 15mbps, I am fully capable of streaming this, however Plex and Plexdrive really struggle with it. I've checked usage stats like CPU and RAM etc, and that's all sitting at a low level. Plex transcoding occurs occasionally as most devices that I stream Plex on support HEVC. 

Does anyone have any ideas to assist with this? I am using the default command line, and haven't adjusted chunk size etc.

Cheers

**Comment by dweidenfeld** [comment]
Please ask your question again in the slack channel. I think you might want to change the default settings and experimenting with it ;)
