### ISSUE TITLE
Error when copy file from plexdrive

### ISSUE THREAD

**Issue by syaifulnizamyahya** [dweidenfeld/plexdrive#270]
I want to copy file on google drive to my pc.

Here are the errors that I get.

https://pastebin.com/gz90Lmm6

Basically repeats of this line

> [0m[34m[USR/SBIN/PLEXDRIVE] [2017-12-05 23:28] DEBUG : Response
> ----------
> &{416 Requested Range Not Satisfiable 416 HTTP/2.0 2 0 map[X-Guploader-Uploadid:[AEnB2UqYp1jLEljcXqhPYuHX-CoeK74QWDRVrfQIKkxS9IEZQ39wmmGLxkKIdSw3KPus6kwPTW4bn9RfihdMw9LViYaqY0rmyqMoeVHWCpdQr7l33CApoXU] Content-Range:[bytes */104857600] Vary:[Origin X-Origin] Date:[Tue, 05 Dec 2017 15:28:01 GMT] Cache-Control:[private, max-age=0] Alt-Svc:[hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=":443"; ma=2592000; v="41,39,38,37,35"] Content-Type:[application/json; charset=UTF-8] Expires:[Tue, 05 Dec 2017 15:28:01 GMT] Content-Length:[225] Server:[UploadServer]] 0xc420362580 225 [] false false map[] 0xc428920200 0xc4204020b0}
> ----------

What happen and what should I do?

**Comment by zmike808** [comment]
Have you tried deleting (renaming) your cache folder and then rebuilding it? Was it originally working and then suddenly you now have these errors? Was this what happened once you finished building your initial cache? 

Hard to provide assistance with just API errors...

**Comment by syaifulnizamyahya** [comment]
Im not aware of those steps needs to be done for trouble shooting. I haven't delete cache folder and rebuilding it. It has been working fine (watching movies) before and now. I get this error when I want to copy file from cloud to my local drive. Tried with windows and linux. Copy operation failed on both and these are the errors I get on both attempt. I will try to rebuild cache and update later.

**Comment by dweidenfeld** [comment]
If this error still occurs after a cache refresh and full rebuild it could be that your file is damaged in Google Drive.
Sometimes when and upload to Google Drive corrupts the file Google Drive thinks the file is e.g. 200mb, but it is actually 199mb because the upload has been interrupted. So the "range is not satisfiable", because plexdrive wants to download 200mb, but only gets 199 ;)

**Comment by syaifulnizamyahya** [comment]
Since the file is zipped, i tried unzipping from plexdrive and it works. It seems that unzip is more tolerance on drive speed but copy does not. probably copy operation time out. Im glad that the file is not corrupted on google side.

**Comment by zmike808** [comment]
Quick question what OS are you using...?

**Comment by syaifulnizamyahya** [comment]
tested download from windows and linux(unraid). unzip from windows(7zip)
