### ISSUE TITLE
Possible windows port using winfsp

### ISSUE THREAD

**Issue by atytel** [dweidenfeld/plexdrive#271]
Is it possible?

**Comment by dweidenfeld** [comment]
Possible yes, but I won't implement it.
A windows/linux/mac version is already in planning. Completeley OS independent. I cannot tell you anything about the schedule ;)

**Comment by atytel** [comment]
any advice for a temp work around then?

**Comment by dweidenfeld** [comment]
Usage of the native Google drive for windows share or rclone ;)... Or a raspberry pi with Linux on it

**Comment by atytel** [comment]
RIP

**Comment by djsecrist** [comment]
Or run Linux in a virtual machine on your Windows machine. Run PlexDrive and share it to your Windows machine via SMB or NFS.
