### ISSUE TITLE
PlexDrive 5.0 and 4k video

### ISSUE THREAD

**Issue by jcrabapple** [dweidenfeld/plexdrive#279]
I have been testing 4k video on my VPS with 8 CPU cores and 12GB RAM and on a dedicated server with 24 CPU cores and 32GB RAM. I am experiencing buffering and sometimes the movie even stops completely. Network connection speeds to both the VPS and dedicated server are fast, I have been having no problem even with high bitrate 1080p video whether direct playing or transcoding. I am trying to play 4k to a TCL 4k HDR Roku TV.
![capture](https://user-images.githubusercontent.com/13261654/35748029-8ff17232-081a-11e8-841e-a7c583dc8c91.PNG)
Above are the details for the movie I am trying to play.

What is happening is that after I start the movie I can watch the cached RAM on my server increase, until it becomes completely used and the movie will begin to buffer or completely stop. I have even tried specifying a cache location on the hard drive, but Plexdrive still uses all of the available RAM.

I can provide any other information necessary.

Any suggestions?

**Comment by jcrabapple** [comment]
I am currently using the following command to mount plexdrive:

sudo /usr/local/bin/plexdrive mount -v 3 --refresh-interval=1m --chunk-check-threads=8 --chunk-load-threads=8 --chunk-load-ahead=4 --max-chunks=250 --fuse-options=allow_other,read_only --config=/home/jason/plexdrive --cache-file=/usr/local/bin/cache.bolt /mnt/plexdrive

**Comment by zmike808** [comment]
Are you transcoding the video? Does it play without issue if you have the file stored locally? 

Why are you only using 250 chunks with 32GB of RAM? At the default of 10M a chunk your ram shouldn't be filling up at all. Your should be using around 2.5gb

**Comment by jcrabapple** [comment]
The video is not transcoding, but the audio is. I haven't tried playing it locally but I will.

The 250 chunks setting is something that was recommended by someone else. I can try removing that or increasing it.

**Comment by jcrabapple** [comment]
I tried it with the movie on the Plex server itself, and I have similar issues. So it seems this is an issue with upstream bandwidth, not Plexdrive.
