### ISSUE TITLE
Error with mounting Google Drive

### ISSUE THREAD

**Issue by MrTwIXx** [dweidenfeld/plexdrive#283]
Hey there,

When I enter the Google Link in my Browser I get this message: 

> Error: invalid_request
> 
> Missing required parameter: client_id

So I added my client_id into the link. Then it works.

After I put the Authorization Token in my shell I get this error message from PlexDrive:

> [PLEXDRIVE] [2018-02-06 17:14] ERROR  : Unable to retrieve token from web oauth2: cannot fetch token: 400 Bad Request
> Response: {
>   "error" : "invalid_request",
>   "error_description" : "Could not determine client ID from request."
> }

So PlexDrive couldn't find my config.json.

I followed this tutorial: https://www.lavavps.lt/login/knowledgebase.php?action=displayarticle&id=145&language=english

Can anyone help me?

**Comment by dweidenfeld** [comment]
You screwed up the config.json before authorization.
So the best thing would be if you reset the config folder and create a new config.json with the following content:
```
{"ClientID":"your-client-id.apps.googleusercontent.com","ClientSecret":"your-client-secret"}
```

Plexdrive must automatically add the client-id to the URL, so maybe you misspelled the parameters in the config.json (case etc) or the path to the config.json is wrong.
