### ISSUE TITLE
High bandwidth usage normal?

### ISSUE THREAD

**Issue by jaredhobbs** [dweidenfeld/plexdrive#286]
Set up plexdrive on my Mac yesterday and went to sleep. This morning got an alert from my ISP that I hit my monthly data cap (1024GB). Checked my router's download stats and sure enough, the Mac had downloaded a terabyte of data over night. I promptly unmounted the plexdrive until I can confirm this is expected behavior.

Also found someone else hitting the same high bandwidth issue at the plexguide forum: https://plexguide.com/threads/data-usage-from-plexdrive.608/

Can anyone confirm whether or not this is expected behavior as PMS builds the library on initial setup? If so, can I expect the bandwidth usage to drop after plex finishes building the library? I would hope to see bandwidth spikes ONLY while watching a video or scanning after uploading a new file.

**Comment by animosity22** [comment]
plexdrive doesn't do anything with bandwidth. It just mounts your drive. If you have something accessing it, backup, plex, whatever, it's going to download whatever you ask it to download.

If it's just plex, are you running any media analysis or things like that? There are many reasons why you'd see high bandwidth from mounting the drive.

**Comment by jaredhobbs** [comment]
Nope, just plain Plex Media Server. So after Plex completed adding my libraries, the bandwidth spikes stopped. Altogether around 1.4TB was downloaded in order to scan everything. Doesn't _seem_ to be spiking my bandwidth anymore.

Now the problem looks like high memory usage. Activity monitor shows plexdrive taking up 12GB of memory (out of 32GB total).

**Comment by dany20mh** [comment]
The memory usage is completely is depend on your setting that you chose before mount.

--max-chunk is the reason for memory usage, if you want Plexdrive use less memory, you have to reduce the number for that.

**Comment by animosity22** [comment]
There are quite a number of settings on Plex that can also influence bandwidth usage as well.

Media analysis adds some time.
Video Preview Thumbnails are a killer and I have them off.

The first time plex scans it's going to consume bandwidth depending on the size of your library as it has to probe each file. I have Empty Trashcan after every scan off in case I ever lose my mount, I don't have to rescan the files all over again and it'll reconnect them.

**Comment by jaredhobbs** [comment]
Thanks for the info!
