### ISSUE TITLE
Second mount without data

### ISSUE THREAD

**Issue by MrTwIXx** [dweidenfeld/plexdrive#293]
Hey there,

I mounted already one GDrive without problems. Now I want to mount a second GDrive.
So i made two new folders. /mnt/plexdrive2 and /root/.plexdrive2

When I run this(plexdrive -o allow_other -v 2 --refresh-interval=1m /mnt/plexdrive2
 -c /root/.plexdrive2) command I get this output:
![image](https://user-images.githubusercontent.com/28006175/38294820-78df5ee0-37ec-11e8-86fa-e7d076cc59b8.png)

But in the folder there is not my GDrive data.
Do you have an idear what the problem is?

Thanks

**Comment by dweidenfeld** [comment]
I think you simply missed the `--cache-file` option. This will point to the first plexdrive instance if you haven't changed it.

**Comment by felixbuenemann** [comment]
Yes, the config defaults to `~/.plexdrive/cache.bolt` even if the config directory was changed-

This is probably something that should be changed, since it's very counterintuitive.

@YipYup Would be great if you could make a PR to fix that, if you have some time.
