### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by dany20mh** [dweidenfeld/plexdrive#3]
Hi,

Sorry, this is just a question and I couldn’t figure out how to make this work with macOS, any suggestion?

Thanks.

**Comment by dweidenfeld** [comment]
I cross compiled the binaries now for darwin, too. Please see the release section.

**Comment by dany20mh** [comment]
Thanks,

It’s working now, just to mention if someone stuck with permission denied error, use this: 

sudo chmod 755 “File Name” 
ex : sudo chmod 755 plexdrive
