### ISSUE TITLE
Caching by Usage

### ISSUE THREAD

**Issue by dany20mh** [dweidenfeld/plexdrive#30]
Hi,

So I’m just wondering if it’s possible that you implement the feature that instead of expiring by time, the cache expire base on the last usage, for example we say we can have cache maximum of 500Gb and then each time if any of the files that didn’t access for specific amount of time (like 10 days) they delete from the cache.

This way we have the file that get more use in the cache handy.

**Comment by dweidenfeld** [comment]
Included in next release (see the readme in master, there is a description for "cache by usage").
