### ISSUE TITLE
Cannot read file

### ISSUE THREAD

**Issue by ArthurKnoep** [dweidenfeld/plexdrive#304]
Hi everybody

I'm using the version 5 of plexdrive and I'm able to mount my drive on a Debien 9 VPS, but, currently I cannot read the file in the mounted folder. 
I have put a file of 6 Bytes in my Drive and when I try to cat it, the server just get stuck and I'm forced to reboot it.

I had the same problem with another server (a real server this time, not virtual)

**Version: 5.0.0 plexdrive-linux-amd64**
**Server: 2 vCore / 2Go RAM / 20Go SSD**
**OS: Debian 9 (stretch)**

PS: I know the existence of the issue #247, but this issue have no answer (The other server I have tried have 4Go of RAM)

Logs:
```
Logs:
[PLEXDRIVE] [2018-07-24 11:21] TRACE  : FUSE <- Open [ID=0x1a Node=0x6 Uid=0 Gid=0 Pid=1641] dir=true fl=OpenReadOnly+OpenDirectory+OpenNonblock
[PLEXDRIVE] [2018-07-24 11:21] TRACE  : FUSE -> [ID=0x1a] Open 0x1 fl=0
[PLEXDRIVE] [2018-07-24 11:21] TRACE  : FUSE <- Getattr [ID=0x1b Node=0x6 Uid=0 Gid=0 Pid=1641] 0x0 fl=0
[PLEXDRIVE] [2018-07-24 11:21] TRACE  : FUSE -> [ID=0x1b] Getattr valid=1m0s ino=7941175627028167545 size=0 mode=drwxr-xr-x
[PLEXDRIVE] [2018-07-24 11:21] TRACE  : FUSE <- Read [ID=0x1c Node=0x6 Uid=0 Gid=0 Pid=1641] 0x1 4096 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock
[PLEXDRIVE] [2018-07-24 11:21] TRACE  : Getting children for 17sPzEgsVKSxZkv-hmjOfDBAOskD0P0fM
[PLEXDRIVE] [2018-07-24 11:21] TRACE  : Got objects from cache [0xc420226d80]
[PLEXDRIVE] [2018-07-24 11:21] TRACE  : FUSE -> [ID=0x1c] Read 32
[PLEXDRIVE] [2018-07-24 11:21] TRACE  : FUSE <- Read [ID=0x1d Node=0x6 Uid=0 Gid=0 Pid=1641] 0x1 4096 @0x20 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock
[PLEXDRIVE] [2018-07-24 11:21] TRACE  : FUSE -> [ID=0x1d] Read 0
[PLEXDRIVE] [2018-07-24 11:21] TRACE  : FUSE <- Getattr [ID=0x1f Node=0x6 Uid=0 Gid=0 Pid=1641] 0x0 fl=0
[PLEXDRIVE] [2018-07-24 11:21] TRACE  : FUSE -> [ID=0x1f] Getattr valid=1m0s ino=7941175627028167545 size=0 mode=drwxr-xr-x
[PLEXDRIVE] [2018-07-24 11:21] TRACE  : FUSE <- Release [ID=0x1e Node=0x6 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenReadOnly+OpenDirectory+OpenNonblock rfl=0 owner=0x0
[PLEXDRIVE] [2018-07-24 11:21] TRACE  : FUSE -> [ID=0x1e] Release
[PLEXDRIVE] [2018-07-24 11:21] TRACE  : FUSE <- Open [ID=0x20 Node=0x8 Uid=0 Gid=0 Pid=1972] dir=false fl=OpenReadOnly
[PLEXDRIVE] [2018-07-24 11:21] TRACE  : FUSE -> [ID=0x20] Open 0x1 fl=0
[PLEXDRIVE] [2018-07-24 11:21] TRACE  : FUSE <- Read [ID=0x21 Node=0x8 Uid=0 Gid=0 Pid=1972] 0x1 4096 @0x0 dir=false fl=0 lock=0 ffl=OpenReadOnly
[PLEXDRIVE] [2018-07-24 11:22] DEBUG  : Checking for changes
[PLEXDRIVE] [2018-07-24 11:22] DEBUG  : Getting start page token from cache
[PLEXDRIVE] [2018-07-24 11:22] TRACE  : Got start page token 24373
[PLEXDRIVE] [2018-07-24 11:22] DEBUG  : Last change id found, continuing getting changes (24373)
[PLEXDRIVE] [2018-07-24 11:22] DEBUG  : Storing page token 24373 in cache
```

**Comment by felixbuenemann** [comment]
There was issue #249, but that only affected systems with 1 vCPU and is fixed on master.

Have you tried with a larger file, like 1 MB? Also what are the exact command line parameters you used to start plexdrive?

**Comment by ArthurKnoep** [comment]
Hi,

Thanks for your answer

My bad, I have just seen that my VPS have 1 vCPU but the other server on which I've tried plexdrive have 4 core.

I've also tried some larger file, one file of 60MB and another file of 1.5GB.

My command line is the following
`./plexdrive mount /drive -v4`

**Comment by felixbuenemann** [comment]
If you have only 1 vCPU and it hangs you need to compile plexdrive from master, eg. using `go get -u github.com/dweidenfeld/plexdrive`, assuming you already have a working golang setup.

**Comment by ArthurKnoep** [comment]
I have recompiled plexdrive with `go get` and now it works, I can `cat` my small file, and I have tried with some larger files, it works but it print the file block by block (it print on the terminal the content of the file for 10sec and then block for 2 or 3sec and then print again), but it works for plex so I'm 

Thanks for your help
