### ISSUE TITLE
Support for Google transcoded streams

### ISSUE THREAD

**Issue by jmacul2** [dweidenfeld/plexdrive#306]
When you upload videos to google drive, Google uses its youtube engine to transcode all videos to h264/mp4 formats in multiple resolutions.  

Kodi plugins have taken advantage of this feature by exposing the stream urls.

https://github.com/ddurdle/GDrive-for-KODI
https://github.com/ddurdle/Python-GoogleDrive-VideoStream
https://github.com/cguZZman/plugin.googledrive

These plugins wrap the url in a .strm file that Kodi supports.  Emby supports this file type as well.  Plex used to support it, but was dropped.

A feature enhancement would be to use Fuse to create a file wrapper of sorts that could point to the mp4 url so that Plex could play it.  Options for displaying the file urls in the the filesystem would be nice so that Plex could in turn display them to the user.

This, in effect, eliminates the need for Plex to transcode files in most circumstances.  

In theory of course.

**Comment by danjames92** [comment]
this is dead in development man.

**Comment by RaymondSchnyder** [comment]
wouldnt work in a full encrypted setup.

**Comment by felixbuenemann** [comment]
In any case, those streams are not actual files and could instead be implemented as a Plex/Emby/Kodi Plugin.

It's certainly not part of the the Google Drive REST API and would have to be reverse engineered.

I don't think any of the above linked plugins use the YouTube Transcoding engine, but just serve up the original files from Google Drive.
