### ISSUE TITLE
Support Team Drive

### ISSUE THREAD

**Issue by flemzord** [dweidenfeld/plexdrive#308]
Hello, 

PlexDrive does not support Team Drive, it's possible support this ? 

Regards, 
Maxence

**Comment by felixbuenemann** [comment]
Yeah, it's possible. You could take a look at #297 and start from there.

**Comment by mondychan** [comment]
same, please info on how to get the folder node-id

**Comment by felixbuenemann** [comment]
Team Drive support was never finished, there's a PR that started to implement it in #297, but it was abandoned and is apparently incomplete.

**Comment by DaveidWeba** [comment]
I keep hearing testimonies that PlexDrive is still better than rclone for Plex streaming, so I'm gonna pitch my vote in for Team Drive support as well! Let me know what I can do to help, thank you!!

**Comment by AndersBrohus** [comment]
We are in need of Team Drive support! :)

**Comment by felixbuenemann** [comment]
You could build plexdrive from the PR in #319 and report how it works for you.

**Comment by felixbuenemann** [comment]
Closing, since #319 has been merged. Instructions for using it can be found in the comments to that PR.
