### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by sneakypete73** [dweidenfeld/plexdrive#312]
Hi. I run Plex on Windows 10 so is there a Plexdrive for Windows?

**Comment by felixbuenemann** [comment]
Plexdrive requires FUSE, which as far as I know is not supported on Windows.

**Comment by fuomag9** [comment]
@felixbuenemann https://github.com/billziss-gh/winfsp has a FUSE compatibility layer

**Comment by felixbuenemann** [comment]
@fuomag9 You can ask https://github.com/bazil/fuse about adding support for WinFsp, because that is the Go package that Plexdrive uses for interacting with FUSE:
