### ISSUE TITLE
Unable to get PlexDrive to run

### ISSUE THREAD

**Issue by notlimahrelyt** [dweidenfeld/plexdrive#313]
When attempting to run plexdrive I receive the following error:

bash: /usr/local/bin/plexdrive: No such file or directory

I have followed this step by step: https://www.lavavps.lt/login/knowledgebase.php?action=displayarticle&id=145&language=english

I am running as root.

Thanks

**Comment by felixbuenemann** [comment]
What's the output of `uname -a` in your shell and what exact download link did you use?

**Comment by notlimahrelyt** [comment]
4.15.0-39-generic #42~16.04.1-Ubuntu SMP Wed Oct 24 17:09:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

https://github.com/dweidenfeld/plexdrive/releases/download/4.0.0/plexdrive-linux-386

**Comment by felixbuenemann** [comment]
You need to download:

https://github.com/dweidenfeld/plexdrive/releases/download/5.0.0/plexdrive-linux-amd64

The link you used is to an older version and for i386 (32-Bit), but you have an x86_64 (also called amd64, 64-Bit) system.

**Comment by sachk** [comment]
Plexdrive 4.0 does run much better for many people, especially if you don't have much RAM.

**Comment by felixbuenemann** [comment]
I never tried 4.0, but in that case the url for amd64 would be:

https://github.com/dweidenfeld/plexdrive/releases/download/4.0.0/plexdrive-linux-amd64

**Comment by notlimahrelyt** [comment]
Okay, i've gotten a step further. 

/usr/local/bin/plexdrive mount -o allow_other /mnt/plexdrive/
1. Please go to https://console.developers.google.com/
2. Create a new project
3. Go to library and activate the Google Drive API
4. Go to credentials and create an OAuth client ID
5. Set the application type to 'other'
6. Specify some name and click create
7. Enter your generated client ID: _{pastedClientID}_
8. Enter your generated client secret: _{pastedSecret}_
Go to the following link in your browser _{generatedURL}_
Paste the authorization code: _{pastedCode}_

Then the terminal just infinitely sits here as if it's still loading.

I've detached the Screen terminal and checked /mnt/plexdrive but nothing is there.

**Comment by notlimahrelyt** [comment]
Just ran again with -v 3

```
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : verbosity            : DEBUG
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : root-node-id         : root
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : config               : /root/.plexdrive
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : temp                 : /tmp
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : mongo-host           : localhost
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : mongo-user           :
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : mongo-password       :
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : mongo-database       : plexdrive
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : chunk-size           : 5M
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : refresh-interval     : 5m0s
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : clear-chunk-interval : 1m0s
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : clear-chunk-age      : 30m0s
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : clear-chunk-max-size :
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : fuse-options         : allow_other
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : UID                  : 0
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : GID                  : 0
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : Umask                : ----------
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : speed-limit          :
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : Opening cache connection
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : Authorizing against Google Drive API
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : Loading token from cache
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] INFO   : Mounting path mount
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : Checking for changes
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : Getting start page token from cache
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] INFO   : Using clear-by-interval method for chunk cleaning
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : Last change id found, continuing getting changes (45344)
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] INFO   : First cache build process started...
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : Getting root from API
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] INFO   : Processed 1 items / deleted 0 items / updated 1 items
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] DEBUG  : Storing page token 45345 in cache
[USR/LOCAL/BIN/PLEXDRIVE] [2018-11-20 16:32] INFO   : First cache build process finished!
```

**Comment by notlimahrelyt** [comment]
After doing some digging, it looks like it is in fact running properly, but the mount directory is /root/mount.

I'd like the mount directory to be /mnt/plexdrive, is this possible?

**Comment by felixbuenemann** [comment]
Lookimy at the guide above for 4.0 the command is plexdrive -o … /mnt/plexdrive not plexdrive mount -o … /mnt/plexdrive. Looks like you are mixing instructions for 4.0 and 5.0.

**Comment by notlimahrelyt** [comment]
Gotcha,

Thank you so much!
