### ISSUE TITLE
Plexdrive loading before FUSE at startup on Raspberry Pi

### ISSUE THREAD

**Issue by TonyTheTechie** [dweidenfeld/plexdrive#317]

**Comment by TonyTheTechie** [comment]
I have just installed Plexdrive on a Raspberry Pi 3. I followed the instructions here and successfully got it to work.
I can successfully use systemctl to start and stop the service.
I have enabled the service for startup, the trouble I am having is that Plexdrive is starting before FUSE has been mounting, meaning that the Plexdrive service fails to start and has to be manually turned on.
How do I force Plexdrive to start after FUSE has mounted?

**Comment by felixbuenemann** [comment]
The message "lookup accounts.google.com on 192.168.1.1:53: dial udp 192.168.1.1:53: connect: network is unreachable" looks like network isn't ready when the service starts up, which `After=network-online.target` should usually ensure.

You could try to add a dependency on another service that sets up networking or tune the restart settings of the unit to try more often with a longer restart delay.
