### ISSUE TITLE
Plexdrive won't mount on startup?

### ISSUE THREAD

**Issue by generallund** [dweidenfeld/plexdrive#322]
I created a simple executable bash script and set it to run on startup in ubuntu 18.04. The script is as follows (i've edited fuse.conf so allow_other does not require sudo):

`#!/usr/bin/env bash`
`screen -S plexdrive -d -m plexdrive --uid=1002 --gid=1002 -o allow_other -v 2 --refresh-interval=60m mount /home/administrator/plexdrive`

When the system starts I get an error message as per the [attached image](https://i.imgur.com/pLWPygI.png). 

However, if I turnoff the startup script and restart the system, I'm able to mount plexdrive just fine using the above command- no errors whatsoever.

I'm a bit of a linux novice so I apologize if this is a simple question with a simple fix... But any help would greatly be appreciated. I live in a place with rolling blackouts and needing to run this every time is quite annoying.

**Comment by generallund** [comment]
Sorry I figured it out- SSD in the system was making the script run too fast, and was trying to mount before network became live apparently. Adding sleep function into the front of the command made it work perfectly.

**Comment by felixbuenemann** [comment]
You could also use systemd to run plexdrive:

```ini
[Unit]
Description=Plexdrive FUSE mount
Documentation=https://github.com/dweidenfeld/plexdrive/
AssertPathIsDirectory=/mnt/plexdrive
After=network-online.target

[Service]
User=plex
Group=plex
Type=simple
ExecStart=/usr/local/bin/plexdrive mount -v 2 -o allow_other,read_only /mnt/plexdrive
ExecStop=/bin/fusermount -uz /mnt/plexdrive
Restart=on-abort

[Install]
WantedBy=default.target
WantedBy=plexmediaserver.service
```
