### ISSUE TITLE
Google API cannot find root node ID for Team Drive

### ISSUE THREAD

**Issue by placid09** [dweidenfeld/plexdrive#327]
I decided to try out the new Team Drive support, so I download the git and built the binary. When I attempt to mount a Team Drive, it fails, stating that it cannot find the object:

``[PLEXDRIVE] [2019-07-09 16:54] DEBUG  : Getting root from API
[PLEXDRIVE] [2019-07-09 16:54] DEBUG  : googleapi: Error 404: File not found: 0AP-SACPTpduzUk9PVA., notFound
[PLEXDRIVE] [2019-07-09 16:54] WARNING: Could not get object 0AP-SACPTpduzUk9PVA from API
[PLEXDRIVE] [2019-07-09 16:54] DEBUG  : cannot obtain root node: Could not get root object``

I have confirmed both on the Google Drive address bar, and through the GCP console API:

![image](https://user-images.githubusercontent.com/27186654/60928432-b6e1df80-a26a-11e9-9aee-c10092b89cac.png)
I have confirmed the client ID and secret are both valid and have access to the drive in question. They can also mount the team drive with rclone. Any idea how to proceed?

**Comment by felixbuenemann** [comment]
Last time I tried to get Team Drive working I couldn't make it work and I took the id from Chrome while browsing the team drive.

Maybe @herver can help.

Could it be that the OAuth credentials need additional permissions to access team drives?

**Comment by placid09** [comment]
I confirmed the OAuth creds work with rclone to mount the Team Drive. Perhaps it depends on what version of  Go that it's built with?

**Comment by herver** [comment]
I'd make sure I run the a `plexdrive` compiled from `master` as there's no "release" yet with the patch.

e.g: as far as I can remember, I just built the binary with the patch that has been merged and used already existing OAuth credentials,

**Comment by placid09** [comment]
I built from the master repo including the patch. What version of Go did you build with? I initially built with Go 1.13, which provided the issues in my initial post. I then tried with Go 1.10 and 1.8, and the build failed both times. Anything I can provide to help test the issue?

**Comment by felixbuenemann** [comment]
Build should work with at least go 1.9 - 1.12, 1.8 is no longer supported and 1.13 is not yet tested.

**Comment by placid09** [comment]
I just re-built with Go 1.12 installed, and it finds the Team Drive correctly. Thank you @felixbuenemann and @herver for you help on this.

**Comment by s0mm3rb** [comment]
@placid09 would you mind sharing the compiled file?
regards
