### ISSUE TITLE
please release the master 

### ISSUE THREAD

**Issue by s0mm3rb** [dweidenfeld/plexdrive#329]
the latest release is from 2017
please update it
I tried to build it but I get alot of errors
I don't want to look into golang atm ;)
thanks

**Comment by placid09** [comment]
I got your reply to the PR thread. I also received the 404 error when I built plexdrive from source with Go 1.13. In the below thread, it was found that it works when built from 1.12.

https://github.com/dweidenfeld/plexdrive/issues/327#issuecomment-510694073

**Comment by s0mm3rb** [comment]
ok, I got it

git clone was just not enough
I had to run `go get` first

1. install go
2. mkdir $GOPATH/src
3. cd $GOPATH/src
4. go get github.com/dweidenfeld/plexdrive
5. cd $GOPATH/src/github.com
6. git clone https://github.com/dweidenfeld/plexdrive.git
7. cd $GOPATH/src/github.com/plexdrive
8. go build -o /tmp/plexdrive
9. use the new file /tmp/plexdrive

now it works

**Comment by felixbuenemann** [comment]
Just running `go get -u github.com/dweidenfeld/plexdrive` should be enough. It should download all the dependencies, compile plexdrive and install it to $GOPATH/bin/.
