### ISSUE TITLE
(UNIQUE constraint failed: api_objects.object_id)

### ISSUE THREAD

**Issue by ExeCuteUK** [dweidenfeld/plexdrive#33]
Spends a few hours caching then seems to bring up these error messages. Cache size does not seem to be increasing any further.

Have an API client ID etc. It seems to be caching some of the directory. Its launched directly into a screen using your ./plexdrive PATH command line.

Running version 1.20

> **Error Messages in screen**
> (UNIQUE constraint failed: api_objects.object_id)
> [2017-05-09 09:16:14]
> 
> (UNIQUE constraint failed: api_objects.object_id)
> [2017-05-09 09:16:14]

> **Plexdrive cache size after these messages**
> du -ha .plexdrive/
> 4.0K    .plexdrive/config.json
> 347M    .plexdrive/cache
> 347M    .plexdrive/

My gdrive is around 60TB large.

Just noticed a previous post on this error. Running with -log 4 switch to see what it brings up.

**Comment by dweidenfeld** [comment]
#15
