### ISSUE TITLE
plexdrive does not show all files

### ISSUE THREAD

**Issue by s0mm3rb** [dweidenfeld/plexdrive#330]
hi there
I successfully built the project from source with 'go'
and was able to mount my team drive
but it does not show all files
there are missing folders and alot of folders shown as empty

is there a limit for amout of files somewhere?
I've recreated the auth token and it showed: `Processed 7886 items / deleted 268 items / updated 7618 items`
so I guess plexdrive gets 7886 files from my drive?
but `rclone size` shows that there are 9119 files at the drive

any help is appreciated
thanks

structure is like this
/mounted/drive/
------>RootSubFolderOne (visible)
------------>Sub1 (not visible)
------------>Sub2 (no visible)
------------>Sub3 (visible)
------------------>a lot of missing and empty folders
------->RootSubFolderTwo (visible)
------------>Every Folder and File visible

**Comment by felixbuenemann** [comment]
You could try removing cache.bolt from ~/.plexdrive and restart plexdrive to force a complete resync of the file system.

**Comment by s0mm3rb** [comment]
@felixbuenemann looks like deleting cache.bolt fixed this
thanks
