### ISSUE TITLE
[FR] Inotify support for automatic media indexing

### ISSUE THREAD

**Issue by MrDini123** [dweidenfeld/plexdrive#331]
Hi,

I am a huge fan of this project, you have built a must have app for Plex & Drive. This is the only project that I have seen already which builds a file index db locally and only checks for updates periodically. I think this model could be amazing to support inotify and tell any subscribed watcher (which could be for example Plex / minidlna) about new or modified files, folders.

## About the implementation

Since you use fuse mounts, I firstly found [this article](https://github.com/libfuse/libfuse/wiki/Fsnotify-and-FUSE) which wasn't so promising for the first look, but inotify support is clearly possible, see [this thread](https://sourceforge.net/p/fuse/mailman/message/24625009/). There is also a C example at the given link which I tried and can confirm it works. So I took a look at the go fuse implementation you are using and found [this function](https://github.com/bazil/fuse/blob/65cc252bf6691cb3c7014bcb2c8dc29de91e3a7e/fuse.go#L1168-L1194) which might be what we are looking for. Couldn't test it though, since I have not much experience with this fuse lib.

## Why would it be useful?

Plexdrive could send a "notification" to any supported media server such as Plex ([or even a remote Plex server](https://github.com/talisto/plex-inotifier)) or minidlna on any changes made on the files, so they could scan them automatically without any timed or manual full rescan.

I would personally love to see such a feature in a future. Thanks

**Comment by felixbuenemann** [comment]
As far as I know fsnotify support in fuse is not implemented and the linked document only contains some ideas on how it could work. 

If you can point me at an existing fuse filesystem that has fsnotify support, I'd be happy to be proven wrong.

**Comment by MrDini123** [comment]
AFAIK fsnotify isn't supported but inotify is. If you call that function linked in my post with the invalidation it should notify the subscribed inotify watchers about the change.

**Comment by MrDini123** [comment]
Nevermind, sadly it's only supported if a local write or file open/close happens. There is no way to trigger that manually.
