### ISSUE TITLE
terminate called after throwing an instance of 'soci::soci_error'

### ISSUE THREAD

**Issue by Halo2Brian** [dweidenfeld/plexdrive#336]
Plex Media Scanner is crashing after it reads one video.  I am trying to do the initial scan.  I am running Ubuntu on a VM so not sure if that is the cause or not.

more Plex\ Media\ Scanner.log
Nov 01, 2019 08:23:37.172 [0x7f7fbbd28700] INFO - Plex Media Scanner v1.18.1.1973-0f4abfbcc - Ubuntu PC x86_64 - build: linux-x86_64 - GMT -07:00
Nov 01, 2019 08:23:37.172 [0x7f7fbbd28700] INFO - Linux version: 18.04.3 LTS (Bionic Beaver), language: en-US
Nov 01, 2019 08:23:37.172 [0x7f7fbbd28700] INFO - Processor Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Nov 01, 2019 08:23:37.172 [0x7f7fbbd28700] INFO - /usr/lib/plexmediaserver/Plex Media Scanner --scan --refresh --section 2 --activity fe86dc5f-e571-4991-a218-64131df47017
Nov 01, 2019 08:23:37.171 [0x7f7fc471f740] DEBUG - Opening 20 database sessions to library (com.plexapp.plugins.library), SQLite 3.26.0, threadsafe=1
Nov 01, 2019 08:23:37.360 [0x7f7fc471f740] DEBUG - Scanning Movies using en(Plex Movie Scanner) with 3 current media items and 1 section locations in the database...
Nov 01, 2019 08:23:37.361 [0x7f7fc471f740] DEBUG - HTTP requesting PUT http://127.0.0.1:32400/activities/fe86dc5f-e571-4991-a218-64131df47017?percentComplete=0
Nov 01, 2019 08:23:37.361 [0x7f7fc471f740] DEBUG - HTTP 200 response from PUT http://127.0.0.1:32400/activities/fe86dc5f-e571-4991-a218-64131df47017?percentComplete=0
Nov 01, 2019 08:23:37.364 [0x7f7fbb222700] DEBUG - HTTP requesting GET http://127.0.0.1:32400/:/metadata/notify/cullTimeline?librarySectionID=2&sinceTime=1572620617
Nov 01, 2019 08:23:37.368 [0x7f7fbb222700] DEBUG - HTTP 200 response from GET http://127.0.0.1:32400/:/metadata/notify/cullTimeline?librarySectionID=2&sinceTime=1572620617
Nov 01, 2019 08:23:37.481 [0x7f7fc471f740] DEBUG - Performing a scan with 'Plex Movie Scanner' (language: en virtual: 0).
Nov 01, 2019 08:23:37.481 [0x7f7fc471f740] DEBUG -   * Scanning /home/plex/plexdrive/Movies
Nov 01, 2019 08:23:37.574 [0x7f7fc471f740] DEBUG - Scanner: Processing directory /home/plex/plexdrive/Movies (parent: no)
Nov 01, 2019 08:23:45.579 [0x7f7fc471f740] DEBUG - Directory had 6221 files, database had 3 files, can't skip.
Nov 01, 2019 08:24:25.879 [0x7f7fc471f740] DEBUG - Looking for path match for [/home/plex/plexdrive/Movies/10 Cloverfield Lane (2016).mkv]
Nov 01, 2019 08:24:25.879 [0x7f7fc471f740] DEBUG - Path matched, we're reusing media item 1
Nov 01, 2019 08:24:25.880 [0x7f7fc471f740] DEBUG - Noting item as needing media analysis, scanning=1, streams=1, missing channels=0, streamability=0, size=0, time=0.
Nov 01, 2019 08:24:25.880 [0x7f7fc471f740] DEBUG - Turbo analysis on modified item 1 [/home/plex/plexdrive/Movies/10 Cloverfield Lane (2016).mkv]
Nov 01, 2019 08:24:25.880 [0x7f7fc471f740] DEBUG - Updating media item 1, size=10717183975, metadata_item_id=1
Nov 01, 2019 08:24:25.880 [0x7f7fc471f740] DEBUG - Updating part with ID=1 [/home/plex/plexdrive/Movies/10 Cloverfield Lane (2016).mkv]
Nov 01, 2019 08:24:25.881 [0x7f7fc471f740] DEBUG - Looking for path match for [/home/plex/plexdrive/Movies/10 Rillington Place (1971).mkv]
Nov 01, 2019 08:24:25.881 [0x7f7fc471f740] DEBUG - Path matched, we're reusing media item 2
Nov 01, 2019 08:24:25.881 [0x7f7fc471f740] DEBUG - Noting item as needing media analysis, scanning=1, streams=1, missing channels=0, streamability=0, size=0, time=0.
Nov 01, 2019 08:24:25.881 [0x7f7fc471f740] DEBUG - Turbo analysis on modified item 2 [/home/plex/plexdrive/Movies/10 Rillington Place (1971).mkv]
Nov 01, 2019 08:24:25.882 [0x7f7fc471f740] DEBUG - Updating media item 2, size=9391079305, metadata_item_id=2
Nov 01, 2019 08:24:25.882 [0x7f7fc471f740] DEBUG - Updating part with ID=2 [/home/plex/plexdrive/Movies/10 Rillington Place (1971).mkv]
Nov 01, 2019 08:24:25.882 [0x7f7fc471f740] DEBUG - Looking for path match for [/home/plex/plexdrive/Movies/10 Rules for Sleeping Around (2013).mkv]
Nov 01, 2019 08:24:25.882 [0x7f7fc471f740] DEBUG - Path matched, we're reusing media item 3
Nov 01, 2019 08:24:25.882 [0x7f7fc471f740] DEBUG - Noting item as needing media analysis, scanning=1, streams=1, missing channels=0, streamability=0, size=0, time=0.
Nov 01, 2019 08:24:25.882 [0x7f7fc471f740] DEBUG - Turbo analysis on modified item 3 [/home/plex/plexdrive/Movies/10 Rules for Sleeping Around (2013).mkv]
Nov 01, 2019 08:24:25.883 [0x7f7fc471f740] DEBUG - Updating media item 3, size=7031204305, metadata_item_id=3
Nov 01, 2019 08:24:25.883 [0x7f7fc471f740] DEBUG - Updating part with ID=3 [/home/plex/plexdrive/Movies/10 Rules for Sleeping Around (2013).mkv]
Nov 01, 2019 08:24:25.884 [0x7f7fc471f740] DEBUG - Looking for path match for [/home/plex/plexdrive/Movies/10 Things I Hate About You (1999).mkv]
Nov 01, 2019 08:24:25.884 [0x7f7fc471f740] DEBUG - Skipping hash check, no size match for 7046202179 bytes.
Nov 01, 2019 08:24:25.885 [0x7f7fc471f740] DEBUG - No match for hash.
Nov 01, 2019 08:24:25.885 [0x7f7fc471f740] DEBUG - Downloading document http://127.0.0.1:32400/library/changestamp
Nov 01, 2019 08:24:25.885 [0x7f7fc471f740] DEBUG - HTTP requesting GET http://127.0.0.1:32400/library/changestamp
Nov 01, 2019 08:24:25.886 [0x7f7fc471f740] DEBUG - HTTP 200 response from GET http://127.0.0.1:32400/library/changestamp
Nov 01, 2019 08:24:25.887 [0x7f7fc471f740] DEBUG - Downloading document http://127.0.0.1:32400/library/changestamp
Nov 01, 2019 08:24:25.887 [0x7f7fc471f740] DEBUG - HTTP requesting GET http://127.0.0.1:32400/library/changestamp
Nov 01, 2019 08:24:25.888 [0x7f7fc471f740] DEBUG - HTTP 200 response from GET http://127.0.0.1:32400/library/changestamp
Nov 01, 2019 08:24:25.888 [0x7f7fc471f740] DEBUG - Added new metadata item (10 Things I Hate About You) with ID 4

/usr/lib/plexmediaserver/Plex\ Media\ Scanner -l
terminate called after throwing an instance of 'soci::soci_error'
  what():  sqlite3_statement_backend::prepare: no such column: library_sections.content_changed_at for SQL: select library_sections.id as 'library_sections_id', library_sections.library_id as 'library_sections_library_id', library_sections.name as 'library_sections_name', library_sections.name_sort as 'library_sections_name_sort', library_sections.section_type as 'library_sections_section_type', library_sections.language as 'library_sections_language', library_sections.agent as 'library_sections_agent', library_sections.scanner as 'library_sections_scanner', library_sections.user_thumb_url as 'library_sections_user_thumb_url', library_sections.user_art_url as 'library_sections_user_art_url', library_sections.user_theme_music_url as 'library_sections_user_theme_music_url', library_sections.created_at as 'library_sections_created_at', library_sections.updated_at as 'library_sections_updated_at', library_sections.scanned_at as 'library_sections_scanned_at', library_sections.user_fields as 'library_sections_user_fields', library_sections.query_xml as 'library_sections_query_xml', library_sections.query_type as 'library_sections_query_type', library_sections.uuid as 'library_sections_uuid', library_sections.changed_at as 'library_sections_changed_at', library_sections.content_changed_at as 'library_sections_content_changed_at' from library_sections
****** PLEX MEDIA SCANNER CRASHED, CRASH REPORT WRITTEN: /home/plex/Library/Application Support/Plex Media Server/Crash Reports/1.18.1.1973-0f4abfbcc/PLEX MEDIA SCANNER/279d938e-616e-1a53-53f8dbba-2369fcc9.dmp

**Comment by felixbuenemann** [comment]
It looks like your Plex database schema is not up to date, you probably need to restart plex media server to fix that and make sure the filesystem that containts /var/lib/plexmediaserver is not read-only or out-of-space.

In any case this has nothing to do with Plexdrive.

**Comment by enz1ey** [comment]
I know this is old, but I get the same error if I don't use the following commands prior to running the scanner manually:
`
export LD_LIBRARY_PATH=/usr/lib/plexmediaserver:/usr/lib/plexmediaserver/lib
`
`export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/var/lib/plexmediaserver/Library/Application\ Support`

Running those before executing the scanner should work. I have those two lines in my scanning scripts so I don't have to run full library scans when adding media to avoid API bans.

**Comment by Dash83** [comment]
I'm experiencing the same issue as OP, and the workaround by @enz1ey still works today for plexmediaserver version: 1.22.1.4228-724c56e62 for ARM (Raspberry Pi).

**Comment by marksherman** [comment]
I was experiencing this until I realized I wasn't running the scanner command as the plex user.

Doing an `sudo -u plex -s` then trying again, it works perfectly. 

The error is because of some permission thing, which i'd argue is it working correctly- become the plex user and it will work correctly.

**Comment by x86txt** [comment]
>The error is because of some permission thing, which i'd argue is it working correctly- become the plex user and it will work correctly.

@marksherman - it's not a permission thing, because even running it as root or via sudo still throws the error. It's because those environment variables aren't set. When you add -s to sudo it executes the user's shell, in this case the plex user, which would have those environment exports set.

That said, it's safer to use your method to avoid inadvertently changing ownership of files that may cause Plex a problem later.

**Comment by egphp** [comment]
> I know this is old, but I get the same error if I don't use the following commands prior to running the scanner manually: `export LD_LIBRARY_PATH=/usr/lib/plexmediaserver:/usr/lib/plexmediaserver/lib` `export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/var/lib/plexmediaserver/Library/Application\ Support`
> 
> Running those before executing the scanner should work. I have those two lines in my scanning scripts so I don't have to run full library scans when adding media to avoid API bans.

that's working good , but after that yum update , not working
any help ?
