### ISSUE TITLE
Getting invalid_client

### ISSUE THREAD

**Issue by sogeniusio** [dweidenfeld/plexdrive#344]
I pasted in the wrong value for client_id and now it cannot be changed:

Go to the following link in your browser https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=sudo&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=state-token

Any way to clear that cached value?

**Comment by felixbuenemann** [comment]
You can remove `~/.plexdrive/config.json` and `~/.plexdrive/token.json`, then you should be able to redo the setup steps.
