### ISSUE TITLE
Betas / Nightlies?

### ISSUE THREAD

**Issue by xyber411** [dweidenfeld/plexdrive#35]
Just wondering if we could get a nightlies / beta downloads area?

Also, a static link to the most recent stable build would be good too.  Most others label this as -latest.

**Comment by dweidenfeld** [comment]
Good idea, I just haven't had the time to automate this.

**Comment by dany20mh** [comment]
I like this too, because I seen a lot of changes so far and I'm still waiting for the next release.

**Comment by dweidenfeld** [comment]
I checked my current infrastructure and it doesn't allow the nightly builds right now. I have to refactor my infrastructure first so that nighly builds are possible ;)

**Comment by dany20mh** [comment]
@xyber411 

Until that time, you can download the zip file and get go language for your OS and use "go build" and get the compile file.

I have macOS and I got Go with homebrew and after I run the "go build" it tells me some package missing inside quote and I just copy those and used "go get ..." one by one until it compile the file.

Hope that help you for time being.

**Comment by Em31Et** [comment]
@dweidenfeld 
Suggest to update version number on new commit since people may compile from source themselves

**Comment by dweidenfeld** [comment]
@Em31Et I see. But the problem is, that I currently don't want to set the version for the next release because I don't know what kind of version it will be (http://semver.org/).
I think we should wait, till I got the process running for nightlies ;)

**Comment by jaketame** [comment]
@dweidenfeld I've managed to get tag based commits to compile via travis on my fork, this could be done for every commit release or for point releases.

Looking to expand the build process for all os's.

**Comment by dweidenfeld** [comment]
@mitchelp is already working on a forum and vps setup for nighly builds. 

@jaketame thank you for your work, but I think you can stop now, because there will be an official solution soon ;)

**Comment by mitchelp** [comment]
@dweidenfeld Maybe we should wait with a forum for now. It will make plexdrive bigger and it's as you said just a side project to support gdrive until rclone does.

@jaketame maybe it's not a good thing to have nightlies, because there will be a lot of less experienced users that will install and start complaining about functions that are not ready. Or other bugs and fails in the not finished for release code.

The experience users now how to build from source. So they can do that in case needed.

**Comment by dweidenfeld** [comment]
@mitchelp I agree... There have been too many questions about non-final versions already. So I don't think I will provide nighlies.

**Comment by dweidenfeld** [comment]
Since plexdrive is stable now there is an automated process for pushing nightlies / change versions to GitHub and Slack ;)
