### ISSUE TITLE
Is fusermount -u triggering a graceful plexdrive program exit?

### ISSUE THREAD

**Issue by xyber411** [dweidenfeld/plexdrive#37]
It has occurred to me that most if not all of these drive mount programs do not document any way of gracefully exiting.

Would it be a good idea to have an option like plexdrive-linux-amd64 -dismount "/path/to/mount"?

Currently I'm just using fusermount -u "/path/to/mount", and sometimes throwing a -uz at it, but then I wind up having to kill a plexdrive task.

**Comment by dweidenfeld** [comment]
Interesting, I just use ```umount /mydrive``` and it triggers all graceful unmount routines I've implemented ;)

**Comment by dweidenfeld** [comment]
Tested it, both mechanisms are working fine for me.

**Comment by xyber411** [comment]
Must just be something weird with unraid / slackware...  I'll put it into my ubuntu vm instead.
Thank you for all your time and hard work.

I'm a network engineer by trade. If I can ever make things easier for you, let me know.

Thank you,

Xyber411

Ps. This email was sent from my mobile phone. Please disregard any misspellings or misinterpreted voice typing that I may not have fixed.

On May 9, 2017, at 8:58 AM, Dominik Weidenfeld <notifications@github.com<mailto:notifications@github.com>> wrote:


Tested it, both mechanisms are working fine for me.
