### ISSUE TITLE
Flags Problem

### ISSUE THREAD

**Issue by dany20mh** [dweidenfeld/plexdrive#39]
Hi,

So I made the package from the master with "go build" on my macOS.

As of now it's version 2.0.0 , but the problem is that some of the argument doesn't work and it tells me that the flag needs an argument and I have it already in the code.

If I don't use those flags, it will work, I tried the --chunk-size and --clear-chunk-age and both have same problem.

PS. I just notice were is the problem is, you made changes in the main.go but those changes "POSIX/GNU style command line flags" only took places for some flags and you missed 3 of them.
Which if I use -chunk-size (old one) the application will work. 
```
./plexdrive --chunk-size 8242880 ./mtng
flag needs an argument: --chunk-size
Usage of ./plexdrive:
  --chunk-size int
    	The size of each chunk that is downloaded (in byte) (default 5242880)
  --clear-chunk-age duration
    	The maximum age of a cached chunk file (default 30m0s)
  --clear-chunk-interval duration
    	The time to wait till clearing the chunk directory (default 1m0s)
  -c, --config string
    	The path to the configuration directory (default "/Users/danial/.plexdrive")
  -o, --fuse-options string
    	Fuse mount options (e.g. -fuse-options allow_other,...)
  --gid int
    	Set the mounts GID (-1 = default permissions) (default -1)
  --refresh-interval duration
    	The time to wait till checking for changes (default 5m0s)
  -t, --temp string
    	Path to a temporary directory to store temporary data (default "/var/folders/ln/7p8jd1ln5djgqchvm5v525dh0000gq/T/")
  --uid int
    	Set the mounts UID (-1 = default permissions) (default -1)
  -v, --verbosity int
    	Set the log level (0 = error, 1 = warn, 2 = info, 3 = debug, 4 = trace)
  --version
    	Displays program's version information
```

**Comment by dweidenfeld** [comment]
Please wait for the release.
Everything is working for me with ```plexdrive --clear-chunk-age=5m```

Not all parameters should have a shorthand
