### ISSUE TITLE
Could not initialize Google Drive Client

### ISSUE THREAD

**Issue by zenjabba** [dweidenfeld/plexdrive#4]
`root@ip-172-31-3-69 plexdrive]# ./plexdrive-linux-amd64 /mnt/plexdrive

Go to the following link in your browser https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=59984850590-0c7j4nd1si3nick410ns5s83tpre216m.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=state-token

Paste the authorization code: XXX

[PLEXDRIVE-LINUX-AMD64] [2017-05-03 22:15] ERROR  : Could not initialize Google Drive Client`

**Comment by zenjabba** [comment]
Ended up being badly formatted json file. I would suggest writing a routine within the main codebase to create the json file.

**Comment by dweidenfeld** [comment]
You're right. I reopened the ticket, so I will have it on my todo list.
There should be some mechanism to enter the clientid/secret if the config.json doesn't exist already.

**Comment by dweidenfeld** [comment]
Implemented for next release.
