### ISSUE TITLE
Content vanished from plexdrive.

### ISSUE THREAD

**Issue by Krealle** [dweidenfeld/plexdrive#40]
So I have setup plexdrive and everything has been working until suddenly two of my movies are showing up as unavailable in plex, and are seemingly gone from the drive, but connecting to the drive using rclone shows the movies as still being there. The movies seems to have disappeared after plexdrive did a refresh, and is not showing up in further refreshes. New content that I'm adding is still showing up properly.

I'm running debian and using this command:
`./plexdrive -fuse-options allow_other -log-level 4 /home22/krealle/mounts/plexdrive`
And this command for decrypting the folder:
`screen -S rclone.plexdrive2: -d -m rclone mount --read-only --allow-non-empty --allow-other --buffer-size 128M -v plexdrive2: /home22/krealle/mounts/plexdrive-decrypt`
![vncviewer_2017-05-09_18-20-31](https://cloud.githubusercontent.com/assets/3404958/25861368/cc418c2c-34e4-11e7-8b17-630f2feee6fd.png)

**Comment by jrarseneau** [comment]
This was fixed a few versions ago, maybe delete everything in your cache and restart with the newly released v2.0.

**Comment by dweidenfeld** [comment]
Exactly @jrarseneau.

It seems that you are storing illegal content, so I have to distance myself from supporting the distribution/usage of illegal content. That is not what Plexdrive is made for.
