### ISSUE TITLE
plexdrive 5.2.1 not getting always the right file

### ISSUE THREAD

**Issue by carlosrovira** [dweidenfeld/plexdrive#415]
Hi, 

just upgrade fro 5.1.0 to 5.1.2 and after playing a first file, the rest of others play was using the same stream from the first play.
I switch again to 5.1.0 to solve this problem.

HTH

**Comment by felixbuenemann** [comment]
Did you delete the `~/.plexdrive/cache.bolt` before starting the new version?

**Comment by carlosrovira** [comment]
Thanks Felix, just tried and that seems to fix the problem. I'll be testing in the following days to see if all continues to work smoothly. Many thanks!
