### ISSUE TITLE
-chunk-size option not respected

### ISSUE THREAD

**Issue by dcplaya** [dweidenfeld/plexdrive#42]
When I specify a chunk size and run it in debug mode level 3, the chunk size is still the default 52428800 even though I did 

``plexdrive-linux-amd64 -chunk-size 104857600 -o allow_other -v 3 /mnt/gsuites_plexdrive``

**Comment by dany20mh** [comment]
I reported this here https://github.com/dweidenfeld/plexdrive/issues/39 but @dweidenfeld closed it.

The problem is find is that the structure changed but the readme didn’t change base on that and we still using the old one.

```
Old one:
-chunk-size int 
New readme : 
--chunk-size int

Correct:
--chunk-size=int
```

**Comment by dcplaya** [comment]
Ill give that a try once it rebuilds the database. I also noticed that if you kill it before its finished building, it will ask for credentials again which is a tiny bit annoying

**Comment by dcplaya** [comment]
Im closing this. The correct syntax is what @dany20mh said above. The README just needs to be updated
