### ISSUE TITLE
 Could not find object

### ISSUE THREAD

**Issue by hjtech** [dweidenfeld/plexdrive#43]
Getting the following messages after removal of 1.2.0 and cache removed (~/.plexdrive/cache) and using now 2.0.0.
What does it mean?

`[PLEXDRIVE] [2017-05-09 13:55] DEBUG  : Could not find object with name .metadata_never_index_unless_rootfs in parent 0AFOIT_N-PGG6Uk9PVA
[PLEXDRIVE] [2017-05-09 13:55] DEBUG  : Getting object .metadata_never_index in parent 0AFOIT_N-PGG6Uk9PVA
[PLEXDRIVE] [2017-05-09 13:55] DEBUG  : Could not find object with name .metadata_never_index in parent 0AFOIT_N-PGG6Uk9PVA
[PLEXDRIVE] [2017-05-09 13:55] DEBUG  : Getting object .metadata_never_index_unless_rootfs in parent 0AFOIT_N-PGG6Uk9PVA
[PLEXDRIVE] [2017-05-09 13:55] DEBUG  : Could not find object with name .metadata_never_index_unless_rootfs in parent 0AFOIT_N-PGG6Uk9PVA`

**Comment by dweidenfeld** [comment]
This could be an issue if you miss some files. Usually it is just a debug message and you can ignore it.

**Comment by hjtech** [comment]
Thanks @dweidenfeld.
I'm now getting warnings:

`[PLEXDRIVE] [2017-05-09 18:00] WARNING: Could not find children for parent 0B1OIT_N-PGG6ZWJ4OVJJaEV0UEE in cache
[PLEXDRIVE] [2017-05-09 18:00] DEBUG  : Getting children for 0B1OIT_N-PGG6SUpsOWQwZXMwRkE
[PLEXDRIVE] [2017-05-09 18:00] WARNING: Could not find children for parent 0B1OIT_N-PGG6SUpsOWQwZXMwRkE in cache`

One file is now missing, it is showing when browsing Google Drive, but does not show when mounting with plexdrive.

**Comment by hjtech** [comment]
Update:
The drive unmounted with the following errors:

> [PLEXDRIVE] [2017-05-10 04:48] DEBUG  : Requesting object 0B1OIT_N-PGG6UDhBNG1ueTYzQWs bytes 12478054400 - 12582912000 from API
[PLEXDRIVE] [2017-05-10 04:48] DEBUG  : Getting object .metadata_never_index in parent 0AFOIT_N-PGG6Uk9PVA
[PLEXDRIVE] [2017-05-10 04:48] DEBUG  : Could not find object with name .metadata_never_index in parent 0AFOIT_N-PGG6Uk9PVA
[PLEXDRIVE] [2017-05-10 04:48] DEBUG  : Getting object .metadata_never_index_unless_rootfs in parent 0AFOIT_N-PGG6Uk9PVA
[PLEXDRIVE] [2017-05-10 04:48] DEBUG  : Could not find object with name .metadata_never_index_unless_rootfs in parent 0AFOIT_N-PGG6Uk9PVA
[PLEXDRIVE] [2017-05-10 04:50] DEBUG  : Checking for changes
[PLEXDRIVE] [2017-05-10 04:50] DEBUG  : Getting change id from cache
[PLEXDRIVE] [2017-05-10 04:54] WARNING: stream error: stream ID 623; INTERNAL_ERROR
[PLEXDRIVE] [2017-05-10 04:54] INFO   : Unmounting path /Volumes/GDrive
[PLEXDRIVE] [2017-05-10 04:54] DEBUG  : Closing cache connection
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x43cd4be]
>
goroutine 59 [running]:
main.(*Cache).startStoringQueue(0xc4201005c0)
	/go/src/github.com/dweidenfeld/plexdrive/cache.go:84 +0x14e
created by main.NewCache
	/go/src/github.com/dweidenfeld/plexdrive/cache.go:74 +0x4b5

**Comment by dweidenfeld** [comment]
I think I addressed your issue. The program will be more tolerant in the next release.

Please also check your hardware, that you have enough disc space etc. ;)
