### ISSUE TITLE
Chunk cache implementation

### ISSUE THREAD

**Issue by Ninjouz** [dweidenfeld/plexdrive#44]
Hey, firstly thanks for your great work.

If I read properly, you can't really limit the cache size. Only set a simple max age.

A better approach would have been to implement a LRU cache (used in many cases). That way u can set a max cache size and if full the least recently used file / chunk get evicted to make space for the newest.

We could control the buffer cache size.

**Comment by zenjabba** [comment]
Honestly, this was about getting something working for plex use as quickly as possible. The buffer size whilst annoying isn't a major issue.

**Comment by dweidenfeld** [comment]
Exactly... I am not planning to limit the cache size. Maybe sometimes ....

If you set leave the cache settings to default a normal movie with 15gb should be cleaned up while it's playing.
