### ISSUE TITLE
Ctrl + C ( SIGINT ?) Should unmount the mount

### ISSUE THREAD

**Issue by qnorsten** [dweidenfeld/plexdrive#45]
I just ran plexdrive in a screen session while generating the first time cache and released that killing the program with CTRL +C (Sending a  SIGINT signal?) does not force a unmount of the mount. While not a major issue, it would be nice if plexdrive would unmount the mount before exiting.

**Comment by animosity22** [comment]
With everything else I've used, you have to use fusermount -u /mnt to stop the process. Anything else leaves something hanging around.

**Comment by Qwatuz** [comment]
I've found that if i close plexdrive with ctrl +c, I then have to run fusermount -uz as sudo to get it to dismount properly.

**Comment by animosity22** [comment]
Yeah, don't use the ctrl+c, just run the fusermount and that unmounts it and stops the process cleanly.

**Comment by qnorsten** [comment]
I know that it is not always possible to clean up and unmount a mount without fusermount -uz, and it is not a major problem, especially when using plexdrive as service, but I still belieave that it is good practice to try and perform an unmount when a SIGINT or SIGTERM signal is recived (as Rclone handles it here https://github.com/ncw/rclone/blob/86cc9f3dfbbcb8e4b7839e2402692df4c206766e/cmd/atexit.go#L22)

**Comment by dweidenfeld** [comment]
Nice idea. SIGINT is implemented for the next release
