### ISSUE TITLE
Inconsistent download speed

### ISSUE THREAD

**Issue by Eric343** [dweidenfeld/plexdrive#46]
Hey, the plex library scanning works perfectly but the download speed when playing a video is really inconsistent as following image shows:

![speed](https://cloud.githubusercontent.com/assets/9350215/25873397/a9fb991c-350e-11e7-943c-8bb00688224b.PNG)

When using rclone mount the speed is consistently at the maximum.
Is upping the chunk size a solution?
Thanks

**Comment by animosity22** [comment]
Are you seeing any playback issues? I've noticed with any of the solutions, depending on how you do the buffer/memory size, you can really either get a huge burst in the beginning with no traffic or with a smaller buffer, it's more choppy bandwidth wise.

I used to do a 1GB buffer with rclone and roughly a 512MB buffer with ocamlfuse. I've been toying around with chunk size and last I was trying ~50MB. You could even do a little chunk size and let rclone be the buffer too. 

![image](https://cloud.githubusercontent.com/assets/5088712/25878742/12b97834-34fb-11e7-92b7-cd77d0769e27.png)

**Comment by hjone72** [comment]
@Eric343, This is fairly normal behavior and is related to how plex handles the streams. What server version are you running?

I'd also suggest trying PMP (Plex media player) that should help with your issue.

**Comment by animosity22** [comment]
@hjone72 - how so? if I do a 1G buffer on rclone, it has a sharp spike in the beginning and than drops to a few Mb/s during the course of the stream. If you do a smaller buffer, it'll be more 'sawtooth' as it has to keep filling the buffer back up.

**Comment by hjone72** [comment]
Sorry, I've miss read your picture. I thought that was your Windows Client performance, hence my response. Sorry for the confusion.

**Comment by animosity22** [comment]
That was just a grafana graph from netdata with my router bandwidth. I should have labeled it. I bumped up my chunk size to 250M to see and that generated a nice chunk download to the /tmp folder. I like the idea of writing to a temp location rather than memory since I sit my /tmp on SSD anyway.

You can see the 2 spikes when it grabs the big chunk I setup:

![image](https://cloud.githubusercontent.com/assets/5088712/25880753/48f53968-3507-11e7-97e0-6476b7883688.png)

So if you make the chunk size much bigger, if your link has the capacity, seems like I'd go that route as I rather bite the bullet up front and grab bigger chunks.

**Comment by jrarseneau** [comment]
@animosity22 

You absolutely can't compare plexdrive with rclone (with the new --buffer-size option)

If you set the buffer-size to 1GB, then rclone will spike at the start and download the 1GB and then trickle fill the buffer as your stream.

PlexDrive does not work this way. Changing the chunk size will not do anything other than what you observed. A spike at the start where it downloaded 250M, then another, etc. 

Two different architectures, apples to oranges comparison.

**Comment by animosity22** [comment]
@jrarseneau - I think we already compared them in use and how they both use bandwidth. It was not an architecture or methodology contrast, but how they use bandwidth. As you yourself stated, you compared how each works and how they consume bandwidth 'compared' to each other :)

**Comment by dweidenfeld** [comment]
I am not quite sure if you got issues while playing your files?!

You can get the "rclone" behaviour if you reduce the chunk size to a minimum (e.g 8kb), then it will request more often and you won't get the spike at the beginning.

I will close the issue now, you can reopen the issue if you have problems playing back your files.

**Comment by Eric343** [comment]
Sorry I forgot to mention that I had constant buffering in Plex (Plex Media Player). Otherwise there would be no reason to complain :)

I'll play around with the settings then, thanks.

**Comment by dweidenfeld** [comment]
Ok.. 
Just as a hint (my media server specs):
2 cores / 1gb ram / 200gb HDD / 100mbit connection

I have all settings set to their defaults and no stuttering at all, even with 20mbit movies.
