### ISSUE TITLE
--clear-chunk-age not working?

### ISSUE THREAD

**Issue by cardinalfan1** [dweidenfeld/plexdrive#47]
hi
i'm trying to set the --clear-chunk-age option, but I get 

`plexdrive -o allow_other --clear-chunk-age 7777 ~/cloud/tmp`
`flag needs an argument: --clear-chunk-age`

**Comment by dany20mh** [comment]
Use it like that, readme is not correct.

`--clear-chunk-age=7777`

**Comment by cardinalfan1** [comment]
thanks
