### ISSUE TITLE
`GLIBC_2.14' not found Error on Debian Wheezy 

### ISSUE THREAD

**Issue by ElrondVardamir** [dweidenfeld/plexdrive#49]
Hy,

I tried to configure Plexdrive on my Debian Wheezy amd64 but It return this error :

/usr/sbin/plexdrive: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/sbin/plexdrive)

Do you have a solution ?

Thanks a lot

**Comment by hthighway** [comment]
A Similar issue was posted here:
https://github.com/RasPlex/rasplex-installer/issues/16

and the solution was to:

Edit:  /etc/apt/sources.list
Add: deb http://http.us.debian.org/debian/ testing non-free contrib main
```
apt-get update
apt-get install libc6-dev
```
Note: remember to remove source after updating if you dont want to mix sources.
