### ISSUE TITLE
What happens when Cache fills a drive?

### ISSUE THREAD

**Issue by xyber411** [dweidenfeld/plexdrive#50]
I had my Cache set to the /tmp folder, as is default, and --clear-chunk-age=1440m but yesterday I ran a full plex scan, and after about 2 hours, the server almost locked up.  Luckily, I have it email me when ram is almost full, so I was able to catch it and remove some of the items in /tmp manually.  I then moved my Cache to my primary SSD, and let it run the scan with the cache in there...  and it filled the drive.  I then removed the cache again, and then set the --clear-chunk-age=15m.  I was then able to complete my scan, which ran beautifully.  Thing is, though that I would rather keep some items (like the shows my kids watch over and over and over until I'm reciting the show in my sleep) whenever possible for that 1440m.

So, this leads me to think that we need the ability to set something like --clear-chunk-size=50GB or something like that, so that when we have the free space, it will hold up to the age specified, but when free space is at a premium, the older data gets cycled out.  This may be easier to implement in a disk img so that it is pre-allocated space.

Another way of looking at it could be something like --clear-chunk-space=10GB where the cache will try to maintain at least 10GB free on the disk (or RAM), removing older items before newer.

For now, I've set my --clear-chunk-age=60m, which works fine, but I'd like to be able to more fully utilize my available resources.

Thank you again for such a wonderful program.  It works as is beautifully.

**Comment by dweidenfeld** [comment]
Good idea, it should also be possible to deactivate the  --clear-chunk-age= when  --clear-chunk-space= is activated, so that the tmp is alwas "full" with the last seen movies.

**Comment by xyber411** [comment]
Agreed.  Thank you for already adding it to the 2.1.0 milestone.  I feel like you're one of the most responsive oss devs I've interacted with. :)

**Comment by Ninjouz** [comment]
Thus my request for a LRU buffer cache yesterday ;)

**Comment by soofuzz** [comment]
AHA! This was my exact question. If I can point the cache to a larger say 2TB hard drive and once theres less than 50gb of space to purge the cache and continue on. This is would be pretty good. Not sure if theres a way for it to just purge from cache what plex has already deep analyzed. Going to try this out sometime later today as ACD is killing me speed wise.

**Comment by dweidenfeld** [comment]
Implemented for next release. 
```
  --clear-chunk-max-size int
    	The maximum size of the temporary chunk directory (in byte)
```

If the option is set to a value higher than 0 the LRU caching will take place.

If you want to limit the chunk size to e.g. 50MB:
```
./plexdrive --clear-chunk-max-size=50000000 /tmp/drive
```
