### ISSUE TITLE
add update function

### ISSUE THREAD

**Issue by Givemeyourgits** [dweidenfeld/plexdrive#52]
Would be nice to have a way to easily update to latest version for beta/stable channels without having to go to release page and downloading it, then manually copying it over.

If not, a fixed URL page with all releases would be nice so it can be scripted.

**Comment by RXWatcher1** [comment]
my script works for me:
#!/bin/bash
if [ ! -f cur-plexdrive.txt ]; then
echo '0.0.0' > cur-plexdrive.txt
fi
CVERSION=$(cat cur-plexdrive.txt)
WVERSION=$(curl https://github.com/dweidenfeld/plexdrive/releases/latest -s -L -I -o /dev/null -w '%{url_effective}'| grep -o '[0-9.].[0-9.].[0-9.]')
echo "CVERSION:$CVERSION"
echo "WVERSION:$WVERSION"
if [[ $WVERSION != $CVERSION ]]; then
     wget https://github.com/dweidenfeld/plexdrive/releases/download/${WVERSION}/plexdrive-linux-amd64
     mv plexdrive-linux-amd64 plexdrive
     chmod +x plexdrive
        echo $WVERSION > cur-plexdrive.txt
        echo "New version $WVERSION!"
else
        echo "$CVERSION is up to date !"
fi

**Comment by dweidenfeld** [comment]
This is planned already, it would be included in #35
