### ISSUE TITLE
FUSE mount umask

### ISSUE THREAD

**Issue by ellisonpatterson** [dweidenfeld/plexdrive#53]
Could that be supported for at lease fuse mount and down the road for the application itself?

Thank you :)

**Comment by ellisonpatterson** [comment]
Oh also for the parameters `--uid` and `--gid` it requires an equal to set the integer since it was saying no value could be found when attempting to use them.

**Comment by dweidenfeld** [comment]
It is supposed to require the equal for "long parameters".

The umask should be possible.

**Comment by dweidenfeld** [comment]
Sorry but I am using a third party library for the parameter handling. I have no influence to the parameter handling or the usage output.

**Comment by dweidenfeld** [comment]
Included in next release.
