### ISSUE TITLE
Buffer cache miss if the last block is less than 4K

### ISSUE THREAD

**Issue by fuyar** [dweidenfeld/plexdrive#56]
Hey,

I noticed that for a simple file weighing less than 4K (default block size), a call to Gdrive API was always done even if the file was cached on disk (I set cache age to 24hours).

Found the culprit here : https://github.com/dweidenfeld/plexdrive/blob/master/buffer.go#L124

readAt returns io.EOF if EOF is encountered while reading buf.size (4096).

The same happens for a file with 5000 bytes or any chunk not weighing a multiple of 4096.

I changed the line like this : 
`if n, err := f.ReadAt(buf, fOffset); n > 0 {`

Seems to do the job, no API call are made.

I could do a PR if u want.

Thanks

**Comment by zenjabba** [comment]
Just did it and referenced your username.

**Comment by dweidenfeld** [comment]
Fixed for next version.
