### ISSUE TITLE
Delete Files/Folders

### ISSUE THREAD

**Issue by dweidenfeld** [dweidenfeld/plexdrive#58]
It should be possible to delete items from Google Drive and push them directly into the trash.

**Comment by dweidenfeld** [comment]
Implemented for next release.

**Comment by qnorsten** [comment]
Glad to see this implemented. Will there still be a way to mount is as read-only? Or is delete also enabled?

**Comment by dweidenfeld** [comment]
Good thing. I will also provide a method to mount it read only.

**Comment by dweidenfeld** [comment]
Implemented as fuse option for next version.
```
-o read_only
```
