### ISSUE TITLE
Will --clear-chunk-max-size int have support for T(G,M,K)B?

### ISSUE THREAD

**Issue by xyber411** [dweidenfeld/plexdrive#59]
I'm just wondering if you're including support for us to put in our integer Terabyte, Gigabyte, Megabyte, Kilobyte, or does the integer have to be in bytes?

I'd like to use it as ./plexdrive --clear-chunk-max-size 256GB instead of having to go do maths. :)

Edit: yes, I am a lazy bastard.

**Comment by dany20mh** [comment]
I was about to say that, because it’s hard to put a big number in byte in those flags, and it will be a long code.

**Comment by dweidenfeld** [comment]
I thought about this myself ;)

**Comment by dweidenfeld** [comment]
I really could teach you math ;) hahaha

But in the next release (published today) you can specify the options like this:
```
--clear-chunk-max-size=256g
```
