### ISSUE TITLE
[Feature Request] Download Speed Limit

### ISSUE THREAD

**Issue by Em31Et** [dweidenfeld/plexdrive#60]
Since Google Drive speed is too fast, plexdrive sometimes may used all my bandwidth (300Mbit) for downloading.

**Comment by savahu** [comment]
And why do you not want that?

Does a physical harddisk have a speed limit?

**Comment by Em31Et** [comment]
If plexdrive used all my bandwidth for download, it will affect other users on LAN.

**Comment by animosity22** [comment]
Not a bad feature to add, but definitely take a look at QoS with something like pfSense or even your own router. I just prioritize my other traffic and if plexdrive wants more, it just gets a lower priority.

**Comment by dweidenfeld** [comment]
This is added for the next release. It is implemented by the go's defaults for rate limiting, so basically it could and will exceed the maximum bytes per second, but then it will block further reads for the next n seconds/milliseconds.
I don't see another way to limit the speed, but it should definitely help you not affecting the LANs bandwidth too much.

**Comment by dweidenfeld** [comment]
I had to remove the implementation, because of other features. 
I will put the issue into backlog first...

**Comment by dweidenfeld** [comment]
I added the speed limit as "per chunk speed limit". So each chunk download will be limited to the specified download rate.
This will help you decrease the bandwidth usage, but you cannot say "do not use more that xxx".

You should experiment with the setting yourself, maybe this will help you. I will also try to add a general speed limit, but this will take much more time.
