### ISSUE TITLE
umount on term isn't working correctly

### ISSUE THREAD

**Issue by zenjabba** [dweidenfeld/plexdrive#61]
[SBIN/PLEXDRIVE] [2017-05-12 22:10] INFO   : Unmounting path /mnt/plex
[SBIN/PLEXDRIVE] [2017-05-12 22:10] DEBUG  : exit status 1: fusermount: failed to unmount /mnt/plex: Invalid argument
[SBIN/PLEXDRIVE] [2017-05-12 22:10] DEBUG  : Could not unmount /mnt/plex

root@ns542478:/mnt# umount /mnt/plex
umount: /mnt/plex: not mounted
root@ns542478:/mnt#

so it says it cannot umount it, but umount is telling us it's unmounted.

**Comment by dweidenfeld** [comment]
Should be fixed in release 2.1.0
