### ISSUE TITLE
use /dev/shm for temp storage whilst building cache

### ISSUE THREAD

**Issue by zenjabba** [dweidenfeld/plexdrive#62]
Found that using /dev/shm to build cache makes the performance increase significantly, so suggesting using /dev/shm for cache to allow faster building.

**Comment by djsecrist** [comment]
zenjabba, do you have your /tmp on an SSD or traditional hard drive? I might try your suggestion but am worried about running out of ram.

**Comment by azgul** [comment]
At 35T my cache is 18M so I wouldn't be worried about that at all. But more so worried about #64, because if your QPS is too high you may get temporarily banned from going over your API quota.

**Comment by zenjabba** [comment]
I wouldn't be to worried about the space, but what I did find is you go over your API quota stupidly fast doing it this way. We need to implement throttling in the cache build part of the script.

**Comment by dweidenfeld** [comment]
You already can use /dev/shm, but as you said I need to implement the throttling. This is already described in issue #64
