### ISSUE TITLE
2.1.0 , all videos stop playing at 5 seconds and control c doesn't work have to manually kill

### ISSUE THREAD

**Issue by haljordan2814** [dweidenfeld/plexdrive#63]
As title states, 
I have deleted cache file twice now, restarted plexdrive 2.1.0 and every video in plex stops playing at 5 seconds. No indication in the logs that anything is wrong at all, it shows the same "play" lines as in 2.0.0, just plex stops 5 seconds in. 

I deleted cache, and rebuilt on 2.0.0 and everything is back to working perfectly again. I'm on Ubuntu 16.04 LTS with basic default settings. 

Here's what i do to mount: 
step 1 in screen: 
/bin/fusermount -uz /mnt/vol02/local
/bin/fusermount -uz /home/plex/.gdriveremote
/bin/fusermount -uz /home/plex/media1
/home/plex/.plexdrive/plexdrive -v 2 -o allow_other --uid=1000 --gid=1000 /home/plex/.gdriveremote

step 2 in another window: 
#!/bin/sh
unionfs-fuse \
-o cow,allow_other,direct_io,nonempty,auto_cache,sync_read \
/mnt/vol02/local=RW:/home/plex/.gdriveremote=RO /home/plex/media1
exit

Let me know how and if I can help in any way.

**Comment by raidzx** [comment]
I am seeing this too, most of mine won't even start.

**Comment by zenjabba** [comment]
Same with v2.1 here. I'm just doing direct plexdrive (fuse mount) with no unionfs or anything sexy and seeing the problem.

**Comment by Ninjouz** [comment]
For me it's a little different, download from API is OK, fuse reads seem OK but I got artifact during playing in Plex while it's OK with 2.0 or google video player.

My setup use union-fs.

**Comment by dweidenfeld** [comment]
Okay. I got the problem too. Is fixed in next release (later today).
