### ISSUE TITLE
QPS is not throttled while cache building

### ISSUE THREAD

**Issue by azgul** [dweidenfeld/plexdrive#64]
Going above 10 QPS is going to get your user API quota temporarily banned, so it should be limited to 10 QPS and possibly give us the ability to override it with our custom QPS.

**Comment by zenjabba** [comment]
Suffered the same issue on 2 test builds. This needs to be managed as per google specs.

**Comment by dweidenfeld** [comment]
I implemented a first version for the next release. Unfortunately, I have to implement this "blind" because I didn't have these problems.

Please check the next version and send me a short info if it is okay.

**Comment by animosity22** [comment]
I use SSD for my temp storage and didn't see the issue. I'm not really following the logic of using /dev/shm. If there a 10 QPS, why even both using memory for temp space as you'll easily consume that.

My first cache build took a few minutes with almost 30TB in my GD. Am I just unique in that case or is that what most people see?

**Comment by azgul** [comment]
It is easy to get the 10 QPS increased to the default project QPS of 100 if you are the sole user.

Yes, it takes 2 minutes on my nvme ssd for 28k transactions, but 2-3 hours on hdd. Due to poor SQLite performance, I assume.

**Comment by dweidenfeld** [comment]
I already checked this and yes it is the SQLite performance.
I also wanted to change the SQLite to another storage provider but didn't found anything suitable yet. I am still hoping that tiedot will get better.
Otherwise it could be a solution to use an external database like MongoDB, that should increase the performance heavily but it would be a downside that you will have to start 2 processes just for a "mount".

**Comment by zenjabba** [comment]
I would be MORE than happy to run MongoDB for the performance! It isn't just a mount, it's about getting as much performance out of a known product. You tell me when you want it tested, and I'll test it!

**Comment by dweidenfeld** [comment]
Sorry @zenjabba but I want to have an embedded solution and no external database provider ;)
