### ISSUE TITLE
Anyone use cache flags and actually get them to work?

### ISSUE THREAD

**Issue by raidzx** [dweidenfeld/plexdrive#65]
I am adding these two flags:

/usr/bin/plexdrive -v 3 --clear-chunk-age duration 1000m --clear-chunk-max-size string 110g -o allow_other,allow_non_empty_mount,default_permissions /mnt/my/

But keep getting this error: 

May 13 10:18:54 back systemd[1]: Started Plexdrive.
May 13 10:18:54 back plexdrive[5163]: flag needs an argument: --clear-chunk-age                                                                        
May 13 10:18:54 back plexdrive[5163]: Usage of /usr/bin/plexdrive:

I have ran these flags with and without "duration" and "string" on the end and still get that error. I have also tried setting duration to 1000m0s. What am I doing wrong? Plexdrive works without these flags. I am using newest build that includes max size capability.

Anyway I am back on 2.0.0 since for some reason nothing plays on 2.1.0 even without those flags.

Thanks

**Comment by raidzx** [comment]
Same things happens for --clear-chunk-max-size:


 /usr/bin/plexdrive -v 3 --clear-chunk-max-size 110g -o allow_other,allow_non_empty_mount,default_permissions /mnt/my         

flag needs an argument: --clear-chunk-max-size
Usage of /usr/bin/plexdrive:
  --chunk-size string
        The size of each chunk that is downloaded (units: B, K, M, G) (default "5M")
  --clear-chunk-age duration
        The maximum age of a cached chunk file (default 30m0s)
  --clear-chunk-interval duration
        The time to wait till clearing the chunk directory (default 1m0s)
  --clear-chunk-max-size string
        The maximum size of the temporary chunk directory (units: B, K, M, G)
  -c, --config string
        The path to the configuration directory (default "/root/.plexdrive")
  -o, --fuse-options string
        Fuse mount options (e.g. -fuse-options allow_other,...)
  --gid int
        Set the mounts GID (-1 = default permissions) (default -1)
  --refresh-interval duration
        The time to wait till checking for changes (default 5m0s)
  -t, --temp string
        Path to a temporary directory to store temporary data (default "/tmp")
  --uid int
        Set the mounts UID (-1 = default permissions) (default -1)
  --umask value
        Override the default file permissions
  -v, --verbosity int
        Set the log level (0 = error, 1 = warn, 2 = info, 3 = debug, 4 = trace)
  --version
        Displays program's version information

Version: 

/usr/bin# ./plexdrive --version
2.1.0

**Comment by qnorsten** [comment]
I think that the shorthand flags work like that for example -v 1 while the longer flags need an argument like this --verbose=1 for example. Eventhough the readme is not clear with this. 

So try running /usr/bin/plexdrive -v 3 --clear-chunk-age=1000m --clear-chunk-max-size string=110G -o allow_other,allow_non_empty_mount,default_permissions /mnt/my/

**Comment by raidzx** [comment]
That did it, thanks!

Now for #63 to get fixed and I am good to go
