### ISSUE TITLE
Speedup plexdrive (rclone 2-5x faster) [feature]

### ISSUE THREAD

**Issue by Brandon168** [dweidenfeld/plexdrive#67]
I'm not sure if this is API related (rclone's API versus for rclone versus a self-generated one for plexdrive) or a program issue. If this is not API related then it's likely a feature request versus a bug.

1G file copy speed with plexdrive:  26.8 MiB/s, 63.5 MiB/s, 63.7 MiB/s
1G file copy speed with rclone: 154 MiB/s, 156 MiB/s, 155 MiB/s

**Setup Info:**
_Debugging disabled on both_
rclone v1.36-54-g0c92a64β
plexdrive 2.0 _(2.1 would only copy the first ~5MB or so due to another different issue)_
GCP instance

**Reproduce:**
fallocate -l 1G /tmp/test1g.file
rclone move /tmp/test1g.file gd:/

rclone mount gd:/ /mnt/rcloneplex
plexdrive /mnt/plexdrive
_(Allow file scan to complete)_

pv /mnt/rcloneplex/test1g.file > /dev/null
pv /mnt/plexdrive/test1g.file > /dev/null

**Comment by Brandon168** [comment]
Rough process cpu usage during runs (relative comparison, single core instance):
plexdrive: ~63%
rclone: 95%

**Comment by Brandon168** [comment]
From home (300 Mbps down, 4 cores):

plexdrive: 7.07 MiB/s
rclone: 22.6 MiB/s

**Comment by Brandon168** [comment]
More test data. Testing chunksize differences.
_From the Google instance_

Doubling default chunksize via plexdrive --chunk-size=10485760 /mnt/plexdrive/
= 22.3 MiB/s

Halving default chunksize via plexdrive --chunk-size=2621440 /mnt/plexdrive/
= 16.9 MiB/s

**Comment by animosity22** [comment]
I only need to download so fast to stream and that's the way plexdrive was designed. I think it's overall goal is much different than comparing against a rclone copy.

**Comment by Brandon168** [comment]
That's reasonable post buffer. I have noticed that rclone mounted media starts playing faster, which is what prompted me to test this initially. That said, there is not enough of a difference to prioritize this feature request at this time.

**Comment by dweidenfeld** [comment]
I will put this into backlog. I saw this myself, but I cannot tell you a reason right now.
As @animosity22 already said: It is designed for media playback. If there is no issue, everything is fine by now.

**Comment by animosity22** [comment]
@Brandon168 - I'm not sure what you mean by 'rclone plays faster'. My playback starts roughly in 1 second to less. In my house, they can't tell if it's local or remote. Be careful on your chunk size as if you set it too large, it has to fully download that first chunk and if your connection is slow/over utilized, it'll take some time. Rclone opens the file and starts to fill the buffer up so it's slightly different in the approach.

**Comment by scoopydude2002** [comment]
Can everyone please post their playback experience with various video bitrate using plexdrive? From my test with PV plexdrive can only do about 5MB/s (or 42Mb/s). Of course this is adequate for single stream playing a normal bitrate video 10-20Mb/s. But this is definitely not enough for 4k video or multiple concurrent streams.

**Comment by dany20mh** [comment]
@scoopydude2002 
So I played a 4K video and my cache chunk is 20M and my internet speed is 150/150, and the first time I played the video, buffer kind of close to playback, but still no stop on it, but the second time when you play the video, it uses the chunk cache, which improve your playback.
Mine video starts around 3-7 second cold start and 1-2 second with the cache.

<img width="565" alt="screen shot 2017-05-15 at 6 30 50 pm" src="https://cloud.githubusercontent.com/assets/5872728/26082236/f03cd232-399c-11e7-88b1-99cdd3793f27.png">

**Comment by ladude626** [comment]
@dany20mh Your 4K video is relatively low bitrate at 25mbps. I'm trying to push some 50-70mbps 4K videos and Plexdrive is struggling a bit compared to node-gdrive-fuse. node-gdrive-fuse is a messy app has very good speed.

**Comment by animosity22** [comment]
@ladude626  - What are you writing your /tmp to? I've had 6 streams going pushing down 1080p without a problem streaming back with close to default configurations. It's a pretty sustained transfer rate to and I get quite a bit disk IO too.

**Comment by ladude626** [comment]
@animosity22 I'm writing to HD, which is an SSD cached HD with bcache. I don't have issue with concurrent 1080p videos either, my server currently can do 10 concurrent streams. Probably is with read speed for single high bitrate video. Here's my testing with node-gdrive-fuse vs. Plexdrive copy a 356MB video:

	Plexdrive Speed Test
	|   PROGRESSs   |   RATE   | AVG. RATE |
	 356MiB 0:00:28 [12.6MiB/s] [12.6MiB/s]

	GDrive Node Speed Test
	|   PROGRESSs   |   RATE   | AVG. RATE |
	 356MiB 0:00:12 [  28MiB/s] [  28MiB/s]

**Comment by animosity22** [comment]
With big bitrate files and the chunk size, you are going to see quite a bit of disk IO and also download. This is a 40Mbs file being played alone:

Bandwidth
![image](https://user-images.githubusercontent.com/5088712/26946133-3700daf2-4c5c-11e7-9210-7fc971b256e0.png)

Disk IO
![image](https://user-images.githubusercontent.com/5088712/26946152-4c09e0f6-4c5c-11e7-854a-142ec82cc8e7.png)

By design, the node gdrive is going to be faster is a straight copy test as it downloads things in parallel (I think 5 is the default). It would need to get some type of parallel download as well if you wanted to compare.

**Comment by zenjabba** [comment]
Basically it's only downloading 1 stream, what is needs to do it have N number of steams because some services seem to rate limit each stream.

**Comment by animosity22** [comment]
I may not be following. If I can run 6-10 streams without an issue, why would 1 higher bitrate stream not work?

**Comment by zenjabba** [comment]
basically one request streams one http stream… 10 stream requests streams 10 http streams.

You’ll see a performance increase as more streams come online. When this is is talking about is single file performance

**Comment by animosity22** [comment]
If I double my bitrate on my graphs though, you need quite the beefy setup with both bandwidth and disk IO to stream a high bitrate 4k video regardless if it's single or multiple threads going on.

**Comment by vampywiz17** [comment]
My speed is very slow....:(

About 3-4 MB/sec (my internet speed is 130Mbit)

here my config:


```
[Unit]
Description=Plexdrive
AssertPathIsDirectory=/mnt/plexdrive
After=network-online.target

[Service]
Type=simple
ExecStartPre=/bin/sleep 80
ExecStart=/usr/bin/plexdrive -v 2 -m localhost /mnt/plexdrive
ExecStop=/bin/fusermount -u /mnt/plexdrive
Restart=on-abort

[Install]
WantedBy=default.target
```

**Comment by Brandon168** [comment]
@vampywiz17 You might try removing verbosity. That improved speeds for me a little bit.

**Comment by vampywiz17** [comment]
@Brandon168  OK i try it.

**Comment by dweidenfeld** [comment]
I think this topic can be closed for the next release ;)

**Comment by syaifulnizamyahya** [comment]
For the past few weeks, i have been using pre release plexdrive and I must say the theres a lot of improvement regarding network speed efficiency. 

Cant wait for the next official release.

Great job @dweidenfeld
