### ISSUE TITLE
Better and Detailed Tutorial to install and config Plexdrive

### ISSUE THREAD

**Issue by Massaguana** [dweidenfeld/plexdrive#70]
Hello,

Plexdrive looks good. But my basic linux expertise are not enough to bring it to work...

Is it possible  to create detailed Tutorials for CentOS or other linux systems?

Thanks
Massaguana

**Comment by Qwatuz** [comment]
I used this guide here:

[https://forum.rclone.org/t/best-mount-settings-for-streaming-plex/344/545](url)

Here is an updated version:

Go and create your own api key: [https://rclone.org/drive/#making-your-own-client-id](url)

Create a directory in your home directory
mkdir ~/.plexdrive
Create a file in this directory using a text editor, vi or nano, in this example i used nano

cd ~/.plexdrive

nano config.json

Add this using the details you got when you created your own api key

{
"clientId": "add your id here",
"clientSecret": "add your secret here"
}


To save nano press CTRL + O, enter, then CTRL + X to exit.
Download the binary release:

wget https://github.com/dweidenfeld/plexdrive/releases/download/2.1.0/plexdrive-linux-amd64 - Remember to always visit github and replace this link with the latest download.

Rename the file to plexdrive for easy execute.

mv plexdrive-linux-amd64 plexdrive

Put it somewhere, I put mine in /usr/local/bin but you could put it in /usr/bin or /usr/sbin
If you chose a different location you will need to change the paths below

sudo mv plexdrive /usr/local/bin/

cd /usr/local/bin/

sudo chown root:root /usr/local/bin/plexdrive

sudo chmod 755 /usr/local/bin/plexdrive

Create a directory you want to mount it on

mkdir /path/to/mount

then mount it

(It has been suggested to run in a screen to allow the cache to be made)

screen -S plexdrive

(depending on where you put it you may or may not need sudo in the following command)

sudo plexdrive --uid=1002 --gid=1002 -o allow_other -v 2 --refresh-interval=1m /path/to/mount (This is the mount directory you created above)

To detach from the screen press CTRL+A Then the D key.

screen -r plexdrive to go back onto the screen.

When it starts, It should give some instructions to authenticate your google drive

Follow the instructions and Wait... It will take some time to create the cache.

You should then see your google drive at /path/to/mount

**Comment by Massaguana** [comment]
Thanks for this... i use in moment this: https://github.com/hthighway/scripts/tree/master/plexdrive

**Comment by dweidenfeld** [comment]
If you have some ideas, please create a SETUP.md and put a detailed description in there and post a PR.

**Comment by Massaguana** [comment]
@Qwatuz Your Tutorial works... thanks. But do you know how it works to mount an with rclone crypted drive?

**Comment by qnorsten** [comment]
@Massaguana  just create a regulular rclone crypt remote with rclone config and point that to the folder you mounted in plex and then mount the rclone as usually. 

For example if you have plexdrive mounted in /home/user/plexdrive and you have an encrypted folder in there called crypt. Just point the remote field in the rclone crypt config to /home/user/plexdrive/crypt. 
Then regular rclone mount:)

**Comment by Massaguana** [comment]
hmm, not sure i understand all....

this are my normal "working" rclone mount:
`nohup rclone mount -v --allow-non-empty --allow-other GSuiteCrypt: /var/lib/plexmediaserver/Media/ &`

what i understand is mount the rclone drive in my folder and do the same with plexdrive in the same folder? Alsop with nohup?

**Comment by zudiguy** [comment]
I;m getting this error  [PLEXDRIVE] [2017-05-17 10:26] ERROR  : Could not initialize Google Drive Client

**Comment by Massaguana** [comment]
Do you have create you own api key?

**Comment by zudiguy** [comment]
Yes I created one maybe I did something wrong..This has been driving me insane trying to get this work for days now

**Comment by zudiguy** [comment]
Now I get mount helper error: fusermount: fuse device not found, try 'modprobe fuse' first

**Comment by RXWatcher1** [comment]
@ `apt-get install fuse`

**Comment by zudiguy** [comment]
It's already installed

**Comment by dany20mh** [comment]
@zudiguy 
I saw this, it’s a little bit old, but try it.
http://www.linuxquestions.org/questions/linux-server-73/fuse-device-not-found-try-%27modprobe-fuse%27-first-centos-5-4-a-4175419920/

**Comment by zudiguy** [comment]
Is it not going to run without doing this?

**Comment by dany20mh** [comment]
@zudiguy 
Honestly I’m not using Linux, but you missing some requirement and I’m using MacOS and here all I need is osxfuse and it works like charm.

**Comment by RXWatcher1** [comment]
@zudiguy 
What flavor of linux are you using and is this on a VPS by chance?

**Comment by zudiguy** [comment]
Ubuntu 16.04 X64

**Comment by RXWatcher1** [comment]
@zudiguy on a VPS? I ask because specific types of VPS have issues running fuse unless enabled by the vendor.

**Comment by zudiguy** [comment]
ssdnodes They already enabled fuse on the server when I 1st statred

**Comment by RXWatcher1** [comment]
I would reboot it and if its not working go back to them and have then validate.
I run physical servers and all I needed to do was apt-get install fuse.

**Comment by billyprice1** [comment]
The size of the cache is like 30gb can i fix that

**Comment by SimonLefisch** [comment]
I'm having trouble with plexdrive staying mounted after a reboot. I have a script that's supposed to run at startup and it is enabled, however after a reboot on my VPS (Ubuntu) my Google Drive does not get mounted. Below is my script located in /lib/systemd/system/plexdrive.service

```
[Unit]
Description=Mount Google to /mnt/GoogleDrive
After=syslog.target local-fs.target network.target

[Service]
Type=simple
User=root
Group=root
ExecStartPre=-/bin/mkdir /mnt/GoogleDrive
ExecStart=/usr/local/bin/plexdrive \
  —uid=1002 \
  —gid=1002 \
  --clear-chunk-max-size=20G \
  --fuse-options=allow_other \
  --temp=/tmp/GoogleDrive-temp \
  —verbosity=2 \
  /mnt/GoogleDrive
ExecStop=/bin/fusermount -u -z /mnt/GoogleDrive
ExecStop=/bin/rmdir /mnt/GoogleDrive
ExecStop=/bin/rm -r /tmp/GoogleDrive-temp
Restart=always

[Install]
WantedBy=default.target
```

Can anyone tell me what I'm doing wrong?

**Comment by tsueri** [comment]
did anyone try to use plexdrive in a freebsd-jail?

**Comment by Meowx3** [comment]
I'm working to get it running on FreeNAS 11. It won't work in a jail until fuse is made jail friendly. I've it nearly working in root which in turn is mounted into my plex jail. Just dealing with issues with plexdrive wanting to access home even when you give other targets.

**Comment by seanmt13** [comment]
So when i run the command: sudo plexdrive --uid=1002 --gid=1002 -o allow_other -v 2 --refresh-interval=1m /googleDrive/ I get the following error: [PLEXDRIVE] [2018-02-17 09:10] ERROR  : Command /googleDrive/ not found. I know the folder exists and i have chmod it to 777 and chown to root:root is there something i am doing wrong?

**Comment by zenjabba** [comment]
Try using the mount command before the directory

**Comment by jflatz** [comment]
@tsueri or @Meowx3: Have either of you got it setup in a FreeNAS jail?

**Comment by Meowx3** [comment]
No, but it's not a concern anymore. I mucked around a bit and got it
partially working, but trust me it's a very bad idea. FUSE is not meant to
work in jails, and plexdrive needs FUSE. However, rclone 1.39 added it's
own caching function that arguably obsoleted plexdrive. It's not a
generally recommended thing, but you can set up the cached drive on the
base of FreeNAS and share to a jail and it works great. Once the official
repo is updated (which will be after  Freshports is updated) you can do it
this way. In the meantime, you risk breaking the base system by forcing
1.39 on.
