### ISSUE TITLE
Question about local copies

### ISSUE THREAD

**Issue by sidscience89** [dweidenfeld/plexdrive#71]
I have a google drive account, and I have computers at 2 different locations. Both computers are running OSX.

On computer A, I plan on keeping all the content local, but letting the folders sync UP to the gdrive.

On computer B, there is much less storage and higher download capacity, so I'd rather let it steam most of the stuff down.

How would I setup Plexdrive to encrypt it, but always leave the copy on computer A forever?

**Comment by Em31Et** [comment]
You want the setup 2 Plex Media Server on 2 computer?

**Comment by Brandon168** [comment]
You can achieve this by adding rclone to the mix. Essentially, rclone does all of the uploading on computer A and a combination of plexdrive and rclone will do the downloading+decrypting for computer B.

**Computer A:**
* _Uploads occur via rclone sync_
* _All uploads are local encrypted first_

[local_file] -> [rclone crypt] -> [rclone to google drive]

**rclone config file example:**

[googledrive]
type = drive
client_id =
client_secret =
token = insert_token

[googledrivecrypt]
type = crypt
remote = googledrive:/encrypted_folder
filename_encryption = standard
password = super_long_key
password2 =

**Syncing up**
rclone sync /home/local/media googledrivecrypt:/



**Computer B:**
* _Will use plexdrive to grab the encrypted files on the fly_
* _Will use rclone to decrypt the plexdrive encrypted files on the fly_

[google drive encrypted files] -> [plexdrive to fetch] -> [rclone local to decrypt] -> [local_file_decrypted]


**rclone config**
[google-drive-decrypt]
type = crypt
remote = local:/mnt/plexdrive/encrypted_folder
filename_encryption = standard (or one of the other options)
password = insert-long-encryption-key-here-again
password2 =

**Basic mounts** 
_See rclone forums for cleaner upstart mount. See plexdrive wiki for cleaner upstart mount)_

plexdrive /mnt/plexdrive
rclone mount google-drive-decrypt:/ /mnt/media

At this point you should clean decrypted files at /mnt/media. _The raw downloading of files will be courtesy of plexdrive and the decryption of said files courtesy of rclone_

**Comment by Brandon168** [comment]
Note that two separate plex servers will be running, each with their own copy of metadata. See plex forums on how to keep show/movie watch progress in sync between servers.

**Comment by hjtech** [comment]
I have a similar setup, but on Computer A, I need to be able not to copy but automatically **move** the files: [local file] -> [rclone move to Google Drive] -> [delete local file]. This should happen automatically so I don't have to manually execute the commands to sync and delete source. Any thoughts?

**Comment by Brandon168** [comment]
Use rclone move for this. Here is an example bash script which ensures one copy is running at a time (I found this on the web somewhere and slightly tweaked it. I take no credit):

-----
#!/bin/bash

if pidof -o %PPID -x "rclone-cron.sh"; then
 echo "$(date "+%d.%m.%Y %T") EXIT: rclone-cron.sh already running."
 exit 1
fi

echo "Starting rclone-move at $(date "+%d.%m.%Y %T")"
/usr/local/bin/rclone move path/to/local.folder remotepath:/ -v --log-file=/var/log/rclone-sync.log
exit

-----

Just put something like that ^ in a crontab to run it on a schedule

**Comment by dweidenfeld** [comment]
@Brandon168 s answer is very good. In case there is no actual problem here I close this issue.
