### ISSUE TITLE
Unmounting every night

### ISSUE THREAD

**Issue by hjtech** [dweidenfeld/plexdrive#72]
This has been happening every night for the past 3-4 days, not sure why. I have Plex set to scan the library automatically but generating thumbnails is disabled. 

> [PLEXDRIVE] [2017-05-14 04:35] DEBUG  : Cleaning empty directory /tmp/chunks/0B1OIT_N-PGG6TWIwQnhiMVVzTG8
[PLEXDRIVE] [2017-05-14 04:35] DEBUG  : Checking for changes
[PLEXDRIVE] [2017-05-14 04:35] DEBUG  : Getting change id from cache
[PLEXDRIVE] [2017-05-14 04:35] WARNING: stream error: stream ID 3403; INTERNAL_ERROR
[PLEXDRIVE] [2017-05-14 04:35] INFO   : Unmounting path /Volumes/GDrive
[PLEXDRIVE] [2017-05-14 04:35] DEBUG  : Closing cache connection

**Comment by dany20mh** [comment]
This happened to me last night too, and it was around 3am, which said stream error and then unmount, this happened when I was on 2.1.0

**Comment by dweidenfeld** [comment]
Okay. This seems to be an issue in the buffer. I need to increase the error logging and add som retry routine.
On the roadmap for the next version ;)

**Comment by dweidenfeld** [comment]
I improved the logging behavior. This will not fix the bug, but it will tell me where the error occurs. 
Please test the next version and append the error log, if it happens again, so that I can fix the error.

**Comment by zenjabba** [comment]
May 19 06:38:14 ip-172-31-7-33 plexdrive: #033[0mpanic: runtime error: invalid memory address or nil pointer dereference
May 19 06:38:14 ip-172-31-7-33 plexdrive: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7c0b28]
May 19 06:38:14 ip-172-31-7-33 plexdrive: goroutine 22349542 [running]:
May 19 06:38:14 ip-172-31-7-33 plexdrive: main.deleteOldestFile.func1(0xc4211df9c0, 0x3e, 0x0, 0x0, 0xd646c0, 0xc4218bcba0, 0x0, 0x0)
May 19 06:38:14 ip-172-31-7-33 plexdrive: /home/thompsons/go/src/github.com/dweidenfeld/plexdrive/buffer.go:271 +0x38
May 19 06:38:14 ip-172-31-7-33 plexdrive: path/filepath.walk(0xc4211df900, 0x33, 0xd6b280, 0xc420a33ad0, 0xc420a04680, 0x0, 0x0)
May 19 06:38:14 ip-172-31-7-33 plexdrive: /usr/lib/go-1.8/src/path/filepath/path.go:372 +0x2fe
May 19 06:38:14 ip-172-31-7-33 plexdrive: path/filepath.walk(0xc42113bf80, 0x16, 0xd6b280, 0xc42066cdd0, 0xc420a04680, 0x0, 0x0)
May 19 06:38:14 ip-172-31-7-33 plexdrive: /usr/lib/go-1.8/src/path/filepath/path.go:376 +0x414
May 19 06:38:14 ip-172-31-7-33 plexdrive: path/filepath.walk(0xc4201ce490, 0xf, 0xd6b280, 0xc420b54d00, 0xc420a04680, 0x0, 0x20)
May 19 06:38:14 ip-172-31-7-33 plexdrive: /usr/lib/go-1.8/src/path/filepath/path.go:376 +0x414
May 19 06:38:14 ip-172-31-7-33 plexdrive: path/filepath.Walk(0xc4201ce490, 0xf, 0xc420a04680, 0x8ed740, 0x0)
May 19 06:38:14 ip-172-31-7-33 plexdrive: /usr/lib/go-1.8/src/path/filepath/path.go:398 +0x14c
May 19 06:38:14 ip-172-31-7-33 plexdrive: main.deleteOldestFile(0xc4201ce490, 0xf, 0x18ffdeba82, 0x0)
May 19 06:38:14 ip-172-31-7-33 plexdrive: /home/thompsons/go/src/github.com/dweidenfeld/plexdrive/buffer.go:279 +0x119
May 19 06:38:14 ip-172-31-7-33 plexdrive: main.cleanChunkDir(0xc4201ce490, 0xf, 0xc4204d4240, 0x438c58)
May 19 06:38:14 ip-172-31-7-33 plexdrive: /home/thompsons/go/src/github.com/dweidenfeld/plexdrive/buffer.go:257 +0x98
May 19 06:38:14 ip-172-31-7-33 plexdrive: main.(*Buffer).ReadBytes.func2()
May 19 06:38:14 ip-172-31-7-33 plexdrive: /home/thompsons/go/src/github.com/dweidenfeld/plexdrive/buffer.go:170 +0x3d
May 19 06:38:14 ip-172-31-7-33 plexdrive: created by main.(*Buffer).ReadBytes
May 19 06:38:14 ip-172-31-7-33 plexdrive: /home/thompsons/go/src/github.com/dweidenfeld/plexdrive/buffer.go:174 +0x1393
May 19 06:38:14 ip-172-31-7-33 systemd: plexdrive.service: main process exited, code=exited, status=2/INVALIDARGUMENT

**Comment by fucheeno** [comment]
I too have similar issues, the same as zenjabba. Do we know what is causing it yet?

**Comment by kconat** [comment]
exact same stacktrace here.

**Comment by kconat** [comment]
here is some info of mine. i guess those:

: Could not read file  message before the crash may be an issue. seems it tries to delete chunks which are not even there. 

maybe there is some error handling missing, when a junk request fails at google?

[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Requesting object 0B8vkAPmA2yhMOTlLdTBOQTVzems bytes 11576279040 - 11607736320 from API
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : <nil>
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Could not read file /data/tmp/chunks/0B8vkAPmA2yhMOTlLdTBOQTVzems/11544821760 at 135168
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Requesting object 0B8vkAPmA2yhMOTlLdTBOQTVzems bytes 11544821760 - 11576279040 from API
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Deleting oldest chunk file /data/tmp/chunks/0B8vkAPmA2yhMUWx5NF8yMlVuN2c/1572864000
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Deleting oldest chunk file /data/tmp/chunks/0B8vkAPmA2yhMUWx5NF8yMlVuN2c/1572864000
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Requesting object 0B8vkAPmA2yhMOTlLdTBOQTVzems bytes 11607736320 - 11639193600 from API
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Deleting oldest chunk file /data/tmp/chunks/0B8vkAPmA2yhMUWx5NF8yMlVuN2c/1604321280
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Requesting object 0B8vkAPmA2yhMOTlLdTBOQTVzems bytes 11639193600 - 11670650880 from API
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Deleting oldest chunk file /data/tmp/chunks/0B8vkAPmA2yhMUWx5NF8yMlVuN2c/1635778560
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Requesting object 0B8vkAPmA2yhMOTlLdTBOQTVzems bytes 11639193600 - 11670650880 from API
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Requesting object 0B8vkAPmA2yhMOTlLdTBOQTVzems bytes 11639193600 - 11670650880 from API
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Deleting oldest chunk file /data/tmp/chunks/0B8vkAPmA2yhMUWx5NF8yMlVuN2c/1667235840
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Deleting oldest chunk file /data/tmp/chunks/0B8vkAPmA2yhMUWx5NF8yMlVuN2c/1667235840
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Requesting object 0B8vkAPmA2yhMOTlLdTBOQTVzems bytes 11670650880 - 11702108160 from API
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Deleting oldest chunk file /data/tmp/chunks/0B8vkAPmA2yhMUWx5NF8yMlVuN2c/1698693120
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : <nil>
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Could not read file /data/tmp/chunks/0B8vkAPmA2yhMOTlLdTBOQTVzems/11639193600 at 135168
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Requesting object 0B8vkAPmA2yhMOTlLdTBOQTVzems bytes 11639193600 - 11670650880 from API
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : <nil>
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Could not read file /data/tmp/chunks/0B8vkAPmA2yhMOTlLdTBOQTVzems/11639193600 at 266240
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Requesting object 0B8vkAPmA2yhMOTlLdTBOQTVzems bytes 11639193600 - 11670650880 from API
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Deleting oldest chunk file /data/tmp/chunks/0B8vkAPmA2yhMUWx5NF8yMlVuN2c/1730150400
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Deleting oldest chunk file /data/tmp/chunks/0B8vkAPmA2yhMUWx5NF8yMlVuN2c/1730150400
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Requesting object 0B8vkAPmA2yhMOTlLdTBOQTVzems bytes 11702108160 - 11733565440 from API
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Deleting oldest chunk file /data/tmp/chunks/0B8vkAPmA2yhMUWx5NF8yMlVuN2c/1761607680
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Requesting object 0B8vkAPmA2yhMOTlLdTBOQTVzems bytes 11702108160 - 11733565440 from API
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Requesting object 0B8vkAPmA2yhMOTlLdTBOQTVzems bytes 11702108160 - 11733565440 from API
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Deleting oldest chunk file /data/tmp/chunks/0B8vkAPmA2yhMUWx5NF8yMlVuN2c/1793064960
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Deleting oldest chunk file /data/tmp/chunks/0B8vkAPmA2yhMUWx5NF8yMlVuN2c/1793064960
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Requesting object 0B8vkAPmA2yhMOTlLdTBOQTVzems bytes 11733565440 - 11765022720 from API
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : <nil>
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Could not read file /data/tmp/chunks/0B8vkAPmA2yhMOTlLdTBOQTVzems/11702108160 at 135168
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Requesting object 0B8vkAPmA2yhMOTlLdTBOQTVzems bytes 11702108160 - 11733565440 from API
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Deleting oldest chunk file /data/tmp/chunks/0B8vkAPmA2yhMUWx5NF8yMlVuN2c/1824522240
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Deleting oldest chunk file /data/tmp/chunks/0B8vkAPmA2yhMUWx5NF8yMlVuN2c/1824522240
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Requesting object 0B8vkAPmA2yhMOTlLdTBOQTVzems bytes 11765022720 - 11796480000 from API
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Deleting oldest chunk file /data/tmp/chunks/0B8vkAPmA2yhMUWx5NF8yMlVuN2c/1855979520
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Requesting object 0B8vkAPmA2yhMOTlLdTBOQTVzems bytes 11796480000 - 11827937280 from API
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Deleting oldest chunk file /data/tmp/chunks/0B8vkAPmA2yhMUWx5NF8yMlVuN2c/1887436800
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Requesting object 0B8vkAPmA2yhMOTlLdTBOQTVzems bytes 11796480000 - 11827937280 from API
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Requesting object 0B8vkAPmA2yhMOTlLdTBOQTVzems bytes 11796480000 - 11827937280 from API
[ROOT/PLEXDRIVE-LINUX-AMD64] [2017-05-29 06:57] DEBUG  : Deleting oldest chunk file /data/tmp/chunks/0B8vkAPmA2yhMUWx5NF8yMlVuN2c/1918894080
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7c0b08]

goroutine 6320682 [running]:
main.deleteOldestFile.func1(0xc421154980, 0x38, 0x0, 0x0, 0xd646e0, 0xc420d0c060, 0x0, 0x0)
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:271 +0x38
path/filepath.walk(0xc420e2df80, 0x2d, 0xd6b2a0, 0xc421607ad0, 0xc420ea3ba0, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:372 +0x2fe
path/filepath.walk(0xc4201ce430, 0x10, 0xd6b2a0, 0xc420554d00, 0xc420ea3ba0, 0x0, 0x20)
        /usr/local/go/src/path/filepath/path.go:376 +0x414
path/filepath.Walk(0xc4201ce430, 0x10, 0xc420ea3ba0, 0x8ed800, 0x0)
        /usr/local/go/src/path/filepath/path.go:398 +0x14c
main.deleteOldestFile(0xc4201ce430, 0x10, 0x1a61084c88, 0x0)
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:279 +0x119
main.cleanChunkDir(0xc4201ce430, 0x10, 0xc4204be180, 0x438c48)
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:257 +0x98
main.(*Buffer).ReadBytes.func2()
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:170 +0x3d
created by main.(*Buffer).ReadBytes
        /go/src/github.com/dweidenfeld/plexdrive/buffer.go:174 +0x1393
/root/plexdrive-linux-amd64 -v 3 -o allow_other,read_only -t /data/tmp      429.30s user 162.26s system 5% cpu 2:53:27.22 total

**Comment by dweidenfeld** [comment]
Should be fixed in next release.
