### ISSUE TITLE
plexdrive eating bandwidth

### ISSUE THREAD

**Issue by memnos** [dweidenfeld/plexdrive#74]
I don't know why, but sometime after i started plexdrive, it beings to eat all my bandwidth and i have to kill it.
I don't know if it is normal or not.
Using nethogs i see this:
26071 root     /home/fabio/.plexdrive/plexdrive                                        eth0      51.230    1395.809 KB/sec

While all my total bandwidth is 1875 KB/sec

Any idea if i have to set something up?

Tnx

**Comment by animosity22** [comment]
What's the processes that are hitting the mount?

You can run as root:

lsof <mountpoint>

plexdrive itself doesn't really do anything other than the first cache build.

**Comment by dweidenfeld** [comment]
@memnos 
Is this the first run of plexdrive? Then it is the initial cache build like @animosity22 already said.

**Comment by memnos** [comment]
No, it is not the first time.
I tried for some days, and i realized during that period internet was very slow. I thought it was a problem with my provider. I called them they told me they had no problem so i investigated and realized that killing plexdrive my problem was solved.
I don't know what plexdrive was doing.
Can you suggest what i can try to check to understand what was causing this? Maybe some kind of plex scan was causing this?

**Comment by dweidenfeld** [comment]
So your complete plexdrive cache has been built successfully? 
If you just start plexdrive without plex, is the bandwidth high, too?

**Comment by memnos** [comment]
Yes, i think cache has been built successfully. Is there i way to check? I can see all my gdrive files.
When i start plexdrive all is ok, 
Bandwidth problems appear sometime after. But i cannot identify why.

**Comment by memnos** [comment]
What i didn't say is that i use plexdrive whit rclone as my data in gdrive is encrypted

**Comment by memnos** [comment]
OK, maybe i found out something usefull.
Bandwidth went  down when i made plex analize of i movie.
This is the speedtest before performe it:
`FABIO-NUC ~/scripts # ./speedtest
Hosted by *** [45.12 km]: 54.859 ms
Testing download speed................................................................................
Download: 15.15 Mbit/s
Testing upload speed....................................................................................................
Upload: 0.90 Mbit/s`

And this is after analize:

`FABIO-NUC ~/scripts # ./speedtest
Hosted by **** [45.12 km]: 110.093 ms
Testing download speed................................................................................
Download: 5.30 Mbit/s
Testing upload speed....................................................................................................
Upload: 0.88 Mbit/s`

The problem is that also a lot of time after finished analize bandwidth continue to go down instead of growing.

**Comment by memnos** [comment]
More info.
If i kill plex all is ok. So the problem is what plex does with plexdrive.
Any idea?

**Comment by dweidenfeld** [comment]
Okay, if a movie has not been scanned for the first time in plex, plex has to download some information for the analyzation process.
So there is nothing you can do, but waiting for plex to finish its first scan. After the first scan, everything should be fine because a rescan of plex doesn't download those metadata again.

**Comment by memnos** [comment]
The strange is that if i press analize on a single movie bandwidth stays down also after much time it has finished to analize. It seems that bandwidth never goes up again.

**Comment by dweidenfeld** [comment]
That is exactly what I expected. The metadata is stored in an internal plex database. So no refetching of the metadata from the file is needed. 

How large is your library? I am indexing a crypted mount with around 3TB right now. The initial load is relatively high, but after all scans are done there is no bandwidth consumption anymore.
Maybe you must give plex/plexdrive some time to rest :smile:

**Comment by memnos** [comment]
OK, i'll try what you suggested. 👍

**Comment by animosity22** [comment]
What library settings are you using as well?  You can take a look at https://github.com/ajkis/scripts as he's got some library stats and such in there so you can see what it is doing. Depending on if you need to analyze things and what your scheduled tasks are, it sounds like you have a lot of plex working going on:

My library stats:
```
felix@plex:~$ plex-library-stats
16.05.2017 06:18:57 PLEX LIBRARY STATS
Media items in Libraries
Library =   TV
  Items = 13573

Library =  Movies
  Items = 1416

Library = Exercise
  Items = 270

Library = MMA
  Items = 42

Library = Misc
  Items = 7

16991 files in library
0 files missing analyzation info
0 media_parts marked as deleted
0 metadata_items marked as deleted
0 directories marked as deleted
15307 files missing deep analyzation info.
```

**Comment by memnos** [comment]
Mhhh, there is something i don't understand.
I understand that if i mount gdrive with plexdrive and make a scan with plex it makes all my bandwidth busy, and my connection becomes unusable.
I've just try to do the same with plex (scan) mounting gdrive with rclone and bandwidth used goes up and down between 300 KB/sec and 1100 KB/sec. With plexdrive i have a costant using of 1.500/1.600 KB/sec wich is all my bandwidth.
In this situation for me plexdrive is unusable. Maybe it should be useful a sort of bandwidth limit, if it is possibile.
Is this only my situation or someone else experienced this?
Tnx for any hint. I'd like very much to have the possibility to use plexdrive.

**Comment by animosity22** [comment]
Rclone doesn't support mod times. GD does support mod times. If you flip flop, you'll get into a spot that you need to rescan things as plex thinks the files have changed.

You have to let a full scan and analyze finish and then life returns back to normal once that is completed.

You can see the scan progress by checking the "Plex Scanner Log" or using the activity page in plex to see what it is doing.

Unless he adds a bandwidth limiter flag, it will do that. I usually ran my scans overnight and I grouped them up. The plex-library-stats will give you an idea how much you have to analyze.

Since my library is fully analyzed at this point, a scan just takes about 2 minutes for my entire 30TB library since it just checks the cached metadata of the files (file size/timestamp).

**Comment by dweidenfeld** [comment]
@animosity22  I think maybe @memnos total bandwidth is too low to let the scan finish. 
I rebuilt my cache completely and deleted the complete plex library (3TB). It used some bandwidth of my 100mb/s connection for around 30 minutes, then it was finished and now no bandwidth is used at all.

**Comment by memnos** [comment]
@animosity22 i think you are right. In fact i've got problem only in my house, while i have a vps using plexdrive with no problem at all, with a connection of 100mb/s.

**Comment by animosity22** [comment]
@dweidenfeld  - I wasn't talking about the plexdrive cache. That finishes pretty fast. I meant the first scan and analyze in "Plex Media Server". Depending on the size of the library/speed of connection, it will define how long that first scan and analyze will take.

**Comment by dweidenfeld** [comment]
I don't think this is a problem with plexdrive. Please check out https://plexdrive.slack.com for help.

**Comment by memnos** [comment]
How can i have credential to enter in https://plexdrive.slack.com?

**Comment by scantem** [comment]
A link is on the README - https://plexdrive.slack.com/shared_invite/MTg1NTg5NzY2Njc4LTE0OTUwNDU3NzAtMjJjNWRiMTAxMg
