### ISSUE TITLE
Errors on Plex Scan

### ISSUE THREAD

**Issue by dabigc** [dweidenfeld/plexdrive#76]
Hi there,

After a fresh/first time install this morning I'm getting the error below for every item when Plex performs a scan. What did I do that would cause this?

Edit: The initial and subsequent caching works as expected, it's just when Plex runs a scan that I get these errors for every piece of media in the library. Playback also doesn't work though. 

[USR/BIN/./PLEXDRIVE] [2017-05-15 13:23] WARNING: Wrong status code &{403 Forbidden 403 HTTP/2.0 2 0 map[Server:[UploadServer] Content-Type:[text/html; charset=UTF-8] X-Guploader-Uploadid:[AEnB2UqOAphdlaCnhnUrEpjxf7IdgGo4luvD-TbuVEHqOwv0w54GZZVCyfcqTW1dr2cpxUpYnO6pZernO6u_vt3PNi_2ja1xHA] Access-Control-Allow-Methods:[GET,OPTIONS] Date:[Mon, 15 May 2017 17:23:37 GMT] Cache-Control:[private, max-age=0] Content-Length:[0] Access-Control-Allow-Origin:[*] Access-Control-Allow-Credentials:[false] Access-Control-Allow-Headers:[Accept, Accept-Language, Authorization, Cache-Control, Content-Disposition, Content-Encoding, Content-Language, Content-Length, Content-MD5, Content-Range, Content-Type, Date, GData-Version, Host, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Origin, OriginToken, Pragma, Range, Slug, Transfer-Encoding, Want-Digest, X-ClientDetails, X-GData-Client, X-GData-Key, X-Goog-AuthUser, X-Goog-PageId, X-Goog-Encode-Response-If-Executable, X-Goog-Correlation-Id, X-Goog-Request-Info, X-Goog-Experiments, x-goog-iam-authority-selector, x-goog-iam-authorization-token, X-Goog-Spatula, X-Goog-Upload-Command, X-Goog-Upload-Content-Disposition, X-Goog-Upload-Content-Length, X-Goog-Upload-Content-Type, X-Goog-Upload-File-Name, X-Goog-Upload-Offset, X-Goog-Upload-Protocol, X-Goog-Visitor-Id, X-HTTP-Method-Override, X-JavaScript-User-Agent, X-Pan-Versionid, X-Proxied-User-IP, X-Origin, X-Referer, X-Requested-With, X-Upload-Content-Length, X-Upload-Content-Type, X-Use-HTTP-Status-Code-Override, X-Ios-Bundle-Identifier, X-Android-Package, X-Ariane-Xsrf-Token, X-YouTube-VVT, X-YouTube-Page-CL, X-YouTube-Page-Timestamp, X-Goog-Meeting-Botguardid, X-Goog-Meeting-Debugid, X-Goog-Meeting-Token, X-Client-Data, X-Sfdc-Authorization] Expires:[Mon, 15 May 2017 17:23:37 GMT] Alt-Svc:[quic=":443"; ma=2592000; v="37,36,35"]] 0xc4211f2180 0 [] false false map[] 0xc420e69700 0xc4201db760}
[USR/BIN/./PLEXDRIVE] [2017-05-15 13:23] WARNING: Wrong status code &{403 Forbidden 403 HTTP/2.0 2 0 map[Server:[UploadServer] Content-Type:[text/html; charset=UTF-8] Alt-Svc:[quic=":443"; ma=2592000; v="37,36,35"] Access-Control-Allow-Origin:[*] Access-Control-Allow-Credentials:[false] Access-Control-Allow-Headers:[Accept, Accept-Language, Authorization, Cache-Control, Content-Disposition, Content-Encoding, Content-Language, Content-Length, Content-MD5, Content-Range, Content-Type, Date, GData-Version, Host, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Origin, OriginToken, Pragma, Range, Slug, Transfer-Encoding, Want-Digest, X-ClientDetails, X-GData-Client, X-GData-Key, X-Goog-AuthUser, X-Goog-PageId, X-Goog-Encode-Response-If-Executable, X-Goog-Correlation-Id, X-Goog-Request-Info, X-Goog-Experiments, x-goog-iam-authority-selector, x-goog-iam-authorization-token, X-Goog-Spatula, X-Goog-Upload-Command, X-Goog-Upload-Content-Disposition, X-Goog-Upload-Content-Length, X-Goog-Upload-Content-Type, X-Goog-Upload-File-Name, X-Goog-Upload-Offset, X-Goog-Upload-Protocol, X-Goog-Visitor-Id, X-HTTP-Method-Override, X-JavaScript-User-Agent, X-Pan-Versionid, X-Proxied-User-IP, X-Origin, X-Referer, X-Requested-With, X-Upload-Content-Length, X-Upload-Content-Type, X-Use-HTTP-Status-Code-Override, X-Ios-Bundle-Identifier, X-Android-Package, X-Ariane-Xsrf-Token, X-YouTube-VVT, X-YouTube-Page-CL, X-YouTube-Page-Timestamp, X-Goog-Meeting-Botguardid, X-Goog-Meeting-Debugid, X-Goog-Meeting-Token, X-Client-Data, X-Sfdc-Authorization] Date:[Mon, 15 May 2017 17:23:37 GMT] Content-Length:[0] X-Guploader-Uploadid:[AEnB2UrSCns9swt4k17lT1aZPIEttAwXpk-cKBTN9dfxooDeASGbN8pBu-fg7dZlYgDDDMeCfb0PSpbtZEuziGuC2pu-_4yJxg] Access-Control-Allow-Methods:[GET,OPTIONS] Expires:[Mon, 15 May 2017 17:23:37 GMT] Cache-Control:[private, max-age=0]] 0xc4211f25c0 0 [] false false map[] 0xc420e69900 0xc4201db760}

**Comment by dabigc** [comment]
This looks like my Google account has been banned. Can anyone confirm? I haven't had this happen before.

**Comment by dany20mh** [comment]
I haven’t go any ban so far with this, but if you want to make sure that you got ban or not, you can go to web ui and download one of your file and it should give you an error.

**Comment by dabigc** [comment]
Thanks @dany20mh. That confirmed it. The account is banned right now. Thanks!

**Comment by dany20mh** [comment]
Just wait 24 hour or less and your account will back to normal.
Using this tool haven’t ban me so far, but make sure, you not keep changing your setting over and over, because it will cache your stuff again with Plex scan and that might cause you problem.
Also make sure don’t use rclone mount or transfer files from another outside account (like ACD) while you scanning within that timeframe (if you doing full scan)

**Comment by dabigc** [comment]
@dany20mh Yea, this is definitely a learning experience. I accidentally left my rclone mounted files in the library that was being scanned along with my plexdrive mount location which is likely why this happened.
