### ISSUE TITLE
Allow For Multiple Accounts / Multiple Config sets

### ISSUE THREAD

**Issue by martinbowling** [dweidenfeld/plexdrive#77]
The ability to switch between multiple drive accounts could be very handy. I am thinking that we use some type of alias system

plexdrive --alias=[account_alias] -o allow_other -v 2 /home/martin/drive

the files that, that account would use would then been stored like this

.plexdrive/[account_alias]/cache
.plexdrive/[account_alias]/config.json
.plexdrive/[account_alias]/token.json

the default account would be stored under:

.plexdrive/default/cache
.plexdrive/default/config.json
.plexdrive/default/token.json

this cache, client id/secret & token would be used if no alias was passed

**Comment by zenjabba** [comment]
Looking for the same thing

**Comment by Em31Et** [comment]
Seems that it is as same as the **--config** parameter?
