### ISSUE TITLE
/tmp/chunks filling very quickly, "No space left on device"

### ISSUE THREAD

**Issue by peatnik** [dweidenfeld/plexdrive#81]
Hey,

so i just performed my first plex + sonarr scan after the initial plexdrive cache build yesterday. I use 16GB RAM for /tmp via tmpfs.

Within minutes, my /tmp mount was 100% full and plexdrive is now constantly throwing warnings along the lines of "Write <chunk file>: no space left on device" while plex is performing the scan, i.e. starting and stopping playback.

Looking at the command line options, i should be able to circumvent this problem by setting a max size and clear intervals for the chunk directory.
I still feel this should be reported here because this feels like excessive cache usage. Extrapolating from capped RAM usage, an uncapped cache might use hundreds of gigabytes? To give some possibly relevant context, the google drive is about 130TB and the ~/.plexdrive folder is 70MB.

What would you recommend to prevent this situation and how does the "No space left on device" warning affect plexdrive and the plex scan? 
Thanks

**Comment by olipayne** [comment]
Version 2.1.0 implemented `clear-by-size` parameter to address this

**Comment by dweidenfeld** [comment]
Exactly.
Recommendation: Wait for 3.0.0. It will address some of those issues and will include some major bugfixes.

**Comment by peatnik** [comment]
Is that flag documented somewhere? I can't seem to find it.

**Comment by dweidenfeld** [comment]
Already implemented
```
-t / --temp=
```

I recommend the biggest movie size * 2, so that you will be able to cache at least the 2 recent movies. But this is totally up to you. 
I think there are users caching 500gb ;)
