### ISSUE TITLE
chunks aren't being removed

### ISSUE THREAD

**Issue by RXWatcher1** [dweidenfeld/plexdrive#82]
I have the temp folder set to /tmp but I'm not seeing my chunks dir cleaning up. I am using this:
--clear-chunk-max-size=500g  --clear-chunk-age=120m 
I have chunks in there from the 14th. Previously I had just the --clear-chunk-age and it wasnt removing them either.

My concern is perhaps I am not setting these properly. Do they need quotes?

Thank you!

**Comment by olipayne** [comment]
I had this problem too, make sure you're using the latest binary

**Comment by RXWatcher1** [comment]
Thank you for the assistance. I'll close this and give these a try.

**Comment by RXWatcher1** [comment]
Just to follow up. It appears that if both clear-chunk-max and clear-chunk-age are give, only clear-chunk-max is used which is probably the behavior I was seeing. Your examples do not work, it needs the equal sign in there per https://github.com/dweidenfeld/plexdrive/issues/59
