### ISSUE TITLE
Support for Mac OS

### ISSUE THREAD

**Issue by trulow** [dweidenfeld/plexdrive#88]
Is there any plans to also port this over to Mac OS? I run the current version on my Linux server and it runs great, it would just also be nice to also run this on my backup machine running Mac OS.

**Comment by dany20mh** [comment]
It’s already support macOS and it works great.
Make sure get this file “plexdrive-darwin-10.6-amd64”

**Comment by trulow** [comment]
@dany20mh Thanks, I missed that link. I appreciate the direction though!
