### ISSUE TITLE
Mounting two different accounts on two different mount points?

### ISSUE THREAD

**Issue by alaq** [dweidenfeld/plexdrive#91]
From my own trial and errors, it looks like plexdrive is looking for the cache, the token and the application id.
Would it be possible to mount two accounts on different mountpoints? Is that an enhancement?

**Comment by qnorsten** [comment]
I do this all the time. just use the --config or -c parameter and point it to different config folders.

**Comment by alaq** [comment]
Thank you sir, I need to learn how to read.
