### ISSUE TITLE
Not deleting chucks

### ISSUE THREAD

**Issue by zenjabba** [dweidenfeld/plexdrive#92]
I have 3.0.0 (alpha) precompiled (but also a problem prior)

plexdrive isn't deleting the chunks (I have to set to delete after 50G) but I still have chunks taking up more space (147G    chunks)

**Comment by DTrace001** [comment]
Same issue here using the following, default regarding chunk dir stuff
>-o allow_other -v 2 --uid=1000 --gid=1000 -t /mytmplocation/plexdrive_tmp 

Earliest chunk
> drwxr-xr-x. 2 user1 user1  4096 May 17 08:51 0B7YkGH5s8_b0....

Current time
>Wed May 17 22:46:58 EDT 2017

Chunk dir used size
>$ du -sh *
203G	chunks

>$ plexdrive --version
>3.0.0

**Comment by dweidenfeld** [comment]
The function has been removed in 3.0.0 currently, because of playback issues.
I will re-add it for the final release.
