### ISSUE TITLE
Plex does not pick up subtitles - to slow for playback

### ISSUE THREAD

**Issue by Keeperjoey** [dweidenfeld/plexdrive#93]
I have a VPS and the rclone connection gives decent playback about a 30 MBytes connection but when I use plexdrive its about 5 MBytes. Besides that when I try to play a videofile it fails because it cannot pick up the subtitles can something have gone wrong during the initial cache. If so how do I clear it.

**Comment by mitchelp** [comment]
I'm not aware of any such trouble playing fine for me with subs. You could remove your cache on the config/dir/cache.

Mostly somewhere in /root/.plexdrive or elsewhere. You can see the location when plexdrive starts.
Try to rebuild the cache and don't access the mount before it is done building the cache.

**Comment by dweidenfeld** [comment]
Sorry but I also cannot reproduce the problem. If you need advanced help please visit the slack channel: https://plexdrive.slack.com
