### ISSUE TITLE
Parallel Connection [Feature Request]

### ISSUE THREAD

**Issue by dany20mh** [dweidenfeld/plexdrive#94]
Hi,

I was wondering if you can add a flag that let us to have more connection using for downloading the chunk at the same time.

Some people have better connection and for example can set multiple concurrent connection for downloading the chunk at the same time, and some people lower it.

For example when I was using ocamlfuse, in the configuration, they had `read_ahead_buffers=3` which it was letting you have 3 block to download at the same time.

**Comment by Em31Et** [comment]
To clarify, **read_ahead_buffers** in ocamlfuse is not exactly equal to parallel.
It is the setting to download next N block of same file, not download N block for N files.

**Comment by dany20mh** [comment]
I was just giving and example like we have that kind of flag.

**Comment by dweidenfeld** [comment]
Currently, I am using the bazil-fuse. It will open several goroutines per request (open, read, ...).

> Multiple goroutines may call service methods simultaneously; the methods being called are responsible for appropriate synchronization.

I've implemented a per-file-buffer logic, so you will use one buffer per movie and multiple buffers for multiple movies. So there is already a "parallel connection" feature. 

@dany20mh Do you have playback issues playing back different movies in parallel?

**Comment by dweidenfeld** [comment]
Closed due to inactivity.
