### ISSUE TITLE
Improve indexing performance

### ISSUE THREAD

**Issue by dweidenfeld** [dweidenfeld/plexdrive#95]
Maybe using in memory transactions / frequently writes to a backup file should increase the indexing performance a lot.

Also have to remember QPS throttling using exponential backoff, because faster indexing could cause API bans.

**Comment by scoopydude2002** [comment]
Have you thought about cache the entire drive (probably using a different API call) on the initial cache build like in node-gdrive-fuse? I got about 50,000 items on my GDrive and node-gdrive-fuse takes about 5min to build up the initial cache.

**Comment by dweidenfeld** [comment]
Included in next release.
