### ISSUE TITLE
Rebuild Caching?

### ISSUE THREAD

**Issue by Massaguana** [dweidenfeld/plexdrive#96]
Hello,

 is it possible to rebuild the plexdrive caching? Because i have an big library, an became an GSuite ban when i Scan my Library. Mayby the Caching is not complete...

Thanks
Massaguana

**Comment by qnorsten** [comment]
Just unmount/exit plexdrive and remove the cache file in your config folder. On restart plexdrive should rebuild the cache.

**Comment by glover279** [comment]
Im having the same problem. After clearing the cache directory it wont rebuild the cache. Even after deleting the tokens it still wont rebuild the cache. Is there no way to force it?

**Comment by dweidenfeld** [comment]
@Massaguana You're not using Plexdrive in your service file. You're just using rclone, so if you delete the cache and do not use Plexdrive at all, it will not rebuild the cache ;)
