### ISSUE TITLE
fuse: panic in handler for Read

### ISSUE THREAD

**Issue by MisterSkilly** [dweidenfeld/plexdrive#98]
Hello,

I've been getting random unmounts with plexdrive today, it worked fine before. 

https://pastebin.com/raw/Ufgk1hRN

Sometimes about 3 minutes after remounting it, sometimes after less it spits out that with -v 3

EDIT: Just got a different error after remounting: https://pastebin.com/raw/mKqpQT6v

**Comment by dweidenfeld** [comment]
Do you use version 3.0.0?

**Comment by MisterSkilly** [comment]
@dweidenfeld Oh, I didn't notice there was an update! I'm rebuilding my cache with it right now. On a different note - what's the default max chunks directory size? Mine is currently over 80GB, would the `--clear-chunk-max-size` flag set to e.g. 40GB change that?

**Comment by dweidenfeld** [comment]
yes, but if its already over 40gb you have to wipe it manually first.
