### ISSUE TITLE
chunk tmp filing up drive

### ISSUE THREAD

**Issue by sbcrumb** [dweidenfeld/plexdrive#99]
So I just started using this and my library is kinda large. The tmp chunks are filling up my hard drive to 100% my settings are
plexdrive -o allow_other --chunk-size=20M --clear-chunk-age=2880m -t
And maybe it is this way cause of the intial scan? Or cause I was just trying to move all my media from ACD to google.
I had 540GB's in chunk files.
How can I prevent this from happening?

**Comment by combwizard** [comment]
Currently you have plexdrive clearing the chunk after 48 hours from the last time the chunk was accessed, so it seems normal it would fill up your drive if you access that much data. Try either setting `--clear-chunk-max-size` to something less, or use `--clear-chunk-max-size` to set the maximum size of the chunk folder, and see if that helps?

**Comment by sbcrumb** [comment]
Ok I will try to limit the size of the tmp folder and see if that helps my issue. Thank you.

**Comment by combwizard** [comment]
Good luck. If you set it to something really small you should be able to see if it works real fast.

**Comment by mitchelp** [comment]
If there are any more questions regarding this issue (what isn't a issue). Please ask the guys on our [slack](https://plexdrive.slack.com/shared_invite/MTg1NTg5NzY2Njc4LTE0OTUwNDU3NzAtMjJjNWRiMTAxMg) channel

**Comment by sbcrumb** [comment]
Sorry didn't know there was one or I would have. Thanks.
